-- GENERATED BY tools/extract_conversions.py. DO NOT EDIT.
--
-- Every rate below is read from a fact file by key, never written by hand.
-- `theme/filters/delta.lua` reads this table and no other source of rates.
-- Change a rate in the fact file it cites, then run `just regen`.
-- `just check` regenerates this file and fails if it drifted.
--
-- Sources:
--   data/facts/attack-power.yaml
--   data/facts/crit.yaml
--   data/facts/hit.yaml

return {
  convertible = { "strength", "agility", "melee_hit", "melee_crit", "spell_hit", "spell_crit" },
  rating_per_percent = {
    melee_hit = { divisor = 15.77, source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
    spell_hit = { divisor = 12.62, source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
    melee_crit = { divisor = 22.08, source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
    spell_crit = { divisor = 22.08, source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
  },
  specs = {
    ["affliction warlock"] = {
      name = "Affliction Warlock",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a warlock",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.warlock" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a warlock",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.mage_priest_warlock" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per strength for a warlock",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.warlock" },
        },
      },
    },
    ["arcane mage"] = {
      name = "Arcane Mage",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a mage",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.mage" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a mage",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.mage_priest_warlock" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per strength for a mage",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.mage" },
        },
      },
    },
    ["arms warrior"] = {
      name = "Arms Warrior",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a warrior",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.warrior" },
          { label = "melee crit", unit = "percent", op = "divide", by = 33,
            rate = "33 agility per 1 percent crit for a warrior",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.warrior" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a warrior",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.warrior" },
        },
      },
    },
    ["balance druid"] = {
      name = "Balance Druid",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility in Moonkin Form",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.druid_moonkin_form" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a druid",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.druid" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a druid",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.druid" },
        },
      },
    },
    ["beast mastery hunter"] = {
      name = "Beast Mastery Hunter",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per agility for a hunter",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.hunter" },
          { label = "ranged attack power", unit = "", op = "multiply", by = 1,
            rate = "1 ranged attack power per agility",
            source = "data/facts/attack-power.yaml :: conversions.ranged_attack_power_per_agility_level_70.hunter" },
          { label = "melee crit", unit = "percent", op = "divide", by = 40,
            rate = "40 agility per 1 percent crit for a hunter",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.hunter" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per strength for a hunter",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.hunter" },
        },
      },
    },
    ["combat rogue"] = {
      name = "Combat Rogue",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per agility for a rogue",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.rogue" },
          { label = "melee crit", unit = "percent", op = "divide", by = 40,
            rate = "40 agility per 1 percent crit for a rogue",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.rogue" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per strength for a rogue",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.rogue" },
        },
      },
    },
    ["destruction warlock"] = {
      name = "Destruction Warlock",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a warlock",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.warlock" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a warlock",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.mage_priest_warlock" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per strength for a warlock",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.warlock" },
        },
      },
    },
    ["elemental shaman"] = {
      name = "Elemental Shaman",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a shaman",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.shaman" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a shaman",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.shaman" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a shaman",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.shaman" },
        },
      },
    },
    ["enhancement shaman"] = {
      name = "Enhancement Shaman",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a shaman",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.shaman" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a shaman",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.shaman" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a shaman",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.shaman" },
        },
      },
    },
    ["feral bear"] = {
      name = "Feral Bear",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility in Bear Form",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.druid_bear_form" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a druid",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.druid" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a druid",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.druid" },
        },
      },
    },
    ["feral cat"] = {
      name = "Feral Cat",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per agility in Cat Form",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.druid_cat_form" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a druid",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.druid" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a druid",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.druid" },
        },
      },
    },
    ["feral dire bear"] = {
      name = "Feral Dire Bear",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility in Dire Bear Form",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.druid_dire_bear_form" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a druid",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.druid" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a druid",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.druid" },
        },
      },
    },
    ["fire mage"] = {
      name = "Fire Mage",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a mage",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.mage" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a mage",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.mage_priest_warlock" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per strength for a mage",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.mage" },
        },
      },
    },
    ["fury warrior"] = {
      name = "Fury Warrior",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a warrior",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.warrior" },
          { label = "melee crit", unit = "percent", op = "divide", by = 33,
            rate = "33 agility per 1 percent crit for a warrior",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.warrior" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a warrior",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.warrior" },
        },
      },
    },
    ["holy paladin"] = {
      name = "Holy Paladin",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a paladin",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.paladin" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a paladin",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.paladin" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a paladin",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.paladin" },
        },
      },
    },
    ["marksmanship hunter"] = {
      name = "Marksmanship Hunter",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per agility for a hunter",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.hunter" },
          { label = "ranged attack power", unit = "", op = "multiply", by = 1,
            rate = "1 ranged attack power per agility",
            source = "data/facts/attack-power.yaml :: conversions.ranged_attack_power_per_agility_level_70.hunter" },
          { label = "melee crit", unit = "percent", op = "divide", by = 40,
            rate = "40 agility per 1 percent crit for a hunter",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.hunter" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per strength for a hunter",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.hunter" },
        },
      },
    },
    ["priest healer"] = {
      name = "Priest Healer",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a priest",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.priest" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a priest",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.mage_priest_warlock" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per strength for a priest",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.priest" },
        },
      },
    },
    ["protection paladin"] = {
      name = "Protection Paladin",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a paladin",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.paladin" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a paladin",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.paladin" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a paladin",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.paladin" },
        },
      },
    },
    ["protection warrior"] = {
      name = "Protection Warrior",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a warrior",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.warrior" },
          { label = "melee crit", unit = "percent", op = "divide", by = 33,
            rate = "33 agility per 1 percent crit for a warrior",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.warrior" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a warrior",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.warrior" },
        },
      },
    },
    ["restoration druid"] = {
      name = "Restoration Druid",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility in no form",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.druid_no_form" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a druid",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.druid" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a druid",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.druid" },
        },
      },
    },
    ["restoration shaman"] = {
      name = "Restoration Shaman",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a shaman",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.shaman" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a shaman",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.shaman" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a shaman",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.shaman" },
        },
      },
    },
    ["retribution paladin"] = {
      name = "Retribution Paladin",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a paladin",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.paladin" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a paladin",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.paladin" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 2,
            rate = "2 attack power per strength for a paladin",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.paladin" },
        },
      },
    },
    ["shadow priest"] = {
      name = "Shadow Priest",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 0,
            rate = "no melee attack power from agility for a priest",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.priest" },
          { label = "melee crit", unit = "percent", op = "divide", by = 25,
            rate = "25 agility per 1 percent crit for a priest",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.mage_priest_warlock" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per strength for a priest",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.priest" },
        },
      },
    },
    ["survival hunter"] = {
      name = "Survival Hunter",
      rules = {
        agility = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per agility for a hunter",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_agility_level_70.hunter" },
          { label = "ranged attack power", unit = "", op = "multiply", by = 1,
            rate = "1 ranged attack power per agility",
            source = "data/facts/attack-power.yaml :: conversions.ranged_attack_power_per_agility_level_70.hunter" },
          { label = "melee crit", unit = "percent", op = "divide", by = 40,
            rate = "40 agility per 1 percent crit for a hunter",
            source = "data/facts/crit.yaml :: conversions.agility_per_percent_crit_level_70.hunter" },
        },
        melee_crit = {
          { label = "melee crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent melee crit",
            source = "data/facts/crit.yaml :: conversions.melee_crit_rating_per_percent" },
        },
        melee_hit = {
          { label = "melee and ranged hit", unit = "percent", op = "divide", by = 15.77,
            rate = "15.77 rating per 1 percent melee and ranged hit",
            source = "data/facts/hit.yaml :: conversions.melee_ranged_hit_rating_per_percent" },
        },
        spell_crit = {
          { label = "spell crit", unit = "percent", op = "divide", by = 22.08,
            rate = "22.08 rating per 1 percent spell crit",
            source = "data/facts/crit.yaml :: conversions.spell_crit_rating_per_percent" },
        },
        spell_hit = {
          { label = "spell hit", unit = "percent", op = "divide", by = 12.62,
            rate = "12.62 rating per 1 percent spell hit",
            source = "data/facts/hit.yaml :: conversions.spell_hit_rating_per_percent" },
        },
        strength = {
          { label = "attack power", unit = "", op = "multiply", by = 1,
            rate = "1 attack power per strength for a hunter",
            source = "data/facts/attack-power.yaml :: conversions.melee_attack_power_per_strength_level_70.hunter" },
        },
      },
    },
  },
}
