-- GENERATED BY tools/extract_judgments.py. DO NOT EDIT.
--
-- What the council concluded, keyed by item id and the spec name the cards use.
-- Written from data/judgments/priorities.yaml; change that file and run `just regen`.
--
-- Nothing here is a fact. Every figure a card prints comes from data/facts, and
-- the cap position on a card is generated separately. This is the judgment.
return {
}
