-- GENERATED BY tools/extract_unranked.py. DO NOT EDIT.
--
-- The items a class can wear that no workbook tab ranks: the relics, and the
-- trinkets locked to one class. Keyed by spec, in name order, with NO rank and
-- NO score, because neither exists for these and inventing one would decide
-- something the council decides.
--
-- `shortlist.lua` renders these under their own heading and skips any item it
-- has already shown in a ranked section.
return {
  ["Affliction Warlock"] = {
    { item_id = 32493, name = "Ashtongue Talisman of Shadows", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30449, name = "Void Star Talisman", slot = "Trinket", location = "High Astromancer Solarian" },
  },
  ["Arcane Mage"] = {
    { item_id = 32488, name = "Ashtongue Talisman of Insight", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30720, name = "Serpent-Coil Braid", slot = "Trinket", location = "Morogrim Tidewalker" },
  },
  ["Arms Warrior"] = {
    { item_id = 32485, name = "Ashtongue Talisman of Valor", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30446, name = "Solarian's Sapphire", slot = "Trinket", location = "High Astromancer Solarian" },
  },
  ["Balance Druid"] = {
    { item_id = 28568, name = "Idol of the Avian Heart", slot = "Relic", location = "Moroes" },
    { item_id = 30051, name = "Idol of the Crescent Goddess", slot = "Relic", location = "Hydross the Unstable" },
    { item_id = 32387, name = "Idol of the Raven Goddess", slot = "Relic", location = "" },
    { item_id = 32257, name = "Idol of the White Stag", slot = "Relic", location = "Supremus" },
    { item_id = 32486, name = "Ashtongue Talisman of Equilibrium", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30664, name = "Living Root of the Wildheart", slot = "Trinket", location = "Hydross the Unstable" },
  },
  ["Beast Mastery Hunter"] = {
    { item_id = 32487, name = "Ashtongue Talisman of Swiftness", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30448, name = "Talon of Al'ar", slot = "Trinket", location = "Al'ar" },
  },
  ["Combat Rogue"] = {
    { item_id = 32492, name = "Ashtongue Talisman of Lethality", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30450, name = "Warp-Spring Coil", slot = "Trinket", location = "Void Reaver" },
  },
  ["Destruction Warlock"] = {
    { item_id = 32493, name = "Ashtongue Talisman of Shadows", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30449, name = "Void Star Talisman", slot = "Trinket", location = "High Astromancer Solarian" },
  },
  ["Elemental Shaman"] = {
    { item_id = 32330, name = "Totem of Ancestral Guidance", slot = "Relic", location = "Teron Gorefiend" },
    { item_id = 28523, name = "Totem of Healing Rains", slot = "Relic", location = "Maiden of Virtue" },
    { item_id = 27815, name = "Totem of the Astral Winds", slot = "Relic", location = "" },
    { item_id = 30023, name = "Totem of the Maelstrom", slot = "Relic", location = "Trash / zone drop" },
    { item_id = 28248, name = "Totem of the Void", slot = "Relic", location = "" },
    { item_id = 32491, name = "Ashtongue Talisman of Vision", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30663, name = "Fathom-Brooch of the Tidewalker", slot = "Trinket", location = "Fathom-Lord Karathress" },
  },
  ["Enhancement Shaman"] = {
    { item_id = 32330, name = "Totem of Ancestral Guidance", slot = "Relic", location = "Teron Gorefiend" },
    { item_id = 28523, name = "Totem of Healing Rains", slot = "Relic", location = "Maiden of Virtue" },
    { item_id = 27815, name = "Totem of the Astral Winds", slot = "Relic", location = "" },
    { item_id = 30023, name = "Totem of the Maelstrom", slot = "Relic", location = "Trash / zone drop" },
    { item_id = 28248, name = "Totem of the Void", slot = "Relic", location = "" },
    { item_id = 32491, name = "Ashtongue Talisman of Vision", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30663, name = "Fathom-Brooch of the Tidewalker", slot = "Trinket", location = "Fathom-Lord Karathress" },
  },
  ["Feral Bear"] = {
    { item_id = 28568, name = "Idol of the Avian Heart", slot = "Relic", location = "Moroes" },
    { item_id = 30051, name = "Idol of the Crescent Goddess", slot = "Relic", location = "Hydross the Unstable" },
    { item_id = 32387, name = "Idol of the Raven Goddess", slot = "Relic", location = "" },
    { item_id = 32257, name = "Idol of the White Stag", slot = "Relic", location = "Supremus" },
    { item_id = 32486, name = "Ashtongue Talisman of Equilibrium", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30664, name = "Living Root of the Wildheart", slot = "Trinket", location = "Hydross the Unstable" },
  },
  ["Feral Cat"] = {
    { item_id = 28568, name = "Idol of the Avian Heart", slot = "Relic", location = "Moroes" },
    { item_id = 30051, name = "Idol of the Crescent Goddess", slot = "Relic", location = "Hydross the Unstable" },
    { item_id = 32387, name = "Idol of the Raven Goddess", slot = "Relic", location = "" },
    { item_id = 32257, name = "Idol of the White Stag", slot = "Relic", location = "Supremus" },
    { item_id = 32486, name = "Ashtongue Talisman of Equilibrium", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30664, name = "Living Root of the Wildheart", slot = "Trinket", location = "Hydross the Unstable" },
  },
  ["Fury Warrior"] = {
    { item_id = 32485, name = "Ashtongue Talisman of Valor", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30446, name = "Solarian's Sapphire", slot = "Trinket", location = "High Astromancer Solarian" },
  },
  ["Holy Paladin"] = {
    { item_id = 30063, name = "Libram of Absolute Truth", slot = "Relic", location = "The Lurker Below" },
    { item_id = 27484, name = "Libram of Avengement", slot = "Relic", location = "" },
    { item_id = 28592, name = "Libram of Souls Redeemed", slot = "Relic", location = "Romulo; The Big Bad Wolf; The Crone" },
    { item_id = 27917, name = "Libram of the Eternal Rest", slot = "Relic", location = "" },
    { item_id = 32368, name = "Tome of the Lightbringer", slot = "Relic", location = "Mother Shahraz" },
    { item_id = 32489, name = "Ashtongue Talisman of Zeal", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30447, name = "Tome of Fiery Redemption", slot = "Trinket", location = "Al'ar" },
  },
  ["Priest Healer"] = {
    { item_id = 32490, name = "Ashtongue Talisman of Acumen", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30665, name = "Earring of Soulful Meditation", slot = "Trinket", location = "The Lurker Below" },
  },
  ["Protection Paladin"] = {
    { item_id = 30063, name = "Libram of Absolute Truth", slot = "Relic", location = "The Lurker Below" },
    { item_id = 27484, name = "Libram of Avengement", slot = "Relic", location = "" },
    { item_id = 28592, name = "Libram of Souls Redeemed", slot = "Relic", location = "Romulo; The Big Bad Wolf; The Crone" },
    { item_id = 27917, name = "Libram of the Eternal Rest", slot = "Relic", location = "" },
    { item_id = 32368, name = "Tome of the Lightbringer", slot = "Relic", location = "Mother Shahraz" },
    { item_id = 32489, name = "Ashtongue Talisman of Zeal", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30447, name = "Tome of Fiery Redemption", slot = "Trinket", location = "Al'ar" },
  },
  ["Protection Warrior"] = {
    { item_id = 32485, name = "Ashtongue Talisman of Valor", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30446, name = "Solarian's Sapphire", slot = "Trinket", location = "High Astromancer Solarian" },
  },
  ["Restoration Druid"] = {
    { item_id = 28568, name = "Idol of the Avian Heart", slot = "Relic", location = "Moroes" },
    { item_id = 30051, name = "Idol of the Crescent Goddess", slot = "Relic", location = "Hydross the Unstable" },
    { item_id = 32387, name = "Idol of the Raven Goddess", slot = "Relic", location = "" },
    { item_id = 32257, name = "Idol of the White Stag", slot = "Relic", location = "Supremus" },
    { item_id = 32486, name = "Ashtongue Talisman of Equilibrium", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30664, name = "Living Root of the Wildheart", slot = "Trinket", location = "Hydross the Unstable" },
  },
  ["Restoration Shaman"] = {
    { item_id = 32330, name = "Totem of Ancestral Guidance", slot = "Relic", location = "Teron Gorefiend" },
    { item_id = 28523, name = "Totem of Healing Rains", slot = "Relic", location = "Maiden of Virtue" },
    { item_id = 27815, name = "Totem of the Astral Winds", slot = "Relic", location = "" },
    { item_id = 30023, name = "Totem of the Maelstrom", slot = "Relic", location = "Trash / zone drop" },
    { item_id = 28248, name = "Totem of the Void", slot = "Relic", location = "" },
    { item_id = 32491, name = "Ashtongue Talisman of Vision", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30663, name = "Fathom-Brooch of the Tidewalker", slot = "Trinket", location = "Fathom-Lord Karathress" },
  },
  ["Retribution Paladin"] = {
    { item_id = 30063, name = "Libram of Absolute Truth", slot = "Relic", location = "The Lurker Below" },
    { item_id = 27484, name = "Libram of Avengement", slot = "Relic", location = "" },
    { item_id = 28592, name = "Libram of Souls Redeemed", slot = "Relic", location = "Romulo; The Big Bad Wolf; The Crone" },
    { item_id = 27917, name = "Libram of the Eternal Rest", slot = "Relic", location = "" },
    { item_id = 32368, name = "Tome of the Lightbringer", slot = "Relic", location = "Mother Shahraz" },
    { item_id = 32489, name = "Ashtongue Talisman of Zeal", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30447, name = "Tome of Fiery Redemption", slot = "Trinket", location = "Al'ar" },
  },
  ["Shadow Priest"] = {
    { item_id = 32490, name = "Ashtongue Talisman of Acumen", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30665, name = "Earring of Soulful Meditation", slot = "Trinket", location = "The Lurker Below" },
  },
  ["Survival Hunter"] = {
    { item_id = 32487, name = "Ashtongue Talisman of Swiftness", slot = "Trinket", location = "Ashtongue Deathsworn, Exalted" },
    { item_id = 30448, name = "Talon of Al'ar", slot = "Trinket", location = "Al'ar" },
  },
}
