#!/usr/bin/env python3
"""Total every stat each captured set carries, not only its hit.

THE GEAR WAS ALREADY COLLECTED AND ONLY ONE COLUMN WAS READ. The captures under
sim-profiles/hit-capture name the item in every slot, with its id, at three
points in the tier. items.csv holds the full stat line for each of those ids.
So the crit, haste, attack power, spell damage, expertise, stamina and armor a
set carries were all determinable from files already on disk, and the first pass
read the hit column and stopped.

That mattered most where a set LOSES a stat wholesale. Gronnstalker's Armor
carries no hit on any piece and the Beast Mastery Hunter falls 121 to 63 across
the tokens, which the hit pass did find. The same shape can occur in crit, in
haste or in expertise and nothing here would have seen it, because nothing was
looking.

WHAT THIS DOES NOT DO. It sums item stats. It applies no talent, no raid buff,
no gem and no enchant, exactly as the hit figures do, so the totals are
comparable with hit.yaml's supplied figures and with each other. It does not
score a set, rank a spec or value one stat against another.

A SLOT THAT DOES NOT RESOLVE IS COUNTED AND NAMED, never skipped silently. A
total quietly missing a trinket is worse than a total that says it is missing
one.

Usage:
    python3 tools/extract_set_stats.py --out data/facts/set-stats.yaml
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import yaml

ITEMS = Path("data/facts/items.csv")
CAPTURES = Path("data/facts/sim-profiles/hit-capture")

# The three states each capture reports. `downgraded_slots` and `uncertain` sit
# beside them in some files as prose, so the anchors are named rather than
# discovered.
ANCHORS = ("entry", "tier_hands_only", "tier_hands_and_head")

# Every stat worth totalling for a raid set.
#
# RESILIENCE IS INCLUDED, having been excluded on a rationale the data refutes.
# The reasoning was that resilience belongs to PvP armor, which this project
# excludes. But PvP WEAPONS are permitted at every anchor, and all the
# resilience in the corpus arrives on those: eight specs across thirteen
# anchors carry it, and the Feral Bear capture spends a paragraph pricing 33
# resilience against roughly 50 defense rating of crit avoidance, a trade no
# reader could check while the column was absent.
#
# THE SCHOOL COLUMNS ARE NOT FOLDED INTO spell_damage AND ARE NOT SUMMED WITH
# EACH OTHER. They are recorded as themselves, because either shortcut is wrong.
# In items.csv the generic and school columns are mutually EXCLUSIVE: of 957
# items, none carries both, and eighteen carry only a school. So omitting them
# understated the Shadow Priest's entry spell damage by 209 of 824, a quarter of
# it. But summing the six would over-count in the other direction, because a
# Spellfire piece reads fire 50 AND arcane 50 and that is one +50 applying to
# two schools rather than +100. Which school a spec actually uses is a per-spec
# reading, and making it here would be deciding rather than collecting, so the
# columns are published as they stand and the reader takes the one that applies.
#
# block_rating sits beside block_value because they are different stats and the
# tank threshold needs the first. Block VALUE is how much a block absorbs; block
# RATING is how often one happens, and it is block chance that enters the 102.4
# uncrushable sum with miss, dodge and parry. Publishing three of those four
# terms invites an arithmetic the fourth is needed for.
STATS = [
    "strength", "agility", "stamina", "intellect", "spirit",
    "attack_power", "ranged_attack_power", "feral_attack_power",
    "spell_damage", "healing_power",
    "arcane_damage", "fire_damage", "frost_damage",
    "holy_damage", "nature_damage", "shadow_damage",
    "melee_hit", "melee_crit", "melee_haste",
    "spell_hit", "spell_crit", "spell_haste", "spell_pen",
    "expertise", "armor_pen", "defense", "dodge", "parry",
    "block_rating", "block_value", "resilience", "armor", "bonus_armor",
]

BANNER = """\
# GENERATED BY tools/extract_set_stats.py. DO NOT EDIT.
#
# What each captured set carries, stat by stat, at three points in the tier.
# Built by joining the per-slot item ids in data/facts/sim-profiles/hit-capture
# to the stat lines in data/facts/items.csv. To change a figure here, change the
# capture it came from.
#
# ITEM STATS ONLY. No talent, no raid buff, no gem, no enchant, no consumable,
# which is the same rule hit.yaml applies to its supplied figures, so these
# totals are comparable with those and with each other.
#
# NOTHING HERE RANKS ANYTHING. It is what the gear carries.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--items", type=Path, default=ITEMS)
    ap.add_argument("--captures", type=Path, default=CAPTURES)
    ap.add_argument("--out", type=Path, default=Path("data/facts/set-stats.yaml"))
    args = ap.parse_args()

    items = {int(row["item_id"]): row
             for row in csv.DictReader(args.items.open())}

    specs: dict[str, dict] = {}
    unresolved_total = 0
    for path in sorted(args.captures.glob("*.yaml")):
        data = yaml.safe_load(path.read_text())
        # Only files carrying anchors are captures. See extract_hit_captures.
        if not isinstance(data, dict) or "anchors" not in data:
            continue
        spec = data.get("spec")
        if not spec:
            continue
        block: dict[str, dict] = {"capture": str(path)}
        for anchor in ANCHORS:
            state = (data.get("anchors") or {}).get(anchor)
            if not isinstance(state, dict):
                continue
            rows = state.get("hit_by_slot")
            if not isinstance(rows, dict):
                continue

            totals = dict.fromkeys(STATS, 0)
            unresolved: list[str] = []
            counted = 0
            # How many gem sockets the set carries. hit.yaml prices a shortfall
            # in hit gems and set-stats could not show whether the sockets to
            # hold them exist, which is the one thing that makes a gem budget
            # real rather than notional. The column is pipe-separated colours,
            # so the count is the number of entries.
            sockets = 0
            for slot, row in rows.items():
                if not isinstance(row, dict):
                    continue
                item_id = row.get("id")
                record = items.get(item_id) if isinstance(item_id, int) else None
                if record is None:
                    # AN EMPTY OFF-HAND IS NOT A GAP AND A NULL ID IS NOT AN
                    # EMPTY OFF-HAND. Treating every null id as empty swallowed
                    # two real items, an idol and a libram written without an
                    # id, and still reported slots_unresolved as zero. Only the
                    # name settles whether a slot is genuinely empty.
                    name = str(row.get("item") or "").lower()
                    if not name or "none" in name or "empty" in name:
                        continue
                    unresolved.append(f"{slot}: {row.get('item')} ({item_id})")
                    continue
                counted += 1
                sockets += len([c for c in (record.get("sockets") or "").split("|") if c])
                for stat in STATS:
                    value = record.get(stat)
                    if value:
                        totals[stat] += int(float(value))

            entry = {stat: value for stat, value in totals.items() if value}
            entry["slots_counted"] = counted
            entry["gem_sockets"] = sockets
            if unresolved:
                entry["slots_unresolved"] = unresolved
                unresolved_total += len(unresolved)
            # The hit the capture itself states, carried across so a reader can
            # see the join agreeing with the source rather than trusting it.
            stated = state.get("total_item_hit")
            if stated is not None:
                entry["hit_stated_by_capture"] = int(stated)
            block[anchor] = entry
        specs[spec] = block

    document = {
        "meta": {
            "generated_by": "tools/extract_set_stats.py",
            "counts": "item stats only",
            "excludes": "talents, raid buffs, gems, enchants, consumables",
            "specs": len(specs),
            "slots_unresolved": unresolved_total,
            "sibling_files": [
                "data/facts/hit-captured.yaml",
                "data/facts/items.csv",
                "data/facts/sim-profiles/token-arithmetic.yaml",
            ],
            # No count is restated here. This sentence used to add "and
            # token-arithmetic.yaml disagrees for six specs", restating the
            # contested-spec list whose one home is the caveat in
            # hit-captured.yaml, and the restated count was read against a
            # DIFFERENT three-spec disclosure inside token-arithmetic.yaml
            # (claims made against captures holding fewer than four tier
            # pieces) and flagged as a contradiction. Link, never restate.
            "which_tier_slots_are_worn_was_ASSUMED": (
                "The same caveat hit-captured.yaml carries applies to every "
                "figure here. The tier states hold the hands token, then the "
                "hands and head tokens, because the capture brief said so. "
                "Which specs' token arithmetic contests that configuration "
                "is stated once, in meta.which_tier_slots_are_worn_was_"
                "ASSUMED_not_derived in data/facts/hit-captured.yaml. Read "
                "it before quoting a tier total."),
        },
        "specs": specs,
    }
    args.out.write_text(
        BANNER + "\n" + yaml.safe_dump(document, sort_keys=True, width=78))
    print(f"{len(specs)} spec(s) -> {args.out}")
    print(f"  {unresolved_total} slot(s) could not be resolved to {args.items}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
