#!/usr/bin/env python3
"""Write each spec's cap position as the rows a card renders.

The Constraints field on a priority card used to be written by hand, once per card.
It carried no judgment: every figure in it was already in hit.yaml or haste.yaml,
so eight cards restated two fact files in prose that would go stale the first
time a cap figure moved. This builds the same sentences from those files.

WHAT IS AND IS NOT HERE. This block describes the SPEC, not the item. It states
where the spec sits against its caps and what its hit is still worth. Whether a
particular item's hit matters enough to route it one way is judgment, and that
belongs with the priority, not here. Keeping the block item-independent is what lets
one spec's text be built once and used on every card.

Every sentence traces to a field:

    the cap                 hit.yaml raw_caps, and the spec's cap
    the threat floor        hit.yaml cap_kind
    the talent              hit.yaml talent, and not_credited where it is not
    the group buff          hit.yaml group_buff_name and group_buff_percent
    what gear must find     hit.yaml net_target_rating
    what gear supplies      hit.yaml supplied_at_p3_entry, supplied_at_tier_anchor
    what a real set carries hit-captured.yaml, generated from the per-spec captures
    the dual-wield cap      hit.yaml dual_wield_specs, raw_caps
    the haste threshold     haste.yaml verified_threshold

Usage:
    python3 tools/extract_constraints.py --out theme/filters/constraints.generated.lua
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

# The registry that maps a card's spec name to its id in the fact files. It is
# extract_ladder's, because that file already holds the one mapping written out
# rather than inferred, and a second copy of it here is the copy that would
# disagree. Its twenty-one specs are the ones hit.yaml carries rows for; the
# three extra names extract_conversions knows are unrostered and hold no row.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_ladder import SPECS  # noqa: E402

HIT = Path("data/facts/hit.yaml")
CAPTURED = Path("data/facts/hit-captured.yaml")
HASTE = Path("data/facts/haste.yaml")
CRIT = Path("data/facts/crit.yaml")

HEADER = """-- GENERATED BY tools/extract_constraints.py. DO NOT EDIT.
--
-- Where each spec sits against its caps, keyed by the spec name the cards use.
--
-- EACH ENTRY IS A LIST OF LINES, NOT SENTENCES. A line holding two tabs is a
-- figure, "label<TAB>value<TAB>note", and the note may be empty. A line with no
-- tab is a sentence that runs the full width. An empty line is a break between
-- groups. theme/filters/specs.lua splits on the tab and lays the columns out. Written from data/facts/hit.yaml and data/facts/haste.yaml;
-- change those and run `just regen`.
--
-- This describes the SPEC and never the item on the card. What an item's hit is
-- worth to a claimant is judgment and is not here."""

# What each cap is called, and what it stops from missing. The cap names are the
# ones the cards already used, because a reader who has seen one card should
# recognise the phrase on the next.
CAP_NAME = {
    "melee_special": ("special attacks", "special-attack cap"),
    "ranged": ("shots", "ranged cap"),
    "spell": ("spells", "spell hit cap"),
}

# WHICH CAP A BLOCK IS ABOUT, said on its first row.
#
# A spec that casts and swings gets one block per cap, and every block opened
# with the words "Hit cap". So a Protection Paladin card showed two stacks of
# figures, one reading 9 percent and the other 16, with nothing anywhere saying
# that the first is for special attacks and the second for spells. The guild
# lead asked what they were on 13 August 2026. They are the same question asked
# of two different attack types, and the row now says which.
CAP_ROW_LABEL = {
    "melee_special": "Special-attack hit cap",
    "ranged": "Ranged hit cap",
    "spell": "Spell hit cap",
}


def percent(rating: float, per_percent: float) -> str:
    """A rating as a percentage, one decimal, trailing zero dropped.

    Cards speak in percent and never in rating, so the conversion happens here
    and no rating reaches the rendered sentence.
    """
    value = round(rating / per_percent, 1)
    text = f"{value:.1f}".rstrip("0").rstrip(".")
    return text + "%"


def talent_clause(spec: dict, cap_percent: str) -> str:
    """What the build supplies before gear, or why it supplies nothing."""
    talent = spec.get("talent") or {}
    name = talent.get("name")
    if talent.get("percent"):
        return f"the {name} talent supplies {talent['percent']}% of that"
    if not name or name == "none":
        return f"no hit talent exists for this spec"
    reason = talent.get("not_credited")
    if reason == "build_does_not_reach_it":
        return (f"the {name} talent sits in the {talent.get('tree')} tree, "
                "which this build does not reach")
    # A DIFFERENT REASON FROM THE ONE ABOVE, and the two warriors are why. An
    # Arms build cannot reach a talent 30 points deep in Fury. A Fury build can
    # reach it and this guild's build does not spend the points, which is a fact
    # about this raid rather than about the tree.
    if reason == "build_does_not_take_it":
        return (f"the {name} talent is reachable in the {talent.get('tree')} "
                "tree and this raid's build does not take it")
    if reason == "does_not_cover_the_filler_spell":
        return (f"the {name} talent does not cover this spec's filler spell, "
                "so none of it counts")
    raise SystemExit(
        f"extract_constraints.py: {spec['id']} credits no talent percent and "
        f"gives no reason. Add `not_credited` to its talent block in {HIT}, "
        "with one of the values the generator recognises."
    )


def trim(value: float) -> str:
    """One decimal, trailing zero dropped. A cap of 142 rating is 9.004%, and
    printing that back is precision the figure does not have."""
    return f"{round(value, 1):.1f}".rstrip("0").rstrip(".")


def upper_first(text: str) -> str:
    """Sentence case without touching the rest. `str.capitalize` lowercases it,
    which turned Totem of Wrath into totem of wrath."""
    return text[:1].upper() + text[1:]


def assumed_rating(hit: dict, cap: str) -> tuple[float, str]:
    """The assumed raid debuff this cap gets, as rating and as a name.

    IT IS NOT IN THE SUPPLY FIGURES. `supplied_at_p3_entry` counts gear, and the
    assumed buffs sit beside it, which is why hit.yaml records a spec as full
    while its gear alone reads short. The generated text has to add them or it
    says a spec misses when the file says it does not, and the cards said
    exactly that before this generator replaced them.

    Improved Faerie Fire supplies melee and ranged hit only in 2.4.3, so a
    caster gets nothing from it. That correction travels with the buff in the
    fact file and is honored by matching on what it supplies.
    """
    wants = {
        "melee_special": "melee_and_ranged_hit",
        "ranged": "melee_and_ranged_hit",
        "spell": "spell_hit",
    }[cap]
    for buff in hit.get("assumed_buffs") or []:
        if buff.get("supplies") == wants:
            return float(buff["rating_equivalent"]), buff["name"]
    return 0.0, ""


def position(supply: float, target: float, per_percent: float) -> tuple[str, str]:
    """A supply against a target, as a margin and the state it puts the spec in."""
    gap = supply - target
    return percent(abs(gap), per_percent), ("over" if gap >= 0 else "short")


# A row is "label<TAB>value<TAB>note" and a line with no tab is a note that runs
# the full width. An empty string is a break between groups. theme/filters/
# specs.lua splits on the tab and aligns the columns.
#
# IT WAS PROSE UNTIL 9 AUGUST 2026 AND THE GUILD LEAD ASKED FOR FACTS. The
# sentences were joined into one paragraph and printed on every claimant card,
# up to twenty times on an item page. Three things made them hard to read: they
# were framed on a "four to six weeks in" forecast, which is not an anchor
# anybody acts on; they restated the anchor in full on every line; and the
# margin was measured against what GEAR still had to find rather than against
# the cap, so a Combat Rogue line read "about 14.1%, which is about 13.1% over"
# against a 9 percent cap, which is correct and reads like a typo.
SEP = "\t"
BREAK = ""


def row(label: str, value: str, note: str = "") -> str:
    """One aligned figure, as "label<TAB>value<TAB>note".

    THE SEPARATOR IS LOAD-BEARING AND NOTHING ESCAPED IT. specs.lua splits on
    exactly two tabs, so a tab inside any of the three fields silently shifted
    every column: an adversarial review put one in a talent name on 10 August
    2026 and got a card reading label "Elemental", value "Precision", note
    "-6%", with no error anywhere. A bare sentence carrying two tabs would
    render as a figure, and a sentence that came out empty would render as a
    group break.
    None of the three can happen now, because a tab in a payload stops the
    build here, where the fact file that caused it can be named.
    """
    for name, field in (("label", label), ("value", value), ("note", note)):
        if SEP in field:
            raise SystemExit(
                f"extract_constraints.py: the {name} {field!r} contains a tab, "
                "which is the column separator this file writes and "
                "theme/filters/specs.lua splits on. Remove it from the fact "
                f"file that supplies it, or the card renders wrong silently.")
    return f"{label}{SEP}{value}{SEP}{note}"


def sentence(text: str) -> str:
    """A note that runs the full width, guarded the same way as a row."""
    if not text.strip():
        raise SystemExit(
            "extract_constraints.py: an empty sentence reached the output, and "
            "an empty line is how a GROUP BREAK is written, so it would render "
            "as one.")
    if SEP in text:
        raise SystemExit(
            f"extract_constraints.py: the sentence {text[:60]!r} contains a "
            "tab, and two tabs would make specs.lua render it as a figure row.")
    return text


def margin_note(supply: float, target: float, per_percent: float) -> str:
    """The margin, said as a reader would act on it."""
    amount, state = position(supply, target, per_percent)
    return ("clear by " if state == "over" else "short by ") + amount


def cap_sentences(spec: dict, hit: dict, cap: str, rating_per_percent: float,
                  cap_rating: float, target_rating: float,
                  entry: float, tier: float,
                  captured: dict) -> list[str]:
    """One cap, from what stops missing through to what the tier profile holds."""
    attacks, cap_label = CAP_NAME[cap]
    cap_percent = percent(cap_rating, rating_per_percent)
    kind = ("threat floor" if spec.get("cap_kind") == "threat_floor"
            else attacks)
    out = [row(CAP_ROW_LABEL[cap], cap_percent, kind)]

    # CALLED FOR ITS GUARD, NOT ITS RETURN VALUE. talent_clause raises when a
    # spec credits no talent percent and gives no reason, which is the check
    # that catches a half-filled talent block. Its sentence is used later, in
    # the not-credited branch below; the prose rewrite of 9 August 2026 left
    # this call building a `supplies` list that nothing read, and an
    # adversarial review found the dead value.
    talent_clause(spec, cap_percent)
    # A SPEC CAN CREDIT MORE THAN ONE TALENT. The Elemental Shaman is the case
    # that forced this: it takes Elemental Precision for 6 percent AND Nature's
    # Guidance for 3, and a model with one talent slot silently dropped the
    # second, which understated the spec by 38 rating and printed it short at
    # every anchor when it is full at all three.
    extra = spec.get("additional_talents") or []

    # WHAT A TALENT APPLIES TO, CHECKED. The reconciliation below only asks
    # whether the percentages add up to the recorded target, so a MELEE talent
    # credited to a caster passed silently as long as the target was lowered to
    # match. An adversarial review pointed out that this is exactly the shape
    # and size of the Elemental Shaman change, 3 percent and 38 rating, which
    # moved a spec from short to full at every anchor. Two files agreeing with
    # each other is not evidence when one was edited to agree.
    wants = {"melee_special": "melee", "ranged": "melee",
             "spell": "spell"}.get(cap, "both")
    for one in [t for t in extra if t.get("percent")]:
        applies = one.get("applies_to", "both")
        if applies != "both" and wants != "both" and applies != wants:
            raise SystemExit(
                f"extract_constraints.py: {spec['id']} has a {cap} cap and "
                f"credits {one['name']}, which its own applies_to says covers "
                f"{applies!r}. A talent that does not reach this cap cannot be "
                f"subtracted from it. Fix the entry in {HIT}.")

    talent_percent = ((spec.get("talent") or {}).get("percent") or 0) \
        + sum(t.get("percent") or 0 for t in extra)
    buff_percent = spec.get("group_buff_percent") or 0

    # WHAT GEAR MUST FIND IS SUBTRACTED IN PERCENT, NOT DIVIDED FROM THE TARGET
    # RATING. The rating is the percentage already rounded once, so dividing it
    # back rounds a second time and printed 4.1% where the file says 9 minus 5.
    # The target rating is still checked against it, because the two are
    # separately authored and either can be edited alone.
    remaining = float(cap_rating) / rating_per_percent - talent_percent - buff_percent
    drift = abs(remaining - target_rating / rating_per_percent)
    if drift > 0.2:
        raise SystemExit(
            f"extract_constraints.py: {spec['id']} has a {cap} cap of "
            f"{cap_rating:g} rating less {talent_percent}% talent and "
            f"{buff_percent}% buff, which leaves {remaining:.2f}%, but its "
            f"net target of {target_rating:g} rating is "
            f"{target_rating / rating_per_percent:.2f}%. Reconcile them in {HIT}."
        )
    # A credited talent is a row. A talent that credits nothing is a reason, and
    # a reason is a sentence, so it goes below the block rather than into it.
    talent = spec.get("talent") or {}
    if talent.get("percent"):
        out.append(row(talent["name"], f"-{trim(talent['percent'])}%"))
    for one in extra:
        if one.get("percent"):
            out.append(row(one["name"], f"-{trim(one['percent'])}%"))
    if buff_percent:
        out.append(row(spec["group_buff_name"], f"-{trim(buff_percent)}%"))

    debuff, debuff_name = assumed_rating(hit, cap)
    if debuff:
        out.append(row(debuff_name, f"-{percent(debuff, rating_per_percent)}",
                       "assumed"))

    # WHAT GEAR MUST FIND, NET OF EVERYTHING ABOVE IT. This is the one figure a
    # council member acts on, so it closes the block.
    out.append(row("Gear needs",
                   percent(max(target_rating - debuff, 0.0),
                           rating_per_percent)))

    if not talent_percent:
        out.append(upper_first(talent_clause(spec, cap_percent)) + ".")

    # WHERE A CAPTURE EXISTS IT IS THE ONLY SUPPLY FIGURE THE CARD SHOWS. The
    # workbook rule gears greedily by a column that already prices hit, so it
    # returns an upper bound rather than a wardrobe, and its tier figure swaps
    # in five Tier 6 pieces that no spec can reach in this window. Printing
    # both put two different entry percentages on one card, which reads as a
    # contradiction rather than as two questions. The workbook figures stay in
    # hit.yaml, where the difference between the two rules is explained.
    if captured:
        return out

    out.append(BREAK)
    out.append(row("Walking in, before Phase 3", percent(entry, rating_per_percent),
                   margin_note(entry + debuff, target_rating,
                               rating_per_percent)))
    if tier != entry:
        out.append(row("Tier pieces", percent(tier, rating_per_percent),
                       margin_note(tier + debuff, target_rating,
                                   rating_per_percent)))
    return out


def captured_sentences(captured: dict, cap: str, rating_per_percent: float,
                       target_rating: float, debuff: float) -> list[str]:
    """What a real four-to-six-week set carries, which is a different question.

    THE SENTENCES ABOVE MEASURE A CONTROLLED SWAP and these measure a wardrobe.
    The rule above holds every non-tier slot still so the movement is
    attributable to the tier set; it is retired as a description of what a spec
    wears, because it puts five Tier 6 pieces on a character who can reach two.

    TWO TIER FIGURES, NOT ONE, because the head token sits behind Archimonde,
    which progression.yaml records as the tier's first wall and as a FORECAST
    rather than an observation. The sentences say so.

    A `short` HERE IS SHORT ON ITEMS. Gems and enchants are excluded from every
    figure. GEMS ARE CREDITED BEFORE ENCHANTS, ruled by the guild lead on
    10 August 2026: the throughput enchant a hit enchant would displace is
    worth more than the throughput gem a hit gem displaces, so the socket is
    the cheaper thing to give up and this guild does not take hit enchants.
    A gem only helps where there is a socket for it, so the count is capped at
    the sockets the set actually carries. What a shortfall means for routing loot is the
    council's call and is NOT stated here.
    """
    if not captured:
        return []
    # ONLY THE PROTECTION PALADIN RECORDS TWO KINDS OF HIT. A pure caster's
    # capture puts its spell hit in `item_hit`, because that is the one hit its
    # cap names, so keying on the cap alone blanked every caster card.
    entry_block = captured.get("entry") or {}
    two_kinds = "item_spell_hit" in entry_block
    spell = cap == "spell" and two_kinds
    field = "item_spell_hit" if spell else "item_hit"
    gap_key = "spell_gap_after_enchants" if spell else "gap_after_enchants"
    gem_key = "spell_gems_after_enchants" if spell else "gems_after_enchants"

    out: list[str] = []
    # WHERE THE TALENT AND THE ASSUMED DEBUFF COVER THE CAP OUTRIGHT, the
    # margin arithmetic returns the whole supply as the margin and the card
    # reads "carries 11.9%, which is about 11.9% over", which looks like a bug
    # and buries the actual finding. The Enhancement Shaman is the one spec
    # where this happens: its 48 rating target is exactly what Improved Faerie
    # Fire supplies.
    covered = target_rating - debuff <= 0

    # A break, so the supply block reads apart from the requirement block.
    out.append(BREAK)

    entry = entry_block
    if entry and field in entry:
        # NOT "a Tier 5 set". Six specs hold two or fewer tier pieces at this
        # anchor and the Feral Cat holds none, so naming the tier described
        # gear those specs do not wear.
        out.append(
            row("Walking in, before Phase 3", percent(entry[field], rating_per_percent),
                margin_note(entry[field] + debuff, target_rating,
                            rating_per_percent)))

    # APPENDED, NEVER RETURNED EARLY. Returning here dropped the entry figure,
    # both tier figures, the forecast and the contested-token caveat from the
    # one spec it fires on, which silently reduced the six caveated specs to
    # five.
    if covered:
        out.append("Talent and the assumed raid debuff cover this cap "
                   "outright, so every point of hit on an item is surplus.")

    contested = captured.get("token_configuration_contested")
    # AN ANCHOR NAMES A STATE OF THE RAID, NOT A PIECE OF GEAR, and the labels
    # hid that. "Entry", "Tier hands" and "Tier hands and head" meant nothing to
    # a reader who had not read progression.yaml, and the guild lead asked on
    # 13 August 2026 what they were. They are the three points a council
    # actually reasons from: before the phase opens, after Azgalor drops the
    # hands token, and after Archimonde drops the head token. The boss is what a
    # reader recognises, so the boss is named.
    for key, label in (("tier_hands_only", "After Azgalor, hands token"),
                       ("tier_hands_and_head",
                        "After Archimonde, hands and head")):
        block = captured.get(key) or {}
        if not block or field not in block:
            continue
        # BUILT FROM WHAT THE SET HOLDS, NOT FROM THE ANCHOR NAME. The Arcane
        # Mage declines the head token at this anchor, and the card used to say
        # it was wearing one.
        held = block.get("tier6_pieces_held") or []
        if key == "tier_hands_and_head" and "head" not in held:
            label = "After Azgalor, keeps Tier 5 helm"
        out.append(row(label, percent(block[field], rating_per_percent),
                       margin_note(block[field] + debuff, target_rating,
                                   rating_per_percent)))

        # GEMS FIRST, THEN ENCHANTS. Ruled by the guild lead on 10 August 2026
        # and it reverses what this said. The throughput enchant a hit enchant
        # displaces is worth more than the throughput gem a hit gem displaces,
        # so the cheaper thing to give up is the socket. This guild does not
        # take hit enchants.
        needed = block.get("gems_needed") or 0
        after_gems = block.get("gap_after_gems")
        sockets = block.get("gem_sockets") or 0
        state_key = "spell_state" if spell else "state"
        if needed and not after_gems:
            gem = "gem" if needed == 1 else "gems"
            out.append(f"Closed by {needed} hit {gem} against {sockets} "
                       "sockets in the set.")
        elif needed and after_gems:
            out.append(
                f"{needed} hit gems fill every socket the set has and "
                f"{percent(after_gems, rating_per_percent)} still remains, so "
                "gems alone do not close this.")

    if contested:
        out.append(f"Tier rows assume both reachable tokens. {upper_first(contested)}.")
    return out


def check_state(spec: dict, hit: dict, cap: str, target: float,
                entry: float, tier: float) -> None:
    """Fail where the arithmetic here disagrees with the state hit.yaml records.

    The two are written by different people at different times and either can be
    wrong. A card that says a spec is short beside a fact file that says it is
    full is the failure this catches, and it is not hypothetical: the
    hand-written cards claimed the Beast Mastery Hunter and the Retribution
    Paladin were short at Entry while hit.yaml recorded both as full, because
    the cards left out the assumed raid debuff.

    A tank paladin holds two caps and hit.yaml records one state, which is the
    melee one, so only that half is checked.
    """
    if cap == "spell" and spec.get("cap") == "melee_special_and_spell":
        return
    debuff, _ = assumed_rating(hit, cap)
    for anchor, supply, recorded in (
        ("Entry", entry, spec.get("state")),
        ("Tier", tier, spec.get("state_at_tier_anchor")),
    ):
        if recorded not in ("full", "short"):
            continue
        computed = "full" if supply + debuff >= target else "short"
        if computed != recorded:
            raise SystemExit(
                f"extract_constraints.py: {spec['id']} at the {anchor} anchor "
                f"supplies {supply:g} plus {debuff:g} assumed against a target "
                f"of {target:g}, which reads {computed}, but {HIT} records "
                f"{recorded}.\nOne of the two is wrong and no text is written "
                "from a figure that contradicts its own file."
            )


def sentences_for(spec: dict, haste_spec: dict, crit_spec: dict, hit: dict,
                  haste: dict, crit: dict, captured: dict) -> list[str]:
    caps = hit["raw_caps"]
    rates = hit["conversions"]
    melee = rates["melee_ranged_hit_rating_per_percent"]
    spell = rates["spell_hit_rating_per_percent"]

    out: list[str] = []
    held_notes: list[str] = []
    cap = spec.get("cap")
    if cap == "none":
        out.append("No hit cap applies to this spec.")
    else:
        # A tank paladin holds two caps at once, and they are different caps
        # with different denominators, so each is stated in full.
        pairs = []
        if cap == "melee_special_and_spell":
            pairs.append(("melee_special", melee, spec["raw_cap_rating"],
                          spec["net_target_rating"],
                          spec["supplied_at_p3_entry"],
                          spec["supplied_at_tier_anchor"]))
            pairs.append(("spell", spell, spec["raw_spell_cap_rating"],
                          spec["net_spell_target_rating"],
                          spec["supplied_spell_hit_at_p3_entry"],
                          spec["supplied_spell_hit_at_tier_anchor"]))
        else:
            per = spell if cap == "spell" else melee
            pairs.append((cap, per, spec["raw_cap_rating"],
                          spec["net_target_rating"],
                          spec["supplied_at_p3_entry"],
                          spec["supplied_at_tier_anchor"]))
        # A BREAK BETWEEN CAPS. The Protection Paladin is the one spec with
        # two, a melee threat floor and a spell one, and without this its
        # second requirement block ran straight on from the first set of
        # supply rows and read as one list.
        for index, (one, per, cap_rating, target, entry, tier) in \
                enumerate(pairs):
            if index:
                out.append(BREAK)
            check_state(spec, hit, one, target, entry, tier)
            mine = captured
            out.extend(cap_sentences(spec, hit, one, per, cap_rating, target,
                                     entry, tier, mine))
            # The captured set follows the controlled swap rather than
            # replacing it, so a reader sees both what the tier set alone does
            # and what a real wardrobe carries. The Paladin's spell half has no
            # capture of its own, so only the melee half takes these.
            if mine:
                debuff, _ = assumed_rating(hit, one)
                out.extend(captured_sentences(mine, one, per, target, debuff))

        if spec["id"] in hit["dual_wield_specs"]:
            white = caps["melee_white_dual_wield"]
            held_notes.append(
                f"Dual-wields: white swings miss until {white['percent']}%, "
                "which nothing in this patch reaches, so hit past the cap "
                "still buys accuracy.")

    # A break, so the mechanical notes read apart from the figures above them.
    tail = held_notes + crit_sentences(crit_spec, crit) \
        + haste_sentences(haste_spec, haste)
    if tail:
        out.append(BREAK)
        out.extend(tail)
    return out


def crit_sentences(crit_spec: dict, crit: dict) -> list[str]:
    """Where the spec sits against its crit cap, and what crit cannot reach.

    A tank's crit constraint is the one that runs the other way. It is not how
    much this spec crits, it is how much the boss crits it, and reaching crit
    immunity is what decides a tank's gear, so that sentence comes first.
    """
    if not crit_spec:
        return []
    out: list[str] = []
    thresholds = crit["tank_defensive_thresholds"]

    pointer = crit_spec.get("crit_immunity")
    if pointer:
        # The spec points at the threshold block rather than repeating it, so
        # the pointer is followed rather than the figures being copied here.
        key = str(pointer).rsplit(".", 1)[-1]
        block = thresholds.get(key)
        if not block:
            raise SystemExit(
                f"extract_constraints.py: {crit_spec['id']} points its crit "
                f"immunity at {pointer!r}, which crit.yaml does not hold under "
                "tank_defensive_thresholds.")
        out.append(
            "The constraint that decides this spec's gear is crit immunity, "
            f"which it reaches at {block['defense_skill_required']} defense "
            f"skill, or {block['defense_rating_required']} defense rating from "
            "gear.")
        talent = block.get("crit_reduction_talent")
        if isinstance(talent, dict):
            out.append(f"{talent['name']} supplies "
                       f"{talent['percent_at_max_rank']}% of that reduction, "
                       "which is why this spec's figure is lower than a plate "
                       "tank's.")
        # A talent supplying defense SKILL is a different mechanism from one
        # reducing crit taken, and the rating figure above assumes it is held.
        # An unstated assumption inside a threshold is how the 332 that this
        # block used to carry survived: it was the untalented figure and
        # nothing on the card said so.
        skill_talent = block.get("defense_skill_talent")
        if isinstance(skill_talent, dict):
            out.append(
                f"That rating figure assumes {skill_talent['name']} at "
                f"{skill_talent['ranks']} ranks, which supplies "
                f"{skill_talent['skill_at_max_rank']} defense skill. Without it "
                f"the requirement is "
                f"{block['defense_rating_required_untalented']} rating.")
        # Plate tanks with a shield hold all four avoidance entries and nobody
        # else does, per who_can_reach_it. A Bear can neither parry nor block.
        uncrushable = thresholds["uncrushable"]
        if key == "plate":
            out.append(
                "Pushing crushing blows off the attack table needs "
                f"{uncrushable['threshold_percent']}% of miss, dodge, parry "
                "and block on the character sheet.")
        else:
            out.append(
                "This spec cannot hold all four avoidance entries, so it "
                "cannot sustainably push crushing blows off the attack table.")

    cap = crit_spec.get("cap")
    white = crit_spec.get("white_cap_percent_at_special_hit_cap")
    if white:
        out.append(
            f"White swings stop critting at {white}%, measured at the "
            "special-attack hit cap.")
        # The qualitative finding, not the simulated percentages behind it.
        # Those are recorded as a single uncorroborated source, and a card is
        # the wrong place to lean on one. The finding itself is what a council
        # member needs: crit does not stop scaling this tier. The guard below
        # breaks the build if the fact file's finding ever changes.
        headline = crit["reachability_at_phase_3"]["headline"]
        if not headline.startswith("NO ROSTERED SPEC IS CRIT CAPPED"):
            raise SystemExit(
                "extract_constraints.py: crit.yaml no longer opens "
                "reachability_at_phase_3 with the finding this sentence was "
                f"written from. It now reads {headline[:60]!r}. Rewrite the "
                "sentence to match before regenerating.")
        out.append("Nothing rostered reaches it this phase, so crit stays "
                   "linear all tier.")
    elif str(cap).startswith("none"):
        # `none, two-roll resolution` is how the hunters are recorded: a ranged
        # attack rolls crit separately, so no cap exists to reach.
        out.append("No crit cap.")

    if crit_spec.get("cannot_crit") and \
            not str(crit_spec["cannot_crit"]).startswith("unverified"):
        out.append(
            "Part of this spec's damage is periodic, and periodic damage "
            "cannot crit in this patch, so crit reaches less of its output "
            "than the character sheet suggests.")
    return out


def haste_sentences(haste_spec: dict, haste: dict) -> list[str]:
    """The one haste threshold a spec has to protect, or the absence of one.

    `verified_threshold` names the threshold by id, and the threshold itself is
    recorded once in haste.yaml, so the figures are read from there rather than
    from the string on the spec.
    """
    named = (haste_spec or {}).get("verified_threshold")
    if not named or named == "none":
        return ["No haste threshold to protect."]
    for threshold in haste["thresholds"]["verified"]:
        if threshold["id"] in named:
            reach = ("" if threshold.get("reachable_from_phase_3_gear")
                     else ", which nothing rostered reaches from gear this "
                          "phase")
            return [f"Global cooldown floor at "
                    f"{threshold['threshold_percent']}% spell haste{reach}."]
    raise SystemExit(
        f"extract_constraints.py: a spec names the haste threshold {named!r}, "
        f"which {HASTE} does not record under thresholds.verified."
    )


def lua_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--hit", type=Path, default=HIT)
    ap.add_argument("--haste", type=Path, default=HASTE)
    ap.add_argument("--crit", type=Path, default=CRIT)
    ap.add_argument("--captured", type=Path, default=CAPTURED)
    ap.add_argument("--out", type=Path,
                    default=Path("theme/filters/constraints.generated.lua"))
    args = ap.parse_args()

    hit = yaml.safe_load(args.hit.read_text())
    haste = yaml.safe_load(args.haste.read_text())
    crit = yaml.safe_load(args.crit.read_text())
    # Absent on a first run before `just regen` has built it. An empty mapping
    # simply omits the captured sentences rather than failing the build.
    captured = (yaml.safe_load(args.captured.read_text())
                if args.captured.exists() else {})
    by_id = {spec["id"]: spec for spec in hit["specs"]}
    haste_by_id = {spec["id"]: spec for spec in haste["specs"]}
    crit_by_id = {spec["id"]: spec for spec in crit["specs"]}

    out = [HEADER, "return {"]
    for name in sorted(SPECS):
        spec_id = SPECS[name][1]
        spec = by_id.get(spec_id)
        if not spec:
            print(f"error: {name} is {spec_id}, which {args.hit} does not hold",
                  file=sys.stderr)
            return 1
        out.append(f"  [{lua_string(name.lower())}] = {{")
        for sentence in sentences_for(spec, haste_by_id.get(spec_id),
                                      crit_by_id.get(spec_id), hit, haste, crit,
                                      (captured.get('specs') or {}).get(spec_id) or {}):
            out.append(f"    {lua_string(sentence)},")
        out.append("  },")
    out.append("}")

    args.out.write_text("\n".join(out) + "\n")
    print(f"{len(SPECS)} spec(s) -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
