#!/usr/bin/env python3
"""Lift each spec's best-in-slot item ids into a table Lua can read.

THE TWO-LEVEL STANDING, ruled by the guild lead on 20 August 2026: the
compendium replaces the four-step priority scale with BIS and Upgrade. An
item is BIS for a spec where the spec's best-in-slot simulated profile
WEARS it, and an Upgrade where the spec is a claimant on the item without
wearing it there. Both halves are derived, neither is judged per item, and
the council's allocation record in data/judgments/priorities.yaml is
untouched by this file: who receives a contested item FIRST is still a
judgment no derivation answers.

WHY THE PROFILE AND NOT THE WORKBOOK. The best-in-slot profiles carry every
ruling the compendium has made, the weapon and trinket routing, the hunter
two-handers, the crafted exclusions, and every revision the enumerated
rounds measured, so the label inherits the project's whole judgment and
measurement history. A workbook rank inherits none of it.

A SPEC WITHOUT A SIMULATED SET LABELS NOTHING BIS. The tanks, the healers
and the Feral Cat have no best-in-slot profile, so every claim those specs
hold renders as an Upgrade, and docs/conventions.md states that limit in
its own words rather than leaving it to be discovered.

Usage:
    python3 tools/extract_bis_sets.py --out theme/filters/bis.generated.lua
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_ladder import SPECS  # noqa: E402

CAPTURES = Path("data/facts/sim-profiles/bis-capture")

# The display name each capture's snake_case spec key renders as, inverted
# from the ladder registry so the two can never disagree on spelling.
DISPLAY = {key: name for name, (_tab, key) in SPECS.items()}


def bis_ids(doc: dict) -> set[int]:
    """Every item id the best-in-slot anchor wears."""
    slots = ((doc.get("anchors") or {}).get("bis") or {}).get("hit_by_slot") or {}
    return {int(row["id"]) for row in slots.values()
            if isinstance(row, dict) and row.get("id")}


def lua_table(sets: dict[str, set[int]]) -> str:
    out = ["-- GENERATED BY tools/extract_bis_sets.py. DO NOT EDIT.",
           "-- Every id below is read from data/facts/sim-profiles/bis-capture,",
           "-- which just regen rebuilds; to change a set, change a capture or",
           "-- a ruling, never this file.",
           "return {"]
    for spec in sorted(sets):
        out.append(f'  ["{spec}"] = {{')
        for item_id in sorted(sets[spec]):
            out.append(f"    [{item_id}] = true,")
        out.append("  },")
    out.append("}")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--captures", type=Path, default=CAPTURES)
    ap.add_argument("--out", type=Path,
                    default=Path("theme/filters/bis.generated.lua"))
    args = ap.parse_args()

    sets: dict[str, set[int]] = {}
    for path in sorted(args.captures.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text())
        key = doc.get("spec") or path.stem.replace("-", "_")
        name = DISPLAY.get(key)
        if name is None:
            print(f"error: {path} names the spec {key!r}, which the ladder "
                  "registry does not know.", file=sys.stderr)
            return 1
        ids = bis_ids(doc)
        if not ids:
            print(f"error: {path} carries no best-in-slot anchor, so it can "
                  "label nothing.", file=sys.stderr)
            return 1
        sets[name] = ids

    args.out.write_text(lua_table(sets))
    total = sum(len(v) for v in sets.values())
    print(f"{len(sets)} spec(s), {total} BIS id(s) -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
