#!/usr/bin/env python3
"""Write the council's judgments as a Lua table the card renderer can read.

The priority, the case for and the case against used to sit inline in the document,
once per card. They are the one thing on a card that no fact file can supply, so
they are kept, but they are kept in one place and rendered rather than typed
into whichever page happened to need them.

Keyed by item id and spec id together, which is the primary key of a judgment:
the same item is prioritized differently for every claimant, and that is the whole
point of the exercise.

Usage:
    python3 tools/extract_judgments.py --out theme/filters/judgments.generated.lua
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_ladder import SPECS  # noqa: E402

SOURCE = Path("data/judgments/priorities.yaml")

HEADER = """-- GENERATED BY tools/extract_judgments.py. DO NOT EDIT.
--
-- What the council concluded, keyed by item id and the spec name the cards use.
-- Written from data/judgments/priorities.yaml; change that file and run `just regen`.
--
-- Nothing here is a fact. Every figure a card prints comes from data/facts, and
-- the cap position on a card is generated separately. This is the judgment."""

# The spec id each card name resolves to, inverted from the one registry that
# writes the mapping out rather than inferring it.
SPEC_ID_TO_NAME = {spec_id: name for name, (_, spec_id) in SPECS.items()}


def lua_string(text: str) -> str:
    return '"' + " ".join(str(text).split()).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", type=Path, default=SOURCE)
    ap.add_argument("--out", type=Path,
                    default=Path("theme/filters/judgments.generated.lua"))
    args = ap.parse_args()

    doc = yaml.safe_load(args.source.read_text())
    entries = doc.get("entries") or []

    seen: set[tuple[str, str]] = set()
    rows: list[tuple[str, str, dict]] = []
    for entry in entries:
        item_id = str(entry.get("item_id", "")).strip()
        spec_id = str(entry.get("spec", "")).strip()
        if not item_id or not spec_id:
            print(f"error: an entry names item {item_id!r} and spec {spec_id!r};"
                  " both are required", file=sys.stderr)
            return 1
        name = SPEC_ID_TO_NAME.get(spec_id)
        if not name:
            print(f"error: {spec_id} is not a spec any card can name. Known: "
                  + ", ".join(sorted(SPEC_ID_TO_NAME)), file=sys.stderr)
            return 1
        # One judgment per item per spec. Two would mean the file disagrees with
        # itself and the renderer would silently show whichever came last.
        key = (item_id, spec_id)
        if key in seen:
            print(f"error: {args.source} holds two judgments for item {item_id} "
                  f"and {spec_id}", file=sys.stderr)
            return 1
        seen.add(key)
        rows.append((item_id, name.lower(), entry))

    out = [HEADER, "return {"]
    for item_id, name, entry in sorted(rows):
        out.append(f"  [{lua_string(item_id + '|' + name)}] = {{")
        out.append(f"    priority = {lua_string(entry.get('priority', ''))},")
        for field in ("unit",):
            if entry.get(field):
                out.append(f"    [{lua_string(field)}] = "
                           f"{lua_string(entry[field])},")
        # An entry nobody has decided is marked, so the card can say so rather
        # than presenting an example as a ruling.
        decided = entry.get("status") == "decided"
        out.append(f"    decided = {'true' if decided else 'false'},")
        out.append("  },")
    out.append("}")

    args.out.write_text("\n".join(out) + "\n")
    decided = sum(1 for e in entries if e.get("status") == "decided")
    print(f"{len(entries)} judgment(s), {decided} decided -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
