#!/usr/bin/env python3
"""Write field commentary as a Lua table the commentary filter can read.

Lua cannot read YAML, so the fact files are projected here at `just regen` time
and `theme/filters/commentary.lua` reads the result. Nothing is written by hand.

TWO SOURCES, ONE OF THEM CURATED. `data/facts/creator-stances.yaml` holds every
remark the transcript pass produced. `data/facts/field-commentary.yaml` holds the
handful that carry an editorial note, matched to a remark by item, creator and
timestamp, so the note travels with it. The claim text comes from the stance file
in both cases, because a second copy of a claim is the copy that goes stale.

FIVE REMARKS PER ITEM, AND DISAGREEMENT SURVIVES THE CUT. Some items draw
forty-five remarks and a page cannot show them all. Selection therefore seeds ONE
remark from every stance present, strongest reach first, BEFORE it fills the
remaining slots by reach. A single creator arguing against an item that eight
others like stays on the page, because that lone objection is the thing a
council most needs to see and is exactly what a straight top-five by views would
delete. Where an item carries both a favours and an against remark, the item is
marked as disagreed so the page can say so.

REACH ORDERS. IT DOES NOT JUDGE. See tools/fetch_reach.py.

The generated file is not a fact. It states nothing the fact file does not, and
a second copy of a fact inside `data/facts/` is the copy that goes stale, so it
lives beside the filter that consumes it and `just check` fails if it drifts.

Usage:
    python3 tools/extract_commentary.py --out theme/filters/commentary.generated.lua
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

SOURCE = Path("data/facts/field-commentary.yaml")
STANCES = Path("data/facts/creator-stances.yaml")
REACH = Path("data/facts/creator-reach.yaml")

# How many remarks one item page shows.
PER_ITEM = 5
# A remark naming the item with no view attached is shown only if nothing else
# is available for that item.
LAST_RESORT = "mentions_only"

HEADER = """-- GENERATED BY tools/extract_commentary.py. DO NOT EDIT.
--
-- What creators have said about an item, keyed by item id. Written from
-- data/facts/field-commentary.yaml; change that file and run `just regen`.
--
-- An entry is a paraphrase in our words, not a transcript quote, with the
-- timestamp that makes it checkable against the recording.
--
-- A field source explains a mechanism and nominates an item for a closer look.
-- It never moves a number, per the framework, so nothing here is rendered as a
-- figure or beside one."""


def lua_string(text: str) -> str:
    return '"' + str(text).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def tidy(text: str) -> str:
    return " ".join(str(text).split())


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", type=Path, default=SOURCE)
    ap.add_argument("--out", type=Path,
                    default=Path("theme/filters/commentary.generated.lua"))
    args = ap.parse_args()

    if not args.source.exists():
        print(f"error: {args.source} not found", file=sys.stderr)
        return 2

    doc = yaml.safe_load(args.source.read_text())
    notes = {}
    for entry in doc.get("entries") or []:
        key = (str(entry.get("item_id")), str(entry.get("creator")),
               str(entry.get("timestamp")))
        notes[key] = entry

    stances = list(yaml.safe_load(STANCES.read_text())["remarks"])

    # A CURATED ENTRY WITH NO REMARK BEHIND IT STILL BELONGS ON THE PAGE.
    # fc-006, Merciless Gladiator's Maul, was read by hand because the item is
    # Arena Season 3 gear and sat outside the Phase 3 drop table the stance pass
    # ran over. It matched nothing, so it rendered nowhere, which made the one
    # entry that needed a human the only entry a reader could not see.
    seconds = {}
    for entry in doc.get("entries") or []:
        stamp_text = str(entry.get("timestamp") or "0:00")
        minutes, _, secs = stamp_text.partition(":")
        try:
            seconds[entry["id"]] = int(minutes) * 60 + int(secs or 0)
        except ValueError:
            seconds[entry["id"]] = 0
    known = {(str(r["item_id"]), r["creator"], r["timestamp"]) for r in stances}
    for entry in doc.get("entries") or []:
        key = (str(entry.get("item_id")), str(entry.get("creator")),
               seconds[entry["id"]])
        if key in known:
            continue
        stances.append({
            "item_id": entry["item_id"], "item_name": entry.get("item_name"),
            "creator": entry["creator"], "slug": "", "timestamp": key[2],
            "stance": entry.get("stance") or "conditional",
            "claim": entry.get("claim") or "", "specs": entry.get("scope") or [],
            "confidence": "high", "url": entry.get("url") or "",
        })
    reach = {}
    if REACH.exists():
        for row in yaml.safe_load(REACH.read_text())["recordings"]:
            reach[row["slug"]] = row.get("views") or 0

    by_item: dict[str, list[dict]] = {}
    for remark in stances:
        by_item.setdefault(str(remark["item_id"]), []).append(remark)

    def specs_of(remark: dict) -> set:
        return {re.sub(r"[^a-z]", "", s.lower()) for s in (remark.get("specs") or [])}

    def disagrees(remarks: list[dict]) -> bool:
        """True only where two DIFFERENT creators contradict each other ABOUT
        THE SAME SPEC.

        A looser test, favours and against both present anywhere on the item,
        called 22 items disputed and 12 of those were nothing of the kind. It
        paired a creator recommending Blade of Infamy to hunters against one
        rating it below Talon of Azshara for ROGUES, which are not in conflict
        and can both be true. It also let one creator arguing a nuanced case
        across a long video appear to argue with themselves.
        """
        for yes in (r for r in remarks if r["stance"] == "favours"):
            for no in (r for r in remarks if r["stance"] == "against"):
                if yes["creator"] == no["creator"]:
                    continue
                a, b = specs_of(yes), specs_of(no)
                if not a or not b or (a & b):
                    return True
        return False

    def is_curated(remark: dict) -> bool:
        return (str(remark["item_id"]), str(remark["creator"]),
                stamp(remark["timestamp"])) in notes

    def stamp(seconds: int) -> str:
        return f"{seconds // 60}:{seconds % 60:02d}"

    def choose(remarks: list[dict]) -> list[dict]:
        """Up to PER_ITEM remarks, with every stance represented first.

        Seeding by stance before filling by reach is what stops a lone
        dissenter being crowded out by five creators who agree with each other.
        """
        ranked = sorted(remarks, key=lambda r: -reach.get(r["slug"], 0))
        speaking = [r for r in ranked if r["stance"] != LAST_RESORT]
        pool = speaking or ranked

        # WHERE AN ITEM IS CURATED, THE CURATED SET IS THE WHOLE SET. Curation
        # exists to say "show these", and it was doing nothing twice over. First
        # the note attached only where the remark also won a place on reach, so
        # four of seven curated entries rendered nowhere. Then, once they were
        # pinned, reach filled the remaining slots and put back the very remarks
        # the curation had excluded: the Warglaive page was designed as one
        # quantified voice per class plus a creator declining to rule, and reach
        # added a second rogue remark and a warrior aside, which is the bias the
        # guild lead asked to avoid on that line.
        #
        # An item nobody has curated still selects on stance and reach, which is
        # every item but the thirteen.
        pinned = [r for r in pool if is_curated(r)]
        if pinned:
            pinned.sort(key=lambda r: -reach.get(r["slug"], 0))
            return pinned[:PER_ITEM]

        # Seed one remark per stance. Within a stance, prefer a creator who is
        # not on the page yet: Sarthe holds both a conditional and a favours
        # view of Cursed Vision and would otherwise take two of the five slots
        # while eight other creators went unheard.
        picked, seen = list(pinned), {r["creator"] for r in pinned}
        for stance in sorted({r["stance"] for r in pool}):
            if any(r["stance"] == stance for r in picked):
                continue
            same = [r for r in pool if r["stance"] == stance]
            fresh = [r for r in same if r["creator"] not in seen]
            choice = (fresh or same)[0]
            seen.add(choice["creator"])
            picked.append(choice)
        # Then the widest reach, but a creator already on the page does not take
        # a second slot while another creator is still unheard.
        for remark in pool:
            if len(picked) >= PER_ITEM:
                break
            if remark not in picked and remark["creator"] not in seen:
                seen.add(remark["creator"])
                picked.append(remark)
        for remark in pool:
            if len(picked) >= PER_ITEM:
                break
            if remark not in picked:
                picked.append(remark)
        picked.sort(key=lambda r: -reach.get(r["slug"], 0))
        return picked[:PER_ITEM]

    out = [HEADER, "return {"]
    shown = 0
    for item_id in sorted(by_item, key=int):
        remarks = by_item[item_id]
        chosen = choose(remarks)
        shown += len(chosen)
        disagreed = disagrees(remarks)
        out.append(f"  [{lua_string(item_id)}] = {{")
        out.append(f"    disagreed = {'true' if disagreed else 'false'},")
        out.append(f"    total = {len(remarks)},")
        out.append("    remarks = {")
        for remark in chosen:
            key = (item_id, str(remark["creator"]), stamp(remark["timestamp"]))
            note = notes.get(key, {})
            out.append("      {")
            out.append(f"        creator = {lua_string(tidy(remark['creator']))},")
            out.append(f"        channel = {lua_string(tidy(remark['creator']))},")
            out.append(f"        url = {lua_string(tidy(remark['url']))},")
            out.append(f"        timestamp = {lua_string(stamp(remark['timestamp']))},")
            out.append(f"        claim = {lua_string(tidy(remark['claim']))},")
            out.append(f"        stance = {lua_string(tidy(remark['stance']))},")
            out.append(f"        views = {reach.get(remark['slug'], 0)},")
            out.append("        captured = true,")
            scope = remark.get("specs") or []
            out.append("        scope = { "
                       + ", ".join(lua_string(s) for s in scope) + " },")
            # A PUBLISHED NOTE IS WRITTEN TO A READER, NOT TO US. Four notes
            # opened by comparing what a placeholder predicted against what the
            # capture returned, or by explaining that the stance labels hide the
            # axis of a conflict. That is this project talking to itself, and it
            # printed on a card under a creator's name. The guild lead read one
            # on the published site on 13 August 2026 and asked what it was.
            #
            # The material is not lost: those entries now carry a `record` field
            # for the authoring detail, which nothing publishes. This refuses to
            # publish a note that still speaks in the vocabulary of the process.
            leaked = [w for w in ("placeholder", "agent pass",
                                  "AXIS OF THE CONFLICT", "stance labels hide")
                      if w.lower() in (note.get("note") or "").lower()]
            if leaked:
                raise SystemExit(
                    f"extract_commentary.py: the note on {key[0]} speaks about "
                    f"how this project works, not about the item: {leaked}.\n"
                    "  A published note is written to a reader. Move the "
                    "authoring detail to a `record:` field, which is not "
                    "published, and leave the note saying what the remark "
                    "means.")
            if note.get("note"):
                out.append(f"        note = {lua_string(tidy(note['note']))},")
            if note.get("conflicts_with"):
                out.append(
                    f"        conflicts_with = {lua_string(note['conflicts_with'])},")
            out.append("      },")
        out.append("    },")
        out.append("  },")
    out.append("}")

    args.out.write_text("\n".join(out) + "\n")
    disputed = sum(1 for rs in by_item.values() if disagrees(rs))
    print(f"{len(stances)} remark(s) across {len(by_item)} item(s); "
          f"{shown} shown at up to {PER_ITEM} per item; "
          f"{disputed} item(s) carry disagreement -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
