#!/usr/bin/env python3
"""Lift the measured slot ladders into a table Lua can read.

The derived-orderings ruling, data/judgments/derived-orderings.yaml, lets an
item page sort a slot's candidates by simulated delta and read a denial cost
as this item minus the next best available. The measurements live in
data/facts/ladder-sims.yaml, one figure per candidate per slot per spec, as
variants of the tier profile; this tool is the bridge that puts them where
the page filters can reach them at build time, the extract_bis_sets pattern.

Alongside each spec's ladders it carries the spec's three anchor figures at
the default boss armor, read from data/facts/sim-figures.yaml, so a card can
print the spread an item moves inside without a second lookup, and the
standing set from the best-in-slot capture so a summary can say whether a
candidate is where the spec ends up or a step on the way.

Writes theme/filters/measured.generated.lua. Runs inside `just regen`;
`just check` regenerates and diffs.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_bis_sets import DISPLAY  # noqa: E402

LADDERS = Path("data/facts/ladder-sims.yaml")
FIGURES = Path("data/facts/sim-figures.yaml")
CONTEXT = Path("data/judgments/sim-context.yaml")
OUT = Path("theme/filters/measured.generated.lua")

# The default boss armor every published reading uses, per the guild lead's
# ruling in data/judgments/sim-context.yaml. Asserted against sim-figures
# rather than restated as a bare number.
DEFAULT_ARMOR = 7684

ANCHOR_KEYS = {"entry": "entry", "tier-hands-and-head": "tier", "bis": "bis"}


def lua_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    if not LADDERS.is_file():
        # The ladder round has not run yet; write an empty table rather than
        # failing regen, the same posture as an empty shortlist.
        OUT.write_text(
            "-- GENERATED BY tools/extract_measured_ladders.py. DO NOT "
            "EDIT.\n-- No ladder round has run; run `just sim-ladders`.\n"
            "return {}\n")
        print(f"0 spec(s) -> {OUT}")
        return 0

    doc = yaml.safe_load(LADDERS.read_text())
    figures = yaml.safe_load(FIGURES.read_text())["results"]
    anchors: dict[str, dict[str, float]] = {}
    for row in figures:
        if row.get("boss_armor") != DEFAULT_ARMOR:
            continue
        key = ANCHOR_KEYS.get(row["anchor"])
        if key:
            anchors.setdefault(row["spec"], {})[key] = row["dps"]

    out = [
        "-- GENERATED BY tools/extract_measured_ladders.py. DO NOT EDIT.",
        "--",
        "-- The measured slot ladders behind the item pages' derived",
        "-- orderings: each single-item slot's candidates priced as variants",
        "-- of the spec's tier profile at boss armor "
        f"{doc['meta']['boss_armor']}, the worn item",
        "-- reproducing the tier figure in sim-figures.yaml. Rows are sorted",
        "-- best first and `worn` marks the tier profile's own item. The",
        "-- `anchors` block is the spec's entry, tier and best-in-slot",
        "-- figures at the same armor, for the spread a card prints.",
        "-- Rebuilt by `just regen` from data/facts/ladder-sims.yaml, which",
        "-- only `just sim` and `just sim-ladders` refresh.",
        "return {",
    ]
    count = 0
    for spec in sorted(doc.get("specs") or {}):
        block = doc["specs"][spec]
        display = DISPLAY.get(spec, spec)
        out.append(f"  [{lua_string(display)}] = {{")
        spread = anchors.get(spec) or {}
        out.append("    anchors = {")
        for key in ("entry", "tier", "bis"):
            if key in spread:
                out.append(f"      {key} = {spread[key]},")
        out.append("    },")
        out.append("    slots = {")
        for slot in sorted(block.get("slots") or {}):
            rows = block["slots"][slot]
            out.append(f"      {slot} = {{")
            for row in rows:
                worn = ", worn = true" if row.get("worn") else ""
                out.append(
                    f"        {{ name = {lua_string(row['item'])}, "
                    f"id = {row['id']}, dps = {row['dps']}, "
                    f"se = {row['standard_error']}{worn} }},")
            out.append("      },")
        out.append("    },")
        out.append("  },")
        count += 1
    out.append("}")
    OUT.write_text("\n".join(out) + "\n")
    print(f"{count} spec(s) -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
