#!/usr/bin/env python3
"""Write the items a class can wear that no workbook tab ranks, per spec.

THE GAP THIS FILLS. A spec page reads down `ladder.generated.lua`, which is the
workbook's own rankings. The workbook ranks by EP, so it holds no relic section
at all: a relic carries no stats, and there is nothing to score. It also ranks
only what its author listed, so seven of the nine Ashtongue Deathsworn trinkets
appear on no tab. The result, found on 13 August 2026, was that fourteen relics
and seven class-locked trinkets existed in `items.csv` and were reachable from
nowhere in the compendium. Correct data that nothing displays is not a fact the
council has.

NOTHING HERE IS RANKED, AND THAT IS THE POINT. This file emits a set, in name
order, with no rank and no score. A relic cannot be ranked against another relic
without a simulation this project has not run, and inventing an order would be
the compendium making a decision on the council's behalf. The section says what
a class can wear and leaves the choosing where it belongs.

WHAT IS IN SCOPE. Two kinds, both defined by the item table rather than by a
list kept here:

  - A RELIC, meaning an item in the Ranged slot with no weapon damage whose
    relic type names an owning class. Idols are Druid, librams are Paladin,
    totems are Shaman.
  - A CLASS-LOCKED TRINKET, meaning a trinket whose `class_allowlist` names
    exactly one class.

DUPLICATION IS RESOLVED AT RENDER TIME, not here. Nine of the class-locked
trinkets are Tier 5 raid drops the workbook does rank, so they already have a
ranked row on the specs that want them. `shortlist.lua` drops any item it has
already shown, so this file can emit the whole set without having to model what
the ladder chose.

Usage:
    python3 tools/extract_unranked.py --out theme/filters/unranked.generated.lua
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_ladder import SPECS  # noqa: E402
from generate_item_pages import RELIC_TYPE_TO_CLASS, spec_class  # noqa: E402

ITEMS = Path("data/facts/items.csv")
DROPS = Path("data/facts/drops.csv")

HEADER = """-- GENERATED BY tools/extract_unranked.py. DO NOT EDIT.
--
-- The items a class can wear that no workbook tab ranks: the relics, and the
-- trinkets locked to one class. Keyed by spec, in name order, with NO rank and
-- NO score, because neither exists for these and inventing one would decide
-- something the council decides.
--
-- `shortlist.lua` renders these under their own heading and skips any item it
-- has already shown in a ranked section."""


def lua_string(text: str) -> str:
    return '"' + str(text).replace("\\", "\\\\").replace('"', '\\"') + '"'


def where(row: dict, drops: dict[str, list[str]]) -> str:
    """Where the item comes from, in the words the shortlist already uses."""
    if row.get("source_note"):
        return row["source_note"]
    bosses = drops.get(row["item_id"]) or []
    return "; ".join(sorted(set(bosses)))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--items", type=Path, default=ITEMS)
    ap.add_argument("--drops", type=Path, default=DROPS)
    ap.add_argument("--out", type=Path,
                    default=Path("theme/filters/unranked.generated.lua"))
    args = ap.parse_args()

    items = list(csv.DictReader(args.items.open()))
    drops: dict[str, list[str]] = {}
    for row in csv.DictReader(args.drops.open()):
        drops.setdefault(row["item_id"], []).append(row["boss"])

    # class -> list of (kind, row), where kind is the heading the item sits
    # under. A relic and a trinket are different slots and are not mixed.
    owned: dict[str, list[tuple[str, dict]]] = {}
    for row in items:
        if (row["slot"] == "Ranged" and not row["weapon_min"]
                and RELIC_TYPE_TO_CLASS.get(row["ranged_weapon_type"])):
            owner = RELIC_TYPE_TO_CLASS[row["ranged_weapon_type"]]
            owned.setdefault(owner, []).append(("Relic", row))
        elif row["slot"] == "Trinket" and row["class_allowlist"]:
            names = row["class_allowlist"].split("|")
            if len(names) == 1:
                owned.setdefault(names[0].lower(), []).append(("Trinket", row))

    out = [HEADER, "return {"]
    specs = 0
    unplaced = [s for s in SPECS if spec_class(s) is None]
    if unplaced:
        # A spec with no class reads as a spec with no relic and no trinket,
        # which is the silence this file exists to end.
        print(f"error: no class for {', '.join(sorted(unplaced))}",
              file=sys.stderr)
        return 1

    for spec in sorted(SPECS):
        klass = spec_class(spec)
        entries = sorted(owned.get(klass, []), key=lambda e: (e[0], e[1]["name"]))
        if not entries:
            continue
        specs += 1
        out.append(f"  [{lua_string(spec)}] = {{")
        for kind, row in entries:
            out.append(
                "    { item_id = %s, name = %s, slot = %s, location = %s },"
                % (row["item_id"], lua_string(row["name"]), lua_string(kind),
                   lua_string(where(row, drops))))
        out.append("  },")
    out += ["}", ""]
    args.out.write_text("\n".join(out))

    total = sum(len(v) for v in owned.values())
    print(f"{total} unranked item(s) across {len(owned)} class(es), "
          f"{specs} spec(s) -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
