#!/usr/bin/env python3
"""Write the trinket each spec wears beside a contested one, as a Lua table.

WHY A TRINKET CARD NEEDS THIS. A player wears two trinkets and the worth of one
depends on what sits beside it. A card comparing a drop against a baseline in
the same slot answers half the question; naming the other slot answers the rest.

WHERE THE PAIR COMES FROM. The captures, at
`data/facts/sim-profiles/hit-capture/`, which record both trinket slots per spec
per anchor. This is a FACT about a captured set rather than a choice made here.

WHAT THE CAPTURES SAY, and it is why no single trinket was assumed. The guild
lead first proposed Dragonspine Trophy for every spec. It is worn by eight of
the seventeen captured specs and all eight are physical: the trinket carries 40
attack power and a melee haste proc, so a Shadow Priest or a Protection Warrior
would never hold it. Icon of the Silver Crescent is the caster counterpart, worn
by five of the six caster specs at every anchor, the exception being the
Destruction Warlock on Sextant of Unstable Currents and Quagmirran's Eye. Taking
the pair from each capture gets all three cases right without asserting any.

NO SECOND SOURCE EXISTS FOR THIS. Dragonspine Trophy, Icon of the Silver
Crescent and Quagmirran's Eye draw zero remarks in
`data/facts/creator-stances.yaml`, because all three are pre-Phase 3 items and
the commentary pass covered Phase 3 drops. So this rests on the captures alone.

Usage:
    python3 tools/extract_trinket_pairs.py --out theme/filters/trinkets.generated.lua
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import yaml

CAPTURES = Path("data/facts/sim-profiles/hit-capture")
ITEMS = Path("data/facts/items.csv")

HEADER = """-- GENERATED BY tools/extract_trinket_pairs.py. DO NOT EDIT.
--
-- The trinkets each spec wears, from the captured sets, so a trinket card can
-- name what would sit in the other slot. Keyed by spec id.
--
-- This is what a captured set HOLDS, not a recommendation. A card names it so a
-- reader weighing one trinket knows what it would be paired with."""


def lua_string(text: str) -> str:
    return '"' + str(text).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path,
                    default=Path("theme/filters/trinkets.generated.lua"))
    args = ap.parse_args()

    items = {r["item_id"]: r for r in csv.DictReader(ITEMS.open())}
    # The filter needs to know whether the item on the card is a trinket, and
    # specs.lua does not load the item database. Emitting the id set here keeps
    # it to one generated table rather than a second copy of itemdb, which this
    # project has already been bitten by: every filter that dofiles itemdb.lua
    # gets its OWN module table, and only items.lua sets the root it needs.
    trinket_ids = sorted(int(i) for i, r in items.items()
                         if r["slot"] == "Trinket")
    out = [HEADER, "return {", "  trinket_ids = {"]
    out += [f"    [{i}] = true," for i in trinket_ids]
    out += ["  },", "  pairs = {"]
    written = 0

    for path in sorted(CAPTURES.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text())
        spec = doc.get("spec") or path.stem.replace("-", "_")
        anchors = doc.get("anchors") or {}
        # The entry anchor is the set worn into the phase, which is the one a
        # council is reasoning about when a drop is on the table.
        block = anchors.get("entry") or next(iter(anchors.values()), {})
        slots = block.get("hit_by_slot") or {}
        worn = []
        for key in sorted(slots):
            if "trinket" not in key:
                continue
            entry = slots[key] or {}
            row = items.get(str(entry.get("id")))
            if row is None:
                continue
            worn.append((row["item_id"], row["name"]))
        if not worn:
            continue
        out.append(f"    [{lua_string(spec)}] = {{")
        for item_id, name in worn:
            out.append(f"      {{ id = {item_id}, name = {lua_string(name)} }},")
        out.append("    },")
        written += 1

    out.append("  },")
    out.append("}")
    args.out.write_text("\n".join(out) + "\n")
    print(f"{written} spec(s) with a captured trinket pair, "
          f"{len(trinket_ids)} trinket id(s) -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
