#!/usr/bin/env python3
"""Write the tier page: what breaking an old set bonus costs, per spec.

WHAT THIS ANSWERS. The guild lead ruled on 20 August 2026 that the tier page's
center of gravity is "we care about at what point it makes sense to break a
bonus". The page reads every figure from data/facts/tier-sims.yaml, which
tools/run_tier_sims.py writes, and computes the break-even reading from the
recorded subsets rather than storing a second copy of any figure. Set piece
counts per row are derived here from the same gear files and item database the
runner used, so the page and the fact file cannot disagree about which bonus a
row holds.

Usage:
    python3 tools/generate_tier_page.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_sim_pages import SPEC_LABEL, figure, rows_table, slug  # noqa: E402
from run_sims import SLOT_ORDER, WOWSIMS  # noqa: E402
from run_tier_sims import (  # noqa: E402
    TIER_ANCHOR, held_sets, pieces_after, with_slots,
)

TIER_SIMS = Path("data/facts/tier-sims.yaml")
GEAR = Path("data/sim/gear")
VERDICTS = Path("data/judgments/token-verdicts.yaml")

BANNER = ("<!-- GENERATED BY tools/generate_tier_page.py. DO NOT EDIT.\n"
          "     Every figure is read from data/facts/tier-sims.yaml and every\n"
          "     set from data/sim/gear. To change what it says, rerun the "
          "sims. -->")

# The specs this build of the simulator cannot measure, with the label a
# reader knows them by. The three tanks are out by the ruling of 14 August
# 2026, the Feral Cat because its preset is a stub in this build, and the
# four healers have no captured gear set.
UNMEASURED = [
    ("feral_bear", "Feral Bear"),
    ("feral_cat", "Feral Cat"),
    ("protection_paladin", "Protection Paladin"),
    ("protection_warrior", "Protection Warrior"),
    ("holy_paladin", "Holy Paladin"),
    ("priest_healer", "Priest Healer"),
    ("restoration_druid", "Restoration Druid"),
    ("restoration_shaman", "Restoration Shaman"),
]


def short_set(name: str) -> str:
    """The set name without its Armor/Regalia/Battlegear suffix, for a
    column heading that has to stay narrow."""
    for suffix in (" Armor", " Regalia", " Battlegear", " Raiment",
                   " Harness", " Vestments"):
        if name.endswith(suffix):
            return name[:-len(suffix)]
    return name


def bonus_word(count: int) -> str:
    """What a piece count keeps, as the cell a reader scans."""
    if count >= 4:
        return "2pc and 4pc"
    if count >= 2:
        return "2pc"
    return "none"


def break_even_reading(set_name: str, threshold: int, entry_pieces: int,
                       rows: list[dict], counts: dict) -> str:
    """The break-even for one bonus: the smallest replacement count at which the
    best subset that breaks it beats the best subset that keeps it.

    THE COMPARISON IS AT EQUAL COUNTS ON PURPOSE. Every replacement arrives
    ungemmed, so a row with more replacements carries more empty sockets;
    two subsets of the same size carry the same number, so at a fixed count
    the gap between the best breaker and the best keeper is the bonus
    question and not the gems.
    """
    label = f"{short_set(set_name)} {threshold}-piece"
    n = max((len(r["replaced"]) for r in rows), default=0)
    if not any(counts[id(r)].get(set_name, 0) < threshold for r in rows):
        return (f"No subset of these slots can break the {label}: the set "
                f"keeps enough pieces outside them, so the replacements never "
                f"poses that question.")
    for k in range(1, n + 1):
        at_k = [r for r in rows if len(r["replaced"]) == k]
        keep = [r for r in at_k if counts[id(r)].get(set_name, 0) >= threshold]
        brk = [r for r in at_k if counts[id(r)].get(set_name, 0) < threshold]
        if not brk:
            continue
        best_b = max(brk, key=lambda r: r["dps"])
        if not keep:
            return (f"The {label} cannot survive {k} replacement piece"
                    f"{'s' if k > 1 else ''} in these slots: every subset of "
                    f"that size breaks it, and the best of them, "
                    f"{', '.join(best_b['replaced'])}, measures "
                    f"{figure(best_b)}.")
        best_k = max(keep, key=lambda r: r["dps"])
        if best_b["dps"] > best_k["dps"]:
            return (f"Breaking the {label} first pays at {k} replacement piece"
                    f"{'s' if k > 1 else ''}: the best subset that breaks "
                    f"it, {', '.join(best_b['replaced'])}, measures "
                    f"{figure(best_b)}, against {figure(best_k)} for the "
                    f"best that keeps it, "
                    f"{', '.join(best_k['replaced'])}.")
    return (f"At no count inside this replacement set does the best subset that "
            f"breaks the {label} beat the best subset of the same size "
            f"that keeps it, so the bonus holds its price all the way to "
            f"the last of these slots.")


def greedy_order(rows: list[dict]) -> list[str]:
    """The best pickup order, read greedily off the subsets: at each step the
    added slot whose superset measures highest."""
    by_set = {frozenset(r["replaced"]): r for r in rows}
    slots = max((r["replaced"] for r in rows), key=len, default=[])
    taken: list[str] = []
    while len(taken) < len(slots):
        candidates = [(by_set[frozenset(taken + [s])]["dps"], s)
                      for s in slots if s not in taken
                      and frozenset(taken + [s]) in by_set]
        if not candidates:
            break
        taken.append(max(candidates)[1])
    return taken


def route_marginals(rows: list[dict]) -> dict[str, float]:
    """Each slot's increment along the greedy best pickup order.

    The single-piece column undervalues a piece that pays at a bonus
    threshold, so the give-out ranking uses the increment each slot adds at
    its step of the best order, which sums to the full-route total and
    credits a threshold piece where the threshold lands.
    """
    by_set = {frozenset(r["replaced"]): r for r in rows}
    order = greedy_order(rows)
    out: dict[str, float] = {}
    taken: list[str] = []
    for slot in order:
        before = by_set[frozenset(taken)]["dps"]
        taken.append(slot)
        out[slot] = round(by_set[frozenset(taken)]["dps"] - before, 1)
    return out


TOKEN_SLOT_LABEL = {"head": "Helm", "shoulder": "Shoulders", "chest": "Chest",
                    "hands": "Gloves", "legs": "Leggings"}


def token_order_sections(doc: dict, tokens: dict,
                         entry_dps: dict) -> list[str]:
    """One section per Tier 6 token: who gains what from it, best gain first.

    THE QUESTION AT THE LOOT TABLE, asked by the guild lead: a token drops,
    and the council wants the give-out order that maximizes what each item
    does. The ranking is the measured route increment per spec; a spec whose
    list does not take the token in that slot is named below the table
    rather than ranked, and the unmeasured claimants close each section.
    Nothing here is a ruling.
    """
    members = tokens["line_members_by_tier"][6]
    spec_to_set = tokens["spec_to_set"]
    set_pieces = {b["set_name"]: b["pieces"] for b in tokens["sets"]}
    t6_tokens = sorted((x for x in tokens["tokens"] if x.get("tier") == 6),
                       key=lambda x: (["head", "shoulder", "chest", "hands",
                                       "legs"].index(x["slot"]), x["name"]))

    def spec_class(label: str) -> str:
        lowered = label.lower()
        for name in ("warrior", "paladin", "hunter", "rogue", "priest",
                     "shaman", "mage", "warlock", "druid"):
            if name in lowered:
                return name.capitalize()
        return "Druid"

    # Every registry spec, measured or not, by class.
    from extract_ladder import SPECS as LADDER_SPECS
    by_class: dict[str, list[tuple[str, str]]] = {}
    for label, (_tab, key) in LADDER_SPECS.items():
        by_class.setdefault(spec_class(label), []).append((label, key))

    out = []
    for token in t6_tokens:
        classes = members[token["line"]]
        slot = token["slot"]
        ranked, unmeasured = [], []
        for cls in classes:
            for label, key in sorted(by_class.get(cls, [])):
                block = (doc["specs"] or {}).get(key)
                if block is None:
                    unmeasured.append(label)
                    continue
                t6 = block.get("tier_six") or {}
                pieces = t6.get("pieces") or {}
                rows = t6.get("rows") or []
                singles = block.get("token_singles") or {}
                set6 = (spec_to_set.get(key) or {}).get(6)
                token_piece = ((set_pieces.get(set6) or {}).get(slot)
                               or {})
                token_id = int(token_piece.get("item_id") or -1)
                worn = pieces.get(slot) or {}
                gain, note = None, ""
                if int(worn.get("id") or 0) == token_id and rows:
                    # The tier-six round measured this token as its single
                    # subset for the slot: the token is what the spec
                    # takes there.
                    by_set = {frozenset(r["replaced"]): r for r in rows}
                    if frozenset([slot]) in by_set:
                        gain = round(by_set[frozenset([slot])]["dps"]
                                     - by_set[frozenset()]["dps"], 1)
                    note = "BIS"
                elif slot in singles:
                    # The token-singles round measured it; the baseline is
                    # the spec's entry figure, which the empty subset
                    # reproduces to the digit.
                    base = entry_dps.get(key)
                    if base is not None:
                        gain = round(singles[slot]["dps"] - base, 1)
                    note = "Not BIS"
                ranked.append((gain, label,
                               token_piece.get("name", ""), note))
        ranked.sort(key=lambda r: (r[0] is None, -(r[0] or 0)))
        parts = [f"### {token['name']}", "",
                 f"Drops from {token['boss']}. Classes: "
                 f"{', '.join(classes)}.", ""]
        if ranked:
            parts += ["| Order | Spec | Gain | Buys | Standing |",
                      "|---|---|---|---|---|"]
            for i, (gain, label, piece, note) in enumerate(ranked, 1):
                cell = "not measured" if gain is None else f"{gain:+.1f}"
                parts.append(
                    f"| {i} | {label} | {cell} | {piece} | {note} |")
            parts.append("")
        if unmeasured:
            parts.append(
                "Unmeasured claimants, see the closing section: "
                + ", ".join(sorted(unmeasured)) + ".")
            parts.append("")
        out.append("\n".join(parts))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=Path("docs/tier.md"))
    args = ap.parse_args()

    if not TIER_SIMS.is_file():
        print(f"error: no figures at {TIER_SIMS}. Produce them with\n"
              "  python3 tools/run_tier_sims.py --iterations 10000\n"
              "A page written from no figures would render empty tables.",
              file=sys.stderr)
        return 1

    doc = yaml.safe_load(TIER_SIMS.read_text())
    meta = doc["meta"]
    db_items = {i["id"]: i for i in json.loads(
        (WOWSIMS / "assets/database/db.json").read_text()).get("items") or []}
    verdicts = (yaml.safe_load(VERDICTS.read_text()) or {}).get(
        "verdicts") or {}
    tokens = yaml.safe_load(Path("data/facts/tokens.yaml").read_text())
    figures = yaml.safe_load(Path("data/facts/sim-figures.yaml").read_text())
    default_tier = max({r.get("boss_armor", 0) for r in figures["results"]})
    entry_dps = {r["spec"]: r["dps"] for r in figures["results"]
                 if r["anchor"] == "entry"
                 and r.get("boss_armor") == default_tier}
    token_sections = token_order_sections(doc, tokens, entry_dps)

    sections = []
    for spec in sorted(doc["specs"], key=lambda s: SPEC_LABEL.get(s, s)):
        block = doc["specs"][spec]
        label = SPEC_LABEL.get(spec, spec)
        stem = spec.replace("_", "-")
        entry = json.loads((GEAR / f"{stem}.entry.gear.json").read_text())
        bis = json.loads((GEAR / f"{stem}.bis.gear.json").read_text())
        tier = json.loads(
            (GEAR / f"{stem}.{TIER_ANCHOR}.gear.json").read_text())

        parts = [f"## {label}\n"]

        ob = block.get("old_bonus") or {}
        rows = ob.get("rows") or []
        if not rows:
            parts.append(
                "The entry set holds no set at two or more pieces, so this "
                "spec walks into Phase 3 with no old bonus to break and the "
                "old-bonus round has nothing to measure.\n")
        else:
            held = ob["held_sets"]
            baseline = next(r for r in rows if not r["replaced"])
            parts.append(
                f"Walking in, this spec holds "
                f"{'; '.join(f'**{name}** at {info['pieces']} pieces, in the '
                             + ', '.join(info['slots']) + ' slots'
                             for name, info in held.items())}. "
                f"The bonuses that gear keeps live:\n")
            for text in ob.get("bonuses_held") or []:
                parts.append(f"> {text}\n")
            parts.append(
                f"The replacement pieces are what the best-in-slot set wears in "
                f"the {', '.join(ob['replaceable_slots'])} slots: "
                + ", ".join(f"{v['name']}"
                            for v in ob["replacements"].values())
                + f". The empty subset reproduces the "
                f"[entry figure](sims/{slug(spec, 'entry')}.md) of "
                f"{figure(baseline)}.\n")

            # Derive each row's piece counts from the same gear and database
            # the runner used, so the bonus column cannot drift from the
            # figures beside it.
            watched = sorted(held)
            counts = {id(r): pieces_after(
                with_slots(entry, bis, r["replaced"]), db_items, watched)
                for r in rows}

            for name in watched:
                p = held[name]["pieces"]
                for threshold in (t for t in (4, 2) if p >= t):
                    parts.append(break_even_reading(
                        name, threshold, p, rows, counts) + "\n")

            best = max(rows, key=lambda r: r["dps"])
            singles = [r for r in rows if len(r["replaced"]) == 1]
            if singles:
                first = max(singles, key=lambda r: r["dps"])
                parts.append(
                    f"The best first pickup is the "
                    f"**{first['replaced'][0]}**, at {figure(first)}, "
                    f"{first['dps'] - baseline['dps']:+.1f} against the "
                    f"entry set.\n")
            if best["dps"] <= baseline["dps"] and best is not baseline:
                parts.append(
                    "No subset in this round measures above the unbroken "
                    "entry set. Read that with the gem rule in mind: every "
                    "replacement arrives ungemmed, so these figures "
                    "understate a gemmed replacement, and the fully gemmed "
                    "destination is priced by the anchor figures instead.\n")
            elif best["replaced"]:
                parts.append(
                    f"The highest subset in the round is "
                    f"{', '.join(best['replaced'])}, at {figure(best)}, "
                    f"{best['dps'] - baseline['dps']:+.1f} against the "
                    f"entry set, before the gems those pieces would "
                    f"carry.\n")

            header = ["Replacement pieces", "Slots replaced"]
            header += [f"{short_set(n)} pieces" for n in watched]
            header += ["Old bonus", "DPS", "Against entry"]
            table = []
            for r in sorted(rows, key=lambda r: (len(r["replaced"]),
                                                 -r["dps"])):
                c = counts[id(r)]
                cells = [str(len(r["replaced"])),
                         ", ".join(r["replaced"]) or "*none, the entry set*"]
                cells += [str(c.get(n, 0)) for n in watched]
                kept = [f"{short_set(n)} {bonus_word(c.get(n, 0))}"
                        for n in watched if c.get(n, 0) >= 2]
                cells += [", ".join(kept) or "none",
                          figure(r), f"{r['dps'] - baseline['dps']:+.1f}"]
                table.append(cells)
            parts.append(rows_table(header, table) + "\n")

        ts = block.get("tier_six") or {}
        t_rows = ts.get("rows") or []
        parts.append("### The Tier 6 set\n")
        if not t_rows:
            parts.append(
                "The tier anchor wears the entry set unchanged in all five "
                "token slots: this spec's Phase 3 list keeps no tier piece "
                "there, so the tier question for it is entirely the "
                "old-bonus table above and the "
                f"[best-in-slot set](sims/{slug(spec, 'bis')}.md).\n")
        else:
            baseline = next(r for r in t_rows if not r["replaced"])
            new_sets = sorted(set(held_sets(tier, db_items))
                              - set(held_sets(entry, db_items)))
            counts = {id(r): pieces_after(
                with_slots(entry, tier, r["replaced"]), db_items, new_sets)
                for r in t_rows}
            parts.append(
                f"The [tier anchor](sims/{slug(spec, TIER_ANCHOR)}.md) "
                f"reconsiders the {', '.join(ts['slots'])} slot"
                f"{'s' if len(ts['slots']) > 1 else ''}, taking "
                + ", ".join(v["name"] for v in ts["pieces"].values())
                + ". The table "
                "prices each count of pieces and the thresholds where a "
                "Tier 6 bonus turns on.\n")

            for name in new_sets:
                full = max((counts[id(r)].get(name, 0) for r in t_rows),
                           default=0)
                for threshold in (t for t in (2, 4) if full >= t):
                    eligible = [r for r in t_rows
                                if counts[id(r)].get(name, 0) >= threshold
                                and len(r["replaced"]) == threshold]
                    if not eligible:
                        continue
                    best = max(eligible, key=lambda r: r["dps"])
                    parts.append(
                        f"The cheapest **{short_set(name)} "
                        f"{threshold}-piece** is {threshold} tokens, and "
                        f"the best way there, "
                        f"{', '.join(best['replaced'])}, measures "
                        f"{figure(best)}, "
                        f"{best['dps'] - baseline['dps']:+.1f} against the "
                        f"entry set.\n")

            order = greedy_order(t_rows)
            if len(order) > 1:
                parts.append(
                    f"Read greedily off the table, the pickup order is "
                    f"**{', then '.join(order)}**: at each count it is the "
                    f"added slot whose subset measures highest.\n")

            header = ["Pieces taken", "Slots"]
            header += [f"{short_set(n)} pieces" for n in new_sets]
            header += ["Tier 6 bonus", "DPS", "Against entry"]
            table = []
            for r in sorted(t_rows, key=lambda r: (len(r["replaced"]),
                                                   -r["dps"])):
                c = counts[id(r)]
                cells = [str(len(r["replaced"])),
                         ", ".join(r["replaced"]) or "*none, the entry set*"]
                cells += [str(c.get(n, 0)) for n in new_sets]
                on = [f"{short_set(n)} {bonus_word(c.get(n, 0))}"
                      for n in new_sets if c.get(n, 0) >= 2]
                cells += [", ".join(on) or "none",
                          figure(r), f"{r['dps'] - baseline['dps']:+.1f}"]
                table.append(cells)
            parts.append(rows_table(header, table) + "\n")

        singles = block.get("token_singles") or {}
        if singles:
            entry_base = entry_dps.get(spec)
            lines = []
            for s in ("head", "shoulder", "chest", "hands", "legs"):
                if s not in singles:
                    continue
                one = singles[s]
                gain = (f"{one['dps'] - entry_base:+.1f}"
                        if entry_base is not None else "measured")
                lines.append(f"{one['name']} ({s}) at {gain}")
            if lines:
                parts.append(
                    "The token pieces this list does not take were still "
                    "measured alone on the entry set, and they appear in "
                    "the token tables above under the same figures: "
                    + "; ".join(lines) + ". None is in this spec's "
                    "best-in-slot set.\n")

        sections.append("\n".join(parts))

    unmeasured = []
    for spec, label in UNMEASURED:
        verdict = verdicts.get(spec) or {}
        shape = " ".join((verdict.get("verdict_shape") or
                          "no recorded reading").split())
        basis = verdict.get("basis") or ""
        cite = ("a named source states it" if basis.startswith("a named")
                else "the council's own reading of the token arithmetic")
        line = (f"- **[{label}](specs/{spec.replace('_', '-')}.md)**, "
                f"unmeasured: {shape} ({cite}).")
        ordering = verdict.get("ordering")
        if ordering:
            text = " ".join(ordering.split())
            line += " Recorded ordering: " + text
            if not line.endswith("."):
                line += "."
        unmeasured.append(line)

    body = f"""---
title: Tier
eyebrow: Measurement
subtitle: >-
  Who gains what from each token, in give-out order, and at what point it
  makes sense to break an old set bonus: every subset of each spec's
  bonus-carrying slots priced against its best-in-slot pieces.
status: draft
updated: 2026-08-21
---

{BANNER}

A tier piece is never priced alone: equipping it cuts an old set by one piece,
and somewhere on that road an old bonus dies. This page answers two questions.
FIRST, the one asked at the loot table: **a token dropped, who gains what from
it**, one section per token with the give-out order the measurements support.
SECOND, per spec, **at what point breaking an old bonus pays**. For
every simulated spec, every subset of the entry set's bonus-carrying slots was
replaced with what the best-in-slot set wears there, on the otherwise
unchanged entry set, so the tables below hold the best way to take one
piece, two, three, and so on, and whether the old bonus survives each.

## How to read every table

Every row is the spec's entry set with only the named slots changed, the
entry consumables, buffs and seed held still, so every figure is directly
comparable with that spec's entry figure on
[Simulated Throughput](sims.md), and the empty row reproduces it. The plus or
minus is one standard error, not a confidence interval.

**Every replacement arrives dressed**: the piece carries the gems and the
enchant the exported profile wears on it, and a token measured outside any
profile carries the spec's standard gem in each socket. A figure here is what
the raider measures actually wearing the pieces, so a four-piece row that
reads below entry is a real statement about the set against the entry gear,
not an artifact of empty sockets.

Each spec carries two rounds. **The old-bonus round** replaces subsets of the
slots holding the entry set's live bonuses with the spec's best-in-slot pieces, the
items its best-in-slot set wears there. **The Tier 6 round** replaces subsets
of the token slots with the tier anchor's pieces, pricing the two-piece and
four-piece thresholds and the order the tokens are best taken in. Nothing
here is a ruling: the tables are measurements, and which claimant takes which
token first is the council's call.

## The tokens, one by one

Each section is one token: the specs that can redeem it, best measured gain
first. **Gain** is the token's own piece measured alone on that spec's entry
set, against its entry figure. A first piece often reads negative because no
set bonus is active yet and a replacement arrives ungemmed; the break-even
tables below say when the set pays. The standing says whether the token piece
is in that spec's best-in-slot set.

{chr(10).join(token_sections)}
## The break-evens, per spec

{chr(10).join(sections)}
## The specs this page cannot measure

No simulator run backs this list. The three tanks are out of simulation scope
by ruling, the Feral Cat's rotation is not compiled into this build, and the
healers have no captured gear set. What stands for them is the recorded
council reading of the token arithmetic, quoted here and marked for what it
is: a reading, not a measurement.

{chr(10).join(unmeasured)}
"""
    args.out.write_text(body)
    print(f"1 page -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
