#!/usr/bin/env python3
"""Write the tier page: what breaking an old set bonus costs, per spec.

WHAT THIS ANSWERS. The guild lead ruled on 20 August 2026 that the tier page's
center of gravity is "we care about at what point it makes sense to break a
bonus". The page reads every figure from data/facts/tier-sims.yaml, which
tools/run_tier_sims.py writes, and computes the break-even reading from the
recorded subsets rather than storing a second copy of any figure. Set piece
counts per row are derived here from the same gear files and item database the
runner used, so the page and the fact file cannot disagree about which bonus a
row holds.

Usage:
    python3 tools/generate_tier_page.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_sim_pages import SPEC_LABEL, figure, rows_table, slug  # noqa: E402
from run_sims import SLOT_ORDER, WOWSIMS  # noqa: E402
from run_tier_sims import (  # noqa: E402
    TIER_ANCHOR, held_sets, pieces_after, with_slots,
)

TIER_SIMS = Path("data/facts/tier-sims.yaml")
GEAR = Path("data/sim/gear")
VERDICTS = Path("data/judgments/token-verdicts.yaml")

BANNER = ("<!-- GENERATED BY tools/generate_tier_page.py. DO NOT EDIT.\n"
          "     Every figure is read from data/facts/tier-sims.yaml and every\n"
          "     set from data/sim/gear. To change what it says, rerun the "
          "sims. -->")

# The specs this build of the simulator cannot measure, with the label a
# reader knows them by. The three tanks are out by the ruling of 14 August
# 2026, the Feral Cat because its preset is a stub in this build, and the
# four healers have no captured gear set.
UNMEASURED = [
    ("feral_bear", "Feral Bear"),
    ("feral_cat", "Feral Cat"),
    ("protection_paladin", "Protection Paladin"),
    ("protection_warrior", "Protection Warrior"),
    ("holy_paladin", "Holy Paladin"),
    ("priest_healer", "Priest Healer"),
    ("restoration_druid", "Restoration Druid"),
    ("restoration_shaman", "Restoration Shaman"),
]


def short_set(name: str) -> str:
    """The set name without its Armor/Regalia/Battlegear suffix, for a
    column heading that has to stay narrow."""
    for suffix in (" Armor", " Regalia", " Battlegear", " Raiment",
                   " Harness", " Vestments"):
        if name.endswith(suffix):
            return name[:-len(suffix)]
    return name


def bonus_word(count: int) -> str:
    """What a piece count keeps, as the cell a reader scans."""
    if count >= 4:
        return "2pc and 4pc"
    if count >= 2:
        return "2pc"
    return "none"


def break_even_reading(set_name: str, threshold: int, entry_pieces: int,
                       rows: list[dict], counts: dict) -> str:
    """The break-even for one bonus: the smallest chase count at which the
    best subset that breaks it beats the best subset that keeps it.

    THE COMPARISON IS AT EQUAL COUNTS ON PURPOSE. Every replacement arrives
    ungemmed, so a row with more replacements carries more empty sockets;
    two subsets of the same size carry the same number, so at a fixed count
    the gap between the best breaker and the best keeper is the bonus
    question and not the gems.
    """
    label = f"{short_set(set_name)} {threshold}-piece"
    n = max((len(r["replaced"]) for r in rows), default=0)
    if not any(counts[id(r)].get(set_name, 0) < threshold for r in rows):
        return (f"No subset of these slots can break the {label}: the set "
                f"keeps enough pieces outside them, so the chase never "
                f"poses that question.")
    for k in range(1, n + 1):
        at_k = [r for r in rows if len(r["replaced"]) == k]
        keep = [r for r in at_k if counts[id(r)].get(set_name, 0) >= threshold]
        brk = [r for r in at_k if counts[id(r)].get(set_name, 0) < threshold]
        if not brk:
            continue
        best_b = max(brk, key=lambda r: r["dps"])
        if not keep:
            return (f"The {label} cannot survive {k} chase piece"
                    f"{'s' if k > 1 else ''} in these slots: every subset of "
                    f"that size breaks it, and the best of them, "
                    f"{', '.join(best_b['replaced'])}, measures "
                    f"{figure(best_b)}.")
        best_k = max(keep, key=lambda r: r["dps"])
        if best_b["dps"] > best_k["dps"]:
            return (f"Breaking the {label} first pays at {k} chase piece"
                    f"{'s' if k > 1 else ''}: the best subset that breaks "
                    f"it, {', '.join(best_b['replaced'])}, measures "
                    f"{figure(best_b)}, against {figure(best_k)} for the "
                    f"best that keeps it, "
                    f"{', '.join(best_k['replaced'])}.")
    return (f"At no count inside this chase set does the best subset that "
            f"breaks the {label} beat the best subset of the same size "
            f"that keeps it, so the bonus holds its price all the way to "
            f"the last of these slots.")


def greedy_order(rows: list[dict]) -> list[str]:
    """The best chase order, read greedily off the subsets: at each step the
    added slot whose superset measures highest."""
    by_set = {frozenset(r["replaced"]): r for r in rows}
    slots = max((r["replaced"] for r in rows), key=len, default=[])
    taken: list[str] = []
    while len(taken) < len(slots):
        candidates = [(by_set[frozenset(taken + [s])]["dps"], s)
                      for s in slots if s not in taken
                      and frozenset(taken + [s]) in by_set]
        if not candidates:
            break
        taken.append(max(candidates)[1])
    return taken


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=Path("docs/tier.md"))
    args = ap.parse_args()

    if not TIER_SIMS.is_file():
        print(f"error: no figures at {TIER_SIMS}. Produce them with\n"
              "  python3 tools/run_tier_sims.py --iterations 10000\n"
              "A page written from no figures would render empty tables.",
              file=sys.stderr)
        return 1

    doc = yaml.safe_load(TIER_SIMS.read_text())
    meta = doc["meta"]
    db_items = {i["id"]: i for i in json.loads(
        (WOWSIMS / "assets/database/db.json").read_text()).get("items") or []}
    verdicts = (yaml.safe_load(VERDICTS.read_text()) or {}).get(
        "verdicts") or {}

    sections = []
    for spec in sorted(doc["specs"], key=lambda s: SPEC_LABEL.get(s, s)):
        block = doc["specs"][spec]
        label = SPEC_LABEL.get(spec, spec)
        stem = spec.replace("_", "-")
        entry = json.loads((GEAR / f"{stem}.entry.gear.json").read_text())
        bis = json.loads((GEAR / f"{stem}.bis.gear.json").read_text())
        tier = json.loads(
            (GEAR / f"{stem}.{TIER_ANCHOR}.gear.json").read_text())

        parts = [f"## {label}\n"]

        ob = block.get("old_bonus") or {}
        rows = ob.get("rows") or []
        if not rows:
            parts.append(
                "The entry set holds no set at two or more pieces, so this "
                "spec walks into Phase 3 with no old bonus to break and the "
                "old-bonus round has nothing to measure.\n")
        else:
            held = ob["held_sets"]
            baseline = next(r for r in rows if not r["replaced"])
            parts.append(
                f"Walking in, this spec holds "
                f"{'; '.join(f'**{name}** at {info['pieces']} pieces, in the '
                             + ', '.join(info['slots']) + ' slots'
                             for name, info in held.items())}. "
                f"The bonuses that gear keeps live:\n")
            for text in ob.get("bonuses_held") or []:
                parts.append(f"> {text}\n")
            parts.append(
                f"The chase pieces are what the best-in-slot set wears in "
                f"the {', '.join(ob['replaceable_slots'])} slots: "
                + ", ".join(f"{v['name']}"
                            for v in ob["replacements"].values())
                + f". Every subset of those slots was run on the entry set, "
                f"and the empty subset reproduces the "
                f"[entry figure](sims/{slug(spec, 'entry')}.md) of "
                f"{figure(baseline)}.\n")

            # Derive each row's piece counts from the same gear and database
            # the runner used, so the bonus column cannot drift from the
            # figures beside it.
            watched = sorted(held)
            counts = {id(r): pieces_after(
                with_slots(entry, bis, r["replaced"]), db_items, watched)
                for r in rows}

            for name in watched:
                p = held[name]["pieces"]
                for threshold in (t for t in (4, 2) if p >= t):
                    parts.append(break_even_reading(
                        name, threshold, p, rows, counts) + "\n")

            best = max(rows, key=lambda r: r["dps"])
            singles = [r for r in rows if len(r["replaced"]) == 1]
            if singles:
                first = max(singles, key=lambda r: r["dps"])
                parts.append(
                    f"The best first chase piece is the "
                    f"**{first['replaced'][0]}**, at {figure(first)}, "
                    f"{first['dps'] - baseline['dps']:+.1f} against the "
                    f"entry set.\n")
            if best["dps"] <= baseline["dps"] and best is not baseline:
                parts.append(
                    "No subset in this round measures above the unbroken "
                    "entry set. Read that with the gem rule in mind: every "
                    "replacement arrives ungemmed, so these figures "
                    "understate a gemmed chase piece, and the full gemmed "
                    "chase is priced by the anchor figures instead.\n")
            elif best["replaced"]:
                parts.append(
                    f"The highest subset in the round is "
                    f"{', '.join(best['replaced'])}, at {figure(best)}, "
                    f"{best['dps'] - baseline['dps']:+.1f} against the "
                    f"entry set, before the gems those pieces would "
                    f"carry.\n")

            header = ["Chase pieces", "Slots replaced"]
            header += [f"{short_set(n)} pieces" for n in watched]
            header += ["Old bonus", "DPS", "Against entry"]
            table = []
            for r in sorted(rows, key=lambda r: (len(r["replaced"]),
                                                 -r["dps"])):
                c = counts[id(r)]
                cells = [str(len(r["replaced"])),
                         ", ".join(r["replaced"]) or "*none, the entry set*"]
                cells += [str(c.get(n, 0)) for n in watched]
                kept = [f"{short_set(n)} {bonus_word(c.get(n, 0))}"
                        for n in watched if c.get(n, 0) >= 2]
                cells += [", ".join(kept) or "none",
                          figure(r), f"{r['dps'] - baseline['dps']:+.1f}"]
                table.append(cells)
            parts.append(rows_table(header, table) + "\n")

        ts = block.get("tier_six") or {}
        t_rows = ts.get("rows") or []
        parts.append("### The Tier 6 chase\n")
        if not t_rows:
            parts.append(
                "The tier anchor wears the entry set unchanged in all five "
                "token slots: this spec's Phase 3 list keeps no tier piece "
                "there, so the tier question for it is entirely the "
                "old-bonus table above and the "
                f"[best-in-slot set](sims/{slug(spec, 'bis')}.md).\n")
        else:
            baseline = next(r for r in t_rows if not r["replaced"])
            new_sets = sorted(set(held_sets(tier, db_items))
                              - set(held_sets(entry, db_items)))
            counts = {id(r): pieces_after(
                with_slots(entry, tier, r["replaced"]), db_items, new_sets)
                for r in t_rows}
            parts.append(
                f"The [tier anchor](sims/{slug(spec, TIER_ANCHOR)}.md) "
                f"reconsiders the {', '.join(ts['slots'])} slot"
                f"{'s' if len(ts['slots']) > 1 else ''}, taking "
                + ", ".join(v["name"] for v in ts["pieces"].values())
                + ". Every subset was run on the entry set, so the table "
                "prices each count of pieces and the thresholds where a "
                "Tier 6 bonus turns on.\n")

            for name in new_sets:
                full = max((counts[id(r)].get(name, 0) for r in t_rows),
                           default=0)
                for threshold in (t for t in (2, 4) if full >= t):
                    eligible = [r for r in t_rows
                                if counts[id(r)].get(name, 0) >= threshold
                                and len(r["replaced"]) == threshold]
                    if not eligible:
                        continue
                    best = max(eligible, key=lambda r: r["dps"])
                    parts.append(
                        f"The cheapest **{short_set(name)} "
                        f"{threshold}-piece** is {threshold} tokens, and "
                        f"the best way there, "
                        f"{', '.join(best['replaced'])}, measures "
                        f"{figure(best)}, "
                        f"{best['dps'] - baseline['dps']:+.1f} against the "
                        f"entry set.\n")

            order = greedy_order(t_rows)
            if len(order) > 1:
                parts.append(
                    f"Read greedily off the table, the chase order is "
                    f"**{', then '.join(order)}**: at each count it is the "
                    f"added slot whose subset measures highest.\n")

            header = ["Pieces taken", "Slots"]
            header += [f"{short_set(n)} pieces" for n in new_sets]
            header += ["Tier 6 bonus", "DPS", "Against entry"]
            table = []
            for r in sorted(t_rows, key=lambda r: (len(r["replaced"]),
                                                   -r["dps"])):
                c = counts[id(r)]
                cells = [str(len(r["replaced"])),
                         ", ".join(r["replaced"]) or "*none, the entry set*"]
                cells += [str(c.get(n, 0)) for n in new_sets]
                on = [f"{short_set(n)} {bonus_word(c.get(n, 0))}"
                      for n in new_sets if c.get(n, 0) >= 2]
                cells += [", ".join(on) or "none",
                          figure(r), f"{r['dps'] - baseline['dps']:+.1f}"]
                table.append(cells)
            parts.append(rows_table(header, table) + "\n")

        sections.append("\n".join(parts))

    unmeasured = []
    for spec, label in UNMEASURED:
        verdict = verdicts.get(spec) or {}
        shape = " ".join((verdict.get("verdict_shape") or
                          "no recorded reading").split())
        basis = verdict.get("basis") or ""
        cite = ("a named source states it" if basis.startswith("a named")
                else "the council's own reading of the token arithmetic")
        line = (f"- **[{label}](specs/{spec.replace('_', '-')}.md)**, "
                f"unmeasured: {shape} ({cite}).")
        ordering = verdict.get("ordering")
        if ordering:
            text = " ".join(ordering.split())
            line += " Recorded ordering: " + text
            if not line.endswith("."):
                line += "."
        unmeasured.append(line)

    body = f"""---
title: Tier
eyebrow: Measurement
subtitle: >-
  At what point it makes sense to break an old set bonus: every subset of each
  spec's bonus-carrying slots priced against its chase pieces, and the Tier 6
  thresholds priced on the same baseline.
status: draft
updated: 2026-08-21
---

{BANNER}

A tier piece is never priced alone: equipping it cuts an old set by one piece,
and somewhere on that road an old bonus dies. This page answers the question
the council actually faces, **at what point does breaking the bonus pay**. For
every simulated spec, every subset of the entry set's bonus-carrying slots was
replaced with what the best-in-slot set wears there, on the otherwise
unchanged entry set, so the tables below hold the best way to take one chase
piece, two, three, and so on, and whether the old bonus survives each.

## How to read every table

Every row is the spec's entry set with only the named slots changed, the
entry consumables, buffs and seed held still, so every figure is directly
comparable with that spec's entry figure on
[Simulated Throughput](sims.md), and the empty row reproduces it. The plus or
minus is one standard error, not a confidence interval.

**A replaced slot keeps its enchant and a replacement arrives ungemmed.**
Which gems a chase piece takes is a separate question from what the piece is
worth, so the figures understate a gemmed replacement, and a row with more
replacements carries more empty sockets. The break-even readings therefore
compare subsets **of the same size**: two subsets of equal size carry the
same number of empty sockets, so the gap between the best that breaks a bonus
and the best that keeps it is the bonus question and not the gems. The fully
gemmed destination is priced by the anchor figures on the set pages, not
here.

Each spec carries two rounds. **The old-bonus round** replaces subsets of the
slots holding the entry set's live bonuses with the spec's chase pieces, the
items its best-in-slot set wears there. **The Tier 6 chase** replaces subsets
of the token slots with the tier anchor's pieces, pricing the two-piece and
four-piece thresholds and the order the tokens are best taken in. Nothing
here is a ruling: the tables are measurements, and which claimant takes which
token first is the council's call.

{chr(10).join(sections)}
## The specs this page cannot measure

No simulator run backs this list. The three tanks are out of simulation scope
by ruling, the Feral Cat's rotation is not compiled into this build, and the
healers have no captured gear set. What stands for them is the recorded
council reading of the token arithmetic, quoted here and marked for what it
is: a reading, not a measurement.

{chr(10).join(unmeasured)}
"""
    args.out.write_text(body)
    print(f"1 page -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
