#!/usr/bin/env python3
"""Write the simulated throughput page and one page per simulated set.

WHAT THIS ANSWERS AND WHAT IT DOES NOT. The table answers "what did this spec
measure at this gear anchor, and how tight is that figure". It does NOT rank one
spec above another and it does not price an item: two specs on the same row of
this table are two different classes running two different rotations, and the
comparison that means something is a spec against ITSELF at another anchor. That
warning is printed on the page rather than left to the reader, because a table
of thirteen numbers sorted by nothing still reads as a league table.

WHY EVERY FIGURE IS CLICKABLE. A DPS number with no set behind it is the kind of
figure this project keeps having to retract. Each cell links to the exact
seventeen slots, enchants, gems, consumables, buffs and talents the run was
configured with, so a reader can reproduce it or find the mistake in it.

THE BUFFS AND CONSUMABLES ARE NOT RESTATED, THEY ARE ASKED FOR. This tool
imports tools/run_sims.py and calls the same functions that build the request,
so a detail page describes the run that actually happened. Writing the buff list
out here would be a second copy, and a second copy is the one that goes stale
the next time a tristate is corrected.

Usage:
    python3 tools/generate_sim_pages.py
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import run_sims  # noqa: E402

FIGURES = Path("data/facts/sim-figures.yaml")
WEAPON_PAIRS = Path("data/facts/weapon-pair-sims.yaml")
GEAR = Path("data/sim/gear")
ITEMS = Path("data/facts/items.csv")
ROSTER = Path("data/facts/roster.yaml")
BUFFS = Path("data/facts/raid-buffs.yaml")
BIS_CAPTURES = Path("data/facts/sim-profiles/bis-capture")
DB = Path(os.path.expanduser(os.environ.get(
    "WOWSIMS_TBC",
    "../tbc-phase-research-recovered/data/raw/vendor/wowsims-tbc-new-master",
))) / "assets/database/db.json"

# THE THREE ANCHORS, in the order a raider meets them, which is also the order
# they must always print in. `tier_hands_and_head` is the profile stem the
# exporter writes and `Tier` is what a reader calls it; both are here so the
# link and the label never have to be derived from each other.
ANCHORS = [
    ("entry", "Entry", "The Phase 2 best-in-slot set. What a raider walks into "
                       "Phase 3 wearing."),
    ("tier-hands-and-head", "Tier",
     "The entry set with ONLY the five token slots reconsidered. Weapons, "
     "trinkets and the other twelve slots are identical to entry."),
    ("bis", "BiS", "The full Phase 3 best-in-slot set, with the guild lead's "
                   "weapon routing applied."),
    # A FOURTH ANCHOR THAT ONLY TWO SPECS HAVE. It is not a column in the main
    # table, because eleven specs would carry a blank; it gets its own section
    # and its own set pages.
    ("bis-no-glaives", "BiS without Warglaives",
     "The same best-in-slot set with the next best weapons this spec can get "
     "instead of the Warglaives of Azzinoth."),
]

# The three every spec has, which is what the summary table shows.
MAIN_ANCHORS = ANCHORS[:3]

SLOT_LABEL = {
    "head": "Head", "neck": "Neck", "shoulder": "Shoulder", "back": "Back",
    "chest": "Chest", "wrist": "Wrist", "hands": "Hands", "waist": "Waist",
    "legs": "Legs", "feet": "Feet", "ring_1": "Ring 1", "ring_2": "Ring 2",
    "trinket_1": "Trinket 1", "trinket_2": "Trinket 2",
    "main_hand": "Main hand", "off_hand": "Off hand", "ranged": "Ranged",
}

SPEC_LABEL = {
    "affliction_warlock": "Affliction Warlock",
    "arcane_mage": "Arcane Mage",
    "arms_warrior": "Arms Warrior",
    "balance_druid": "Balance Druid",
    "beast_mastery_hunter": "Beast Mastery Hunter",
    "combat_rogue": "Combat Rogue",
    "destruction_warlock": "Destruction Warlock",
    "elemental_shaman": "Elemental Shaman",
    "enhancement_shaman": "Enhancement Shaman",
    "fury_warrior": "Fury Warrior",
    "retribution_paladin": "Retribution Paladin",
    "shadow_priest": "Shadow Priest",
    "survival_hunter": "Survival Hunter",
}

BANNER = ("<!-- GENERATED BY tools/generate_sim_pages.py. DO NOT EDIT.\n"
          "     Every figure is read from data/facts/sim-figures.yaml and every\n"
          "     set from data/sim/gear. To change what it says, rerun the sim. -->")


def slug(spec: str, anchor: str) -> str:
    """The page name. Hyphens throughout, because it becomes a URL."""
    return f"{spec.replace('_', '-')}-{anchor}"


def gear_stem(spec: str, anchor: str) -> str:
    """The gear file name, which separates spec from anchor with a DOT.

    THE TWO NAMING SCHEMES ARE NOT INTERCHANGEABLE and confusing them fails
    silently. `tools/export_sim_profiles.py` writes `combat-rogue.bis.gear.json`
    because run_sims.py splits the stem on the first dot to recover the spec,
    and a page is `combat-rogue-bis.md` because a URL should not carry a dot.
    Built with a hyphen, every gear lookup missed, `write_detail` returned zero
    for all thirty-nine pages, and the index still rendered with every figure in
    place and every link pointing at a page that did not exist.
    """
    return f"{spec.replace('_', '-')}.{anchor}"


def figure(row: dict) -> str:
    """One DPS figure with its spread, in the one format this project uses."""
    if row.get("standard_error") is None:
        return f"{row['dps']:.1f}"
    return f"{row['dps']:.1f} ± {row['standard_error']:.2f}"


def rows_table(header: list[str], rows: list[list[str]]) -> str:
    """A pipe table, padded so the Markdown source is readable in a diff."""
    widths = [max(len(header[i]), *(len(r[i]) for r in rows)) if rows
              else len(header[i]) for i in range(len(header))]
    out = ["| " + " | ".join(h.ljust(widths[i]) for i, h in enumerate(header))
           + " |",
           "|" + "|".join("-" * (w + 2) for w in widths) + "|"]
    for row in rows:
        out.append("| " + " | ".join(cell.ljust(widths[i])
                                     for i, cell in enumerate(row)) + " |")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--figures", type=Path, default=FIGURES)
    ap.add_argument("--out", type=Path, default=Path("docs"))
    args = ap.parse_args()

    if not args.figures.is_file():
        print(f"error: no figures at {args.figures}. Produce them with\n"
              "  python3 tools/run_sims.py --iterations 10000 "
              f"--out {args.figures}\n"
              "A page written from no figures would render empty rows, which "
              "reads as a spec measuring nothing.", file=sys.stderr)
        return 1

    doc = yaml.safe_load(args.figures.read_text())
    meta = doc["meta"]
    # KEYED ON ARMOR AS WELL, because a figure at one boss armor tier is not
    # comparable with a figure at another. DEFAULT_ARMOR is the tier ten of the
    # fourteen Phase 3 bosses sit in, and it is what the summary table shows.
    tiers = sorted({r.get("boss_armor", 0) for r in doc["results"]}, reverse=True)
    default_armor = 6193 if 6193 in tiers else tiers[0]
    by_key = {(r["spec"], r["anchor"], r.get("boss_armor", 0)): r
              for r in doc["results"]}
    specs = sorted({r["spec"] for r in doc["results"]},
                   key=lambda s: SPEC_LABEL.get(s, s))

    items_csv = {int(r["item_id"]): r for r in csv.DictReader(ITEMS.open())}
    db = json.loads(DB.read_text())
    db_items = {i["id"]: i for i in db["items"]}
    gems_by_id = {g["id"]: g["name"] for g in db["gems"]}
    enchant_by_effect = {e["effectId"]: e["name"] for e in db["enchants"]}
    consumable_name = {}
    for group in ("items", "gems"):
        for entry in db.get(group) or []:
            consumable_name[entry["id"]] = entry["name"]

    buffs_doc = yaml.safe_load(BUFFS.read_text())
    roster = yaml.safe_load(ROSTER.read_text())
    party_of: dict[str, str] = {}
    for group in roster.get("groups") or []:
        for member in group.get("members") or []:
            party_of.setdefault(member, group["id"])

    talents = yaml.safe_load(
        Path("data/facts/talents.yaml").read_text(
        ))["wowsims_talent_strings"]["strings"]

    detail_dir = args.out / "sims"
    detail_dir.mkdir(parents=True, exist_ok=True)
    for stale in detail_dir.glob("*.md"):
        stale.unlink()

    written = 0
    for spec in specs:
        for anchor, label, _why in ANCHORS:
            row = by_key.get((spec, anchor, default_armor))
            if row is None:
                continue
            written += write_detail(
                detail_dir, spec, anchor, label, row, meta, items_csv,
                by_key, tiers, default_armor,
                db_items, gems_by_id, enchant_by_effect, consumable_name,
                buffs_doc, party_of, talents)

    write_index(args.out / "sims.md", specs, by_key, meta, tiers,
                default_armor)
    print(f"1 index and {written} set page(s) -> {args.out}/sims.md, "
          f"{detail_dir}/")
    return 0


def write_index(path: Path, specs: list[str], by_key: dict, meta: dict,
                tiers: list, default_armor: int) -> None:
    """The one table, and the warnings that have to travel with it."""
    # EACH STEP GETS ITS OWN COLUMN, because the two halves answer different
    # questions. Entry to Tier is what the five tier tokens alone are worth, and
    # Tier to BiS is what the other twelve slots are worth once the weapons and
    # trinkets finally move. A single Entry to BiS figure hides which of the two
    # a spec's gain came from, and for several specs the split is very uneven.
    # EACH DELTA SITS BETWEEN THE TWO FIGURES IT MEASURES, not in a block at the
    # end. A reader following one spec's row left to right then meets the set,
    # what the next step of gearing is worth, the next set, and so on, instead of
    # having to track back across three columns to find which pair a delta
    # belongs to. The overall Entry to BiS total closes the row.
    header = ["Spec", "Entry", "Entry to Tier", "Tier", "Tier to BiS", "BiS",
              "Entry to BiS"]
    rows, order = [], []
    for spec in specs:
        got = {a: by_key.get((spec, a, default_armor))
               for a, _l, _w in MAIN_ANCHORS}
        entry = got.get("entry")
        tier = got.get("tier-hands-and-head")

        def cell(anchor, row, s=spec):
            return (f"[{figure(row)}](sims/{slug(s, anchor)}.md)"
                    if row else "not simulated")

        def delta(a, b):
            return f"{b['dps'] - a['dps']:+.1f}" if a and b else "not comparable"

        # A SPEC WITH A SECOND BEST-IN-SLOT SET GETS A SECOND ROW, so it sorts
        # into the table beside everyone else rather than sitting in a section
        # below it. Entry and Tier are the SAME runs in both rows, because the
        # variant differs only in the two weapon slots of the best-in-slot set.
        variants = [("bis", SPEC_LABEL.get(spec, spec))]
        if (spec, "bis-no-glaives", default_armor) in by_key:
            variants.append(("bis-no-glaives",
                             SPEC_LABEL.get(spec, spec) + ", no Warglaives"))
        for anchor, label in variants:
            bis = by_key.get((spec, anchor, default_armor))
            rows.append([
                label,
                cell("entry", entry), delta(entry, tier),
                cell("tier-hands-and-head", tier), delta(tier, bis),
                cell(anchor, bis), delta(entry, bis),
            ])
            order.append(bis["dps"] if bis else float("-inf"))

    # THE PAGE LOADS SORTED BY BEST-IN-SLOT, HIGHEST FIRST. Ruled by the guild
    # lead on 16 August 2026, replacing spec order. A row with no best-in-slot
    # figure sorts last rather than acting like a zero, which is the same rule
    # the sorting script applies to a cell holding no number.
    rows = [r for _k, r in sorted(zip(order, rows), key=lambda p: -p[0])]

    body = f"""---
title: Simulated Throughput
eyebrow: Measurement
subtitle: >-
  What each spec measures at three gear anchors, with the spread on every
  figure, and the exact set behind each one.
status: draft
updated: 2026-08-15
---

{BANNER}

A published best-in-slot list answers "is this item my best in slot". This page
answers a different question: **what does a spec actually measure, wearing a
stated set, against a stated encounter.** It does not answer which spec is
better, and the numbers below must not be read that way. Two rows are two
classes running two rotations written by other people, and the rotation quality
varies between specs far more than it varies within one. **The comparison that
carries meaning is a spec against ITSELF at another anchor**, which is why the
last column exists, and it is why the order of the rows is not a ranking.

## What each spec measures

Each spec is simulated in three complete sets of gear, and a figure means
nothing without knowing which set produced it. Every figure is a link into that
exact set: seventeen slots with their enchants and gems, the consumables drunk,
the buffs and debuffs applied, the talent string and the rotation.

**Entry** is the spec's Phase 2 best-in-slot set, captured from the published
list for that spec. It is what a raider walks into Phase 3 already wearing, so
it is the floor every Phase 3 drop is measured against. Season 2 arena gear is
in it and Season 3 is not, because Season 3 opens five days after the phase.

**Tier** is the entry set with ONLY the five tier token slots reconsidered.
Nothing else moves: the weapons, the trinkets and the other twelve slots are the
same items the entry set wears. It exists to answer one narrow question, what
the tier tokens alone are worth to a raider who has just walked in, and it
answers nothing else.

**BiS** is the full Phase 3 best-in-slot set, every slot, captured from that
spec's published Phase 3 list and then adjusted by the guild lead's weapon and
trinket routing where a published list gives a spec something this raid will not
give it. It is the ceiling for one spec rather than a description of the raid.

**Entry to Tier** is therefore what the tokens are worth, and **Tier to BiS** is
what everything else is worth once the weapons and trinkets finally move. The
two are wildly uneven per spec, which is why they are separate columns.

**Every column sorts.** Click a heading to order by it, click again to reverse.
The page loads ordered by the best-in-slot figure, highest first. Read that
order as what each set measured and not as a ranking of the players: these
specs run rotations written by different authors, and a spec is only strictly
comparable with itself at another anchor.

::: {{.sortable default-sort="5"}}
{rows_table(header, rows)}
:::

## The same spec against a harder boss

**This section answers where a drop will actually be used.** Every figure above
is against one boss armor value, and Phase 3 does not have one: it has two.
Armor is subtracted before any physical damage lands, so the same spec in the
same gear measures materially lower on a high-armor boss and a pure caster does
not move at all. A council weighing a physical item for Black Temple is weighing
it in a harder world than the same item for Mount Hyjal.

**The gear does not change here. Only the boss does.** Every row below is that
spec's BIS SET, exactly as the table above simulates it, re-run unchanged
against each armor value Phase 3 contains. Nothing about the character is
different between the three columns, so the whole spread is the boss.

The table above is the 6193 column, because ten of the fourteen bosses sit in
that tier.

**The last column is simply the 7684 figure minus the 6193 figure**: how much
damage that spec gives up when the boss is one of the armoured ones. It sorts,
and sorting by it splits the roster cleanly in two. Every physical spec pays,
and the five pure casters pay nothing at all, which is the correct behaviour and
a standing check that the armor model does what it claims.

::: {{.sortable}}
{rows_table(["Spec"] + [f"Armor {a}" for a in tiers]
            + [f"Lost on a {max(tiers)} boss"],
            [[SPEC_LABEL.get(s, s)]
             + [(f"{by_key[(s, 'bis', a)]['dps']:.1f}"
                 if (s, 'bis', a) in by_key else "-") for a in tiers]
             + [(f"{by_key[(s, 'bis', max(tiers))]['dps'] - by_key[(s, 'bis', default_armor)]['dps']:+.1f}"
                if (s, 'bis', max(tiers)) in by_key
                and (s, 'bis', default_armor) in by_key else "-")]
             for s in specs])}
:::

Which boss sits in which tier is [`boss-armor.yaml`](../data/facts/boss-armor.yaml),
one row per boss with its own source and confidence.

{rows_table(["Armor", "Mitigation", "Targets"],
            [[str(a), f"{100 * a / (a + 10557.5):.2f}%",
              ", ".join(meta["armor_tiers_run"].get(a, [])) or "none"]
             for a in tiers])}

::: {{.note}}
**Veras Darkshadow carries no figure**, and that is deliberate. His armor is
near-zero, approximately 137 to 146, and the exact value was never measured in
the TBC era, so `boss-armor.yaml` records the magnitude and no digits rather
than implying a precision nobody has. Read him against the zero column.
:::

## How every figure was produced

Two runs are subtractable only when everything around the gear was held still.
This table states what was held still, and it is the same for every row above.

{rows_table(["Setting", "Value"], [
    ["Simulator", meta.get("simulator", "unrecorded")],
    ["Iterations", str(meta["iterations"])],
    ["Random seed", str(meta["seed"])],
    ["Encounter", f"{meta['encounter_seconds']} seconds, "
                  f"{meta['targets']} target at level {meta['target_level']}"],
    ["Interval", "one standard error on the mean"],
])}

## What is not on this page

Four specs are absent, and each for a stated reason rather than an oversight.

- **The three tanks**, Feral Bear, Protection Paladin and Protection Warrior.
  Ruled out of scope by the guild lead on 14 August 2026: a tank run answers
  survivability questions this project does not ask.
- **The Feral Cat.** Its preset in this build of the simulator is a stub with no
  rotation and no talents, and eleven of the fourteen files in the cat directory
  are excluded from the build, so the abilities are not compiled in. A figure
  from it would be a non-result rather than a low one.
- **The four healers.** No healer has a captured gear set, and the simulator
  checkout excludes the shaman healing code from compilation for the same
  underscore reason.
"""
    path.write_text(body)


def weapon_pair_section(spec: str, anchor: str, row: dict, meta: dict) -> str:
    """A spec's weapon pair variants, as a section of one anchor page.

    RULED BY THE GUILD LEAD ON 20 AUGUST 2026: the weapons analysis is
    variants on the existing entry, tier and best-in-slot profile sims, shown
    on these detail pages, and more specs are expected to carry a round. The
    figures are read from data/facts/weapon-pair-sims.yaml, which
    tools/run_weapon_pair_sims.py writes, so this section appears for exactly
    the specs and anchors that file holds and changes only when the round
    reruns. The Enhancement round is ruled in
    data/judgments/enhancement-weapon-rules.yaml.
    """
    if not WEAPON_PAIRS.is_file():
        return ""
    doc = yaml.safe_load(WEAPON_PAIRS.read_text())
    block = (doc.get("specs") or {}).get(spec)
    if not block:
        return ""
    pairs = (block.get("anchors") or {}).get(anchor)
    if not pairs:
        return ""

    table_rows = []
    for entry in pairs:
        table_rows.append([
            entry["main_hand"]["name"], entry["off_hand"]["name"],
            f"{entry['pair_speed']:.1f}",
            f"{entry['dps']:.1f} ± {entry['standard_error']:.2f}",
            f"{entry['dps'] - row['dps']:+.1f}",
        ])

    # THREE READINGS, NOT TWO. A set whose worn pair is itself the best row
    # produces a delta of zero, and the two-way version read that as "the
    # rule is a cost, by 0.0 DPS", which is a sentence about nothing. The
    # tolerance is one rounding step of the recorded figures, not a
    # significance test.
    best = pairs[0]
    if abs(best["dps"] - row["dps"]) < 0.05:
        reading = (
            "This set already wears the best pair the round measured, which "
            "is why its top row reads plus zero: that row IS this profile.")
    elif best["dps"] > row["dps"]:
        reading = (
            f"The best pair, {best['main_hand']['name']} with "
            f"{best['off_hand']['name']}, measures "
            f"{best['dps'] - row['dps']:+.1f} against this set's own pair, "
            "so at this anchor the pair rule and throughput point the same "
            "way.")
    else:
        reading = (
            f"Every pair below measures UNDER this set's own pair, the best "
            f"of them by {row['dps'] - best['dps']:.1f} DPS, so at this "
            "anchor the simulator prices the pair rule as a cost, not a "
            "gain. What that does and does not settle is recorded in "
            "data/facts/sim-results.yaml under "
            "what_the_matched_pairs_measure, and the rule stands until the "
            "council revisits it.")

    return f"""
## Weapon pairs

{block['why']}

Not a ruling: which pair this anchor wears is the council's call.

{rows_table(["Main hand", "Off hand", "Pair speed", "DPS",
             "Against this set"], table_rows)}

{reading}
"""


def write_detail(directory: Path, spec: str, anchor: str, label: str,
                 row: dict, meta: dict, items_csv: dict,
                 by_key: dict, tiers: list, default_armor: int, db_items: dict,
                 gems_by_id: dict, enchant_by_effect: dict,
                 consumable_name: dict, buffs_doc: dict, party_of: dict,
                 talents: dict) -> int:
    """One page: the whole request, in the order a reader checks it."""
    gear_path = Path("data/sim/gear") / f"{gear_stem(spec, anchor)}.gear.json"
    if not gear_path.is_file():
        # LOUD, NOT SKIPPED. A missing gear file used to return 0 here in
        # silence, and the index went on rendering a link to a page that was
        # never written. A figure with no set behind it is exactly what this
        # page exists to make impossible.
        raise SystemExit(
            f"error: {gear_path} does not exist, but sim-figures.yaml carries "
            f"a figure for {spec} at {anchor}. Rerun `just regen` to rebuild "
            "the profiles, or rerun `just sim` so the figures match them.")
    gear = json.loads(gear_path.read_text())

    gear_rows = []
    for i, slot in enumerate(run_sims.SLOT_ORDER):
        entry = gear["items"][i] if i < len(gear["items"]) else {}
        if not entry:
            gear_rows.append([SLOT_LABEL[slot], "*empty*", "", ""])
            continue
        item_id = entry["id"]
        name = (items_csv.get(item_id) or {}).get("name") \
            or (db_items.get(item_id) or {}).get("name") or str(item_id)
        enchant = enchant_by_effect.get(entry.get("enchant"), "")
        gems = ", ".join(f"`{gems_by_id.get(g, g)}`" for g in entry.get("gems", []))
        gear_rows.append([SLOT_LABEL[slot], f"`{name}`",
                          f"`{enchant}`" if enchant else "", gems])

    # THE NAME COMES FROM THE FACT TABLE, NOT FROM THE ITEM DATABASE. A flask,
    # a food and an oil are not in `db.json.items`, so a database lookup returns
    # the raw id and the page prints `22854`, which nobody can check against the
    # guide the pick came from. consumable-ids.yaml records the name beside the
    # id for exactly this reason.
    key = anchor.replace("-", "_")
    consumables = run_sims.consumables_for(spec, key)
    picks = ((yaml.safe_load(Path("data/facts/consumable-ids.yaml").read_text()
                             ).get("picks") or {}).get(spec) or {}).get(key) or {}
    named = {}
    for field, entry in picks.items():
        camel = field.split("_")[0] + "".join(
            w.title() for w in field.split("_")[1:])
        named[camel] = entry.get("name")
    consumable_rows = []
    for field, value in sorted(consumables.items()):
        # THE LIST HALF OF A TWO-FIELD PAIR IS NOT ITS OWN CONSUMABLE.
        # `potions` and `conjuredItems` exist only because the simulator
        # registers a cooldown by iterating a list while the id beside it
        # selects which entry to drink. Printing both would show one consumable
        # twice, and a list is not hashable so it also crashed the name lookup.
        if isinstance(value, list):
            continue
        if isinstance(value, bool):
            # A scroll is a flag rather than an id, so it has no name to resolve.
            consumable_rows.append([f"`{field}`", "`yes`" if value else "`no`",
                                    ""])
            continue
        # NOT `label`. That is this function's anchor-name parameter, and
        # reassigning it here retitled every set page after whichever
        # consumable sorted last: "Arms Warrior, Haste Potion Set" instead of
        # "Arms Warrior, BiS Set". It shipped to the published site because the
        # title is built further down and nothing reads it in between.
        name_of = named.get(field) or consumable_name.get(value) or str(value)
        consumable_rows.append([f"`{field}`", f"`{name_of}`", str(value)])

    raid, party, debuffs = run_sims.buffs_for(spec, buffs_doc, party_of)
    types = run_sims.proto_field_types()
    individual = {}
    wanted = ["blessingOfKings",
              "blessingOfMight" if spec in run_sims.PHYSICAL
              else "blessingOfWisdom"]
    if spec in run_sims.PHYSICAL and party_of.get(spec) in ("g1", "g2"):
        wanted.append("unleashedRage")
    if party_of.get(spec) == "g4":
        wanted.append("shadowPriestDps")
    for field in wanted:
        value = run_sims.typed(field, types["IndividualBuffs"][field])
        if value is not None:
            individual[field] = value

    def buff_rows(block: dict) -> list[list[str]]:
        return [[f"`{k}`", f"`{v}`"] for k, v in sorted(block.items())]

    divergence = gear.get("_divergence") or []
    # THE ROUTING DIVERGENCES ARE NOT PRINTED HERE. Removed on the guild lead's
    # instruction, 15 August 2026. Every slot the guild lead routed away from
    # what a published page ranks is recorded in that spec's own capture, under
    # `routing_applied` in data/facts/sim-profiles/bis-capture/, and the ruling
    # behind each is in data/judgments/weapon-routing.yaml and
    # trinket-routing.yaml. Nothing is lost by leaving it off the page; it is
    # stated where a reader checking a decision would look for it.

    spec_label = SPEC_LABEL.get(spec, spec)
    body = f"""---
title: {spec_label}, {label} Set
eyebrow: Simulated Set
subtitle: >-
  The whole request behind one figure: {figure(row)} damage per second.
status: draft
updated: 2026-08-15
---

{BANNER}

This page answers "what exactly was simulated to get that number". It does not
argue that the set is correct, and it does not price any item on it. It is the
request, written out, so the figure above it can be reproduced or disproved.

Back to [Simulated Throughput](../sims.md).

{rows_table(["Figure", "Value"], [
    ["Damage per second, averaged over "
     f"{meta['iterations']} pulls", f"**{row['dps']:.1f}**"],
    ["How precisely that average is known",
     f"± {row['standard_error']:.2f} DPS"
     if row.get('standard_error') is not None else "not recorded"],
    ["How much a SINGLE pull varies",
     f"± {row['stdev']:.1f} DPS"
     if row.get('stdev') is not None else "not recorded"],
    ["Anchor", f"{label}. {dict((a, w) for a, _l, w in ANCHORS)[anchor]}"],
])}

::: {{.note}}
**The plus or minus is DPS**, and it says how precisely the average is known
rather than how much a pull varies. The average of {meta['iterations']} pulls is
pinned to that many DPS; a single pull swings by the figure in the row below it,
which is far larger.
:::

The figure above is against boss armor {default_armor}. This same set was run
against every Phase 3 armor tier, and armor is subtracted before any physical
damage lands, so a physical spec moves between them and a pure caster does not.

{rows_table(["Boss armor", "Mitigation", "This set measures", "Targets at that armor"],
            [[str(a), f"{100 * a / (a + 10557.5):.2f}%",
              (f"{by_key[(spec, anchor, a)]['dps']:.1f} "
               f"± {by_key[(spec, anchor, a)]['standard_error']:.2f}"
               if (spec, anchor, a) in by_key else "not run"),
              ", ".join(meta["armor_tiers_run"].get(a, [])[:3])
              + (" ..." if len(meta["armor_tiers_run"].get(a, [])) > 3 else "")]
             for a in tiers])}
"""

    if divergence:
        body += "\n::: {.note .veto}\n**This profile does NOT wear what the "
        body += "compendium says this spec wears.**\n\n"
        for line in divergence:
            body += f"- {line}\n"
        body += ":::\n"

    body += weapon_pair_section(spec, anchor, row, meta)

    body += f"""
## The set

Seventeen slots, with the enchant and the gems each carries. An empty row is a
slot the profile deliberately leaves unfilled, which for a two-handed weapon is
the off hand.

{rows_table(["Slot", "Item", "Enchant", "Gems"], gear_rows)}

## Consumables

Consumables are assumed in every run, per the framework, and they are not
counted in the hit cap states, because those two settings answer different
questions.

{rows_table(["Field", "Consumable", "Item id"], consumable_rows)}

## Buffs and debuffs

The rest of the raid is not simulated. Its whole contribution is the four blocks
below, derived from the roster rather than switched on wholesale, so a spec gets
a totem only when it sits in the party carrying it.

The raid-wide buffs every party receives.

{rows_table(["Field", "Value"], buff_rows(raid)) if raid
 else "None recorded."}

The party buffs this spec receives, from party `{party_of.get(spec, 'unplaced')}`.

{rows_table(["Field", "Value"], buff_rows(party)) if party
 else "None recorded."}

The buffs applied to this player alone.

{rows_table(["Field", "Value"], buff_rows(individual)) if individual
 else "None recorded."}

The debuffs applied to the target.

{rows_table(["Field", "Value"], buff_rows(debuffs)) if debuffs
 else "None recorded."}

## Talents, rotation and encounter

The rotation is the action priority list the simulator itself ships for this
spec. Writing our own would be a modelling choice we could not defend, and
taking theirs is one we can cite.

{rows_table(["Setting", "Value"], [
    ["Talent string", f"`{(talents.get(spec) or {}).get('string', 'none')}`"],
    ["Rotation", f"`ui/{run_sims.APL[spec]}`"],
    ["Simulator", meta.get("simulator", "unrecorded")],
    ["Iterations", str(meta["iterations"])],
    ["Random seed", str(meta["seed"])],
    ["Encounter", f"{meta['encounter_seconds']} seconds, "
                  f"{meta['targets']} target at level {meta['target_level']}"],
])}
"""
    (directory / f"{slug(spec, anchor)}.md").write_text(body)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
