#!/usr/bin/env python3
"""Write the simulated throughput page and one page per simulated set.

WHAT THIS ANSWERS AND WHAT IT DOES NOT. The table answers "what did this spec
measure at this gear anchor, and how tight is that figure". It does NOT rank one
spec above another and it does not price an item: two specs on the same row of
this table are two different classes running two different rotations, and the
comparison that means something is a spec against ITSELF at another anchor. That
warning is printed on the page rather than left to the reader, because a table
of thirteen numbers sorted by nothing still reads as a league table.

WHY EVERY FIGURE IS CLICKABLE. A DPS number with no set behind it is the kind of
figure this project keeps having to retract. Each cell links to the exact
seventeen slots, enchants, gems, consumables, buffs and talents the run was
configured with, so a reader can reproduce it or find the mistake in it.

THE BUFFS AND CONSUMABLES ARE NOT RESTATED, THEY ARE ASKED FOR. This tool
imports tools/run_sims.py and calls the same functions that build the request,
so a detail page describes the run that actually happened. Writing the buff list
out here would be a second copy, and a second copy is the one that goes stale
the next time a tristate is corrected.

Usage:
    python3 tools/generate_sim_pages.py
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import run_sims  # noqa: E402

FIGURES = Path("data/facts/sim-figures.yaml")
GEAR = Path("data/sim/gear")
ITEMS = Path("data/facts/items.csv")
ROSTER = Path("data/facts/roster.yaml")
BUFFS = Path("data/facts/raid-buffs.yaml")
BIS_CAPTURES = Path("data/facts/sim-profiles/bis-capture")
DB = Path(os.path.expanduser(os.environ.get(
    "WOWSIMS_TBC",
    "../tbc-phase-research-recovered/data/raw/vendor/wowsims-tbc-new-master",
))) / "assets/database/db.json"

# THE THREE ANCHORS, in the order a raider meets them, which is also the order
# they must always print in. `tier_hands_and_head` is the profile stem the
# exporter writes and `Tier` is what a reader calls it; both are here so the
# link and the label never have to be derived from each other.
ANCHORS = [
    ("entry", "Entry", "The Phase 2 best-in-slot set. What a raider walks into "
                       "Phase 3 wearing."),
    ("tier-hands-and-head", "Tier",
     "The entry set with ONLY the five token slots reconsidered. Weapons, "
     "trinkets and the other twelve slots are identical to entry."),
    ("bis", "BiS", "The full Phase 3 best-in-slot set, with the guild lead's "
                   "weapon routing applied."),
]

SLOT_LABEL = {
    "head": "Head", "neck": "Neck", "shoulder": "Shoulder", "back": "Back",
    "chest": "Chest", "wrist": "Wrist", "hands": "Hands", "waist": "Waist",
    "legs": "Legs", "feet": "Feet", "ring_1": "Ring 1", "ring_2": "Ring 2",
    "trinket_1": "Trinket 1", "trinket_2": "Trinket 2",
    "main_hand": "Main hand", "off_hand": "Off hand", "ranged": "Ranged",
}

SPEC_LABEL = {
    "affliction_warlock": "Affliction Warlock",
    "arcane_mage": "Arcane Mage",
    "arms_warrior": "Arms Warrior",
    "balance_druid": "Balance Druid",
    "beast_mastery_hunter": "Beast Mastery Hunter",
    "combat_rogue": "Combat Rogue",
    "destruction_warlock": "Destruction Warlock",
    "elemental_shaman": "Elemental Shaman",
    "enhancement_shaman": "Enhancement Shaman",
    "fury_warrior": "Fury Warrior",
    "retribution_paladin": "Retribution Paladin",
    "shadow_priest": "Shadow Priest",
    "survival_hunter": "Survival Hunter",
}

BANNER = ("<!-- GENERATED BY tools/generate_sim_pages.py. DO NOT EDIT.\n"
          "     Every figure is read from data/facts/sim-figures.yaml and every\n"
          "     set from data/sim/gear. To change what it says, rerun the sim. -->")


def slug(spec: str, anchor: str) -> str:
    """The page name. Hyphens throughout, because it becomes a URL."""
    return f"{spec.replace('_', '-')}-{anchor}"


def gear_stem(spec: str, anchor: str) -> str:
    """The gear file name, which separates spec from anchor with a DOT.

    THE TWO NAMING SCHEMES ARE NOT INTERCHANGEABLE and confusing them fails
    silently. `tools/export_sim_profiles.py` writes `combat-rogue.bis.gear.json`
    because run_sims.py splits the stem on the first dot to recover the spec,
    and a page is `combat-rogue-bis.md` because a URL should not carry a dot.
    Built with a hyphen, every gear lookup missed, `write_detail` returned zero
    for all thirty-nine pages, and the index still rendered with every figure in
    place and every link pointing at a page that did not exist.
    """
    return f"{spec.replace('_', '-')}.{anchor}"


def figure(row: dict) -> str:
    """One DPS figure with its spread, in the one format this project uses."""
    if row.get("standard_error") is None:
        return f"{row['dps']:.1f}"
    return f"{row['dps']:.1f} ± {row['standard_error']:.2f}"


def rows_table(header: list[str], rows: list[list[str]]) -> str:
    """A pipe table, padded so the Markdown source is readable in a diff."""
    widths = [max(len(header[i]), *(len(r[i]) for r in rows)) if rows
              else len(header[i]) for i in range(len(header))]
    out = ["| " + " | ".join(h.ljust(widths[i]) for i, h in enumerate(header))
           + " |",
           "|" + "|".join("-" * (w + 2) for w in widths) + "|"]
    for row in rows:
        out.append("| " + " | ".join(cell.ljust(widths[i])
                                     for i, cell in enumerate(row)) + " |")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--figures", type=Path, default=FIGURES)
    ap.add_argument("--out", type=Path, default=Path("docs"))
    args = ap.parse_args()

    if not args.figures.is_file():
        print(f"error: no figures at {args.figures}. Produce them with\n"
              "  python3 tools/run_sims.py --iterations 10000 "
              f"--out {args.figures}\n"
              "A page written from no figures would render empty rows, which "
              "reads as a spec measuring nothing.", file=sys.stderr)
        return 1

    doc = yaml.safe_load(args.figures.read_text())
    meta = doc["meta"]
    by_key = {(r["spec"], r["anchor"]): r for r in doc["results"]}
    specs = sorted({r["spec"] for r in doc["results"]},
                   key=lambda s: SPEC_LABEL.get(s, s))

    items_csv = {int(r["item_id"]): r for r in csv.DictReader(ITEMS.open())}
    db = json.loads(DB.read_text())
    db_items = {i["id"]: i for i in db["items"]}
    gems_by_id = {g["id"]: g["name"] for g in db["gems"]}
    enchant_by_effect = {e["effectId"]: e["name"] for e in db["enchants"]}
    consumable_name = {}
    for group in ("items", "gems"):
        for entry in db.get(group) or []:
            consumable_name[entry["id"]] = entry["name"]

    buffs_doc = yaml.safe_load(BUFFS.read_text())
    roster = yaml.safe_load(ROSTER.read_text())
    party_of: dict[str, str] = {}
    for group in roster.get("groups") or []:
        for member in group.get("members") or []:
            party_of.setdefault(member, group["id"])

    talents = yaml.safe_load(
        Path("data/facts/talents.yaml").read_text(
        ))["wowsims_talent_strings"]["strings"]

    detail_dir = args.out / "sims"
    detail_dir.mkdir(parents=True, exist_ok=True)
    for stale in detail_dir.glob("*.md"):
        stale.unlink()

    written = 0
    for spec in specs:
        for anchor, label, _why in ANCHORS:
            row = by_key.get((spec, anchor))
            if row is None:
                continue
            written += write_detail(
                detail_dir, spec, anchor, label, row, meta, items_csv,
                db_items, gems_by_id, enchant_by_effect, consumable_name,
                buffs_doc, party_of, talents)

    write_index(args.out / "sims.md", specs, by_key, meta)
    print(f"1 index and {written} set page(s) -> {args.out}/sims.md, "
          f"{detail_dir}/")
    return 0


def write_index(path: Path, specs: list[str], by_key: dict,
                meta: dict) -> None:
    """The one table, and the warnings that have to travel with it."""
    header = ["Spec"] + [label for _a, label, _w in ANCHORS] \
        + ["Entry to BiS"]
    rows = []
    for spec in specs:
        cells = [SPEC_LABEL.get(spec, spec)]
        for anchor, label, _why in ANCHORS:
            row = by_key.get((spec, anchor))
            if row is None:
                cells.append("not simulated")
                continue
            cells.append(f"[{figure(row)}](sims/{slug(spec, anchor)}.md)")
        entry, bis = by_key.get((spec, "entry")), by_key.get((spec, "bis"))
        cells.append(f"{bis['dps'] - entry['dps']:+.1f}"
                     if entry and bis else "not comparable")
        rows.append(cells)

    body = f"""---
title: Simulated Throughput
eyebrow: Measurement
subtitle: >-
  What each spec measures at three gear anchors, with the spread on every
  figure, and the exact set behind each one.
status: draft
updated: 2026-08-15
generated: data/facts/sim-figures.yaml
---

{BANNER}

A published best-in-slot list answers "is this item my best in slot". This page
answers a different question: **what does a spec actually measure, wearing a
stated set, against a stated encounter.** It does not answer which spec is
better, and the numbers below must not be read that way. Two rows are two
classes running two rotations written by other people, and the rotation quality
varies between specs far more than it varies within one. **The comparison that
carries meaning is a spec against ITSELF at another anchor**, which is why the
last column exists and why nothing here is sorted by damage.

::: {{.note .veto}}
**The plus or minus is ONE standard error, not a confidence interval.** It is
the spread across iterations divided by the square root of
{meta['iterations']}, and it covers about 68 percent rather than 95. Two figures
whose intervals do not quite overlap are not thereby separated. Ruled by the
guild lead on 15 August 2026.
:::

## The three anchors

Every figure on this page belongs to one of three sets, and reading a figure
without knowing which set it came from is how the two warriors got called weak.

{rows_table(["Anchor", "What the set is"],
            [[label, why] for _a, label, why in ANCHORS])}

::: {{.note}}
**The Tier anchor is not a Phase 3 set.** It is the entry set with only the five
token slots reconsidered, so weapons and trinkets are identical to entry and six
specs still swing Season 2 arena weapons there. A negative Entry to Tier
movement means the tier ARMOR is a small net downgrade for that spec, and it
does not mean the spec is weak in Phase 3. The BiS column is what separates
those two readings.
:::

## What each spec measures

Every figure below is a click into the set that produced it: seventeen slots
with their enchants and gems, the consumables drunk, the buffs and debuffs
applied, the talent string and the rotation.

{rows_table(header, rows)}

## How every figure was produced

Two runs are subtractable only when everything around the gear was held still.
This table states what was held still, and it is the same for every row above.

{rows_table(["Setting", "Value"], [
    ["Simulator", meta.get("simulator", "unrecorded")],
    ["Iterations", str(meta["iterations"])],
    ["Random seed", str(meta["seed"])],
    ["Encounter", f"{meta['encounter_seconds']} seconds, "
                  f"{meta['targets']} target at level {meta['target_level']}"],
    ["Interval", "one standard error on the mean"],
])}

## What is not on this page

Four specs are absent, and each for a stated reason rather than an oversight.

- **The three tanks**, Feral Bear, Protection Paladin and Protection Warrior.
  Ruled out of scope by the guild lead on 14 August 2026: a tank run answers
  survivability questions this project does not ask.
- **The Feral Cat.** Its preset in this build of the simulator is a stub with no
  rotation and no talents, and eleven of the fourteen files in the cat directory
  are excluded from the build, so the abilities are not compiled in. A figure
  from it would be a non-result rather than a low one.
- **The four healers.** No healer has a captured gear set, and the simulator
  checkout excludes the shaman healing code from compilation for the same
  underscore reason.
"""
    path.write_text(body)


def write_detail(directory: Path, spec: str, anchor: str, label: str,
                 row: dict, meta: dict, items_csv: dict, db_items: dict,
                 gems_by_id: dict, enchant_by_effect: dict,
                 consumable_name: dict, buffs_doc: dict, party_of: dict,
                 talents: dict) -> int:
    """One page: the whole request, in the order a reader checks it."""
    gear_path = Path("data/sim/gear") / f"{gear_stem(spec, anchor)}.gear.json"
    if not gear_path.is_file():
        # LOUD, NOT SKIPPED. A missing gear file used to return 0 here in
        # silence, and the index went on rendering a link to a page that was
        # never written. A figure with no set behind it is exactly what this
        # page exists to make impossible.
        raise SystemExit(
            f"error: {gear_path} does not exist, but sim-figures.yaml carries "
            f"a figure for {spec} at {anchor}. Rerun `just regen` to rebuild "
            "the profiles, or rerun `just sim` so the figures match them.")
    gear = json.loads(gear_path.read_text())

    gear_rows = []
    for i, slot in enumerate(run_sims.SLOT_ORDER):
        entry = gear["items"][i] if i < len(gear["items"]) else {}
        if not entry:
            gear_rows.append([SLOT_LABEL[slot], "*empty*", "", ""])
            continue
        item_id = entry["id"]
        name = (items_csv.get(item_id) or {}).get("name") \
            or (db_items.get(item_id) or {}).get("name") or str(item_id)
        enchant = enchant_by_effect.get(entry.get("enchant"), "")
        gems = ", ".join(f"`{gems_by_id.get(g, g)}`" for g in entry.get("gems", []))
        gear_rows.append([SLOT_LABEL[slot], f"`{name}`",
                          f"`{enchant}`" if enchant else "", gems])

    # THE NAME COMES FROM THE FACT TABLE, NOT FROM THE ITEM DATABASE. A flask,
    # a food and an oil are not in `db.json.items`, so a database lookup returns
    # the raw id and the page prints `22854`, which nobody can check against the
    # guide the pick came from. consumable-ids.yaml records the name beside the
    # id for exactly this reason.
    key = anchor.replace("-", "_")
    consumables = run_sims.consumables_for(spec, key)
    picks = ((yaml.safe_load(Path("data/facts/consumable-ids.yaml").read_text()
                             ).get("picks") or {}).get(spec) or {}).get(key) or {}
    named = {}
    for field, entry in picks.items():
        camel = field.split("_")[0] + "".join(
            w.title() for w in field.split("_")[1:])
        named[camel] = entry.get("name")
    consumable_rows = []
    for field, value in sorted(consumables.items()):
        if field == "potions":
            continue
        label = named.get(field) or consumable_name.get(value) or str(value)
        consumable_rows.append([f"`{field}`", f"`{label}`", str(value)])

    raid, party, debuffs = run_sims.buffs_for(spec, buffs_doc, party_of)
    types = run_sims.proto_field_types()
    individual = {}
    wanted = ["blessingOfKings",
              "blessingOfMight" if spec in run_sims.PHYSICAL
              else "blessingOfWisdom"]
    if spec in run_sims.PHYSICAL and party_of.get(spec) in ("g1", "g2"):
        wanted.append("unleashedRage")
    if party_of.get(spec) == "g4":
        wanted.append("shadowPriestDps")
    for field in wanted:
        value = run_sims.typed(field, types["IndividualBuffs"][field])
        if value is not None:
            individual[field] = value

    def buff_rows(block: dict) -> list[list[str]]:
        return [[f"`{k}`", f"`{v}`"] for k, v in sorted(block.items())]

    divergence = gear.get("_divergence") or []
    routing = []
    capture = BIS_CAPTURES / f"{spec.replace('_', '-')}.yaml"
    if anchor == "bis" and capture.is_file():
        routing = yaml.safe_load(capture.read_text()).get("routing_applied") or []

    spec_label = SPEC_LABEL.get(spec, spec)
    body = f"""---
title: {spec_label}, {label} Set
eyebrow: Simulated Set
subtitle: >-
  The whole request behind one figure: {figure(row)} damage per second.
status: draft
updated: 2026-08-15
generated: data/sim/gear/{gear_stem(spec, anchor)}.gear.json
---

{BANNER}

This page answers "what exactly was simulated to get that number". It does not
argue that the set is correct, and it does not price any item on it. It is the
request, written out, so the figure above it can be reproduced or disproved.

Back to [Simulated Throughput](../sims.md).

{rows_table(["Figure", "Value"], [
    ["Damage per second", f"**{row['dps']:.1f}**"],
    ["Standard error on the mean",
     f"± {row['standard_error']:.2f}" if row.get('standard_error') is not None
     else "not recorded"],
    ["Spread across iterations",
     f"{row['stdev']:.1f}" if row.get('stdev') is not None else "not recorded"],
    ["Anchor", f"{label}. {dict((a, w) for a, _l, w in ANCHORS)[anchor]}"],
])}

::: {{.note .veto}}
**The plus or minus is ONE standard error**, the spread across iterations
divided by the square root of {meta['iterations']}. It covers about 68 percent,
not 95.
:::
"""

    if divergence:
        body += "\n::: {.note .veto}\n**This profile does NOT wear what the "
        body += "compendium says this spec wears.**\n\n"
        for line in divergence:
            body += f"- {line}\n"
        body += ":::\n"

    if routing:
        body += """
## Where this set differs from the published page

The Phase 3 list was captured from Wowhead and is never edited. A published list
ranks a weapon for one spec in isolation, and a raid has one of each, so the
guild lead routed the contested weapons on 15 August 2026. Those rulings are
applied when this profile is built, which is why the capture and the set below
disagree in these slots and only these.

"""
        for line in routing:
            body += f"- {line}\n"

    body += f"""
## The set

Seventeen slots, with the enchant and the gems each carries. An empty row is a
slot the profile deliberately leaves unfilled, which for a two-handed weapon is
the off hand.

{rows_table(["Slot", "Item", "Enchant", "Gems"], gear_rows)}

## Consumables

Consumables are assumed in every run, per the framework, and they are not
counted in the hit cap states, because those two settings answer different
questions.

{rows_table(["Field", "Consumable", "Item id"], consumable_rows)}

## Buffs and debuffs

The rest of the raid is not simulated. Its whole contribution is the four blocks
below, derived from the roster rather than switched on wholesale, so a spec gets
a totem only when it sits in the party carrying it.

The raid-wide buffs every party receives.

{rows_table(["Field", "Value"], buff_rows(raid)) if raid
 else "None recorded."}

The party buffs this spec receives, from party `{party_of.get(spec, 'unplaced')}`.

{rows_table(["Field", "Value"], buff_rows(party)) if party
 else "None recorded."}

The buffs applied to this player alone.

{rows_table(["Field", "Value"], buff_rows(individual)) if individual
 else "None recorded."}

The debuffs applied to the target.

{rows_table(["Field", "Value"], buff_rows(debuffs)) if debuffs
 else "None recorded."}

## Talents, rotation and encounter

The rotation is the action priority list the simulator itself ships for this
spec. Writing our own would be a modelling choice we could not defend, and
taking theirs is one we can cite.

{rows_table(["Setting", "Value"], [
    ["Talent string", f"`{(talents.get(spec) or {}).get('string', 'none')}`"],
    ["Rotation", f"`ui/{run_sims.APL[spec]}`"],
    ["Simulator", meta.get("simulator", "unrecorded")],
    ["Iterations", str(meta["iterations"])],
    ["Random seed", str(meta["seed"])],
    ["Encounter", f"{meta['encounter_seconds']} seconds, "
                  f"{meta['targets']} target at level {meta['target_level']}"],
])}
"""
    (directory / f"{slug(spec, anchor)}.md").write_text(body)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
