#!/usr/bin/env python3
"""Write one page per Mount Hyjal and Black Temple item.

NO PAGE CARRIES DATA. Every page written here is the item's name, the specs
that contest it with each one's standing, and nothing else. The stat line, the
drop source, the sockets, the comparison baselines and the cap positions are
all read at build time from the fact files, exactly as they are on the worked
example in docs/conventions.md. A figure typed into a page is a figure that
goes stale, and 177 pages is 177 chances for that. The standing is the one
derived label a page states, as an attribute on each claimant heading, because
it is computed here from the best-in-slot captures rather than typed.

WHICH SPECS EARN A CARD. A spec earns one where the item ranks in the top five
of its slot section on that spec's workbook tab, which is the same shortlist a
spec page reads down. One rule, two views, so the two cannot disagree: a spec
that would be shown the item on its own page is a spec the item page shows as a
claimant.

The rule is generous on purpose. A missing card hides a claimant, which is the
failure that matters; an extra card is an Upgrade the council reads past. Five
Tier 6 drops appear in no ladder at all and still get a page, where the empty
cards block says so in its own words.

THE PAGES ARE GENERATED AND DEFEND THEMSELVES. A hand edit to one is lost on the
next `just regen`, and `just check` regenerates and diffs. To change what a page
says, change the data it reads or this file.

Usage:
    python3 tools/generate_item_pages.py --out docs/items
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_bis_sets import CAPTURES, DISPLAY, bis_ids  # noqa: E402
from extract_ladder import (  # noqa: E402
    ENHANCEMENT_SPEC, ENHANCEMENT_SPEED_FLOOR, LEVEL_60, SHORTLIST, SPECS,
    WEAPON_SECTION_NAMES, WIDE_SECTIONS,
    WIDE_SHORTLIST, WORKBOOK, enhancement_slow_only, hunter_no_crafted,
    select, weapon_speeds,
    WORLD_BOSSES, level_60_locations, read_tab, world_boss_ids,
)

ITEMS = Path("data/facts/items.csv")
DROPS = Path("data/facts/drops.csv")

# The tiers that get a page. Mount Hyjal and Black Temple are Tier 6; the
# earlier tiers stay in the data as the gear the roster wears in.
TIERS = ("T6",)

BANNER = (
    "<!-- GENERATED BY tools/generate_item_pages.py. DO NOT EDIT.\n"
    "     Every figure on this page is read at build time from data/facts,\n"
    "     and every standing from the best-in-slot captures. To change what\n"
    "     it says, change the data. -->"
)


def slug(name: str) -> str:
    """A file name from an item name. Stable, because it is a URL."""
    text = name.lower().replace("'", "")
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")



# A CLASS-LOCKED RELIC IS CLAIMED BY ITS CLASS, ruled by the guild lead on 12
# August 2026: relics are owned by a class type, and by more than one spec
# inside that class.
#
# THIS IS THE ONE CLAIMANT NOT DERIVED FROM A WORKBOOK RANK, and it exists
# because eleven of the twenty-one tabs carry no `Ranged` section at all. Every
# druid, paladin and shaman tab is among them, which is exactly the three
# classes whose relic slot holds an idol, a libram or a totem. So the workbook
# ranks no relic for the only classes that can wear one, and three Phase 3
# relics reached the compendium claimed by nobody.
#
# THE LOCK IS CARRIED BY `ranged_weapon_type`, NOT BY `class_allowlist`, which
# is empty for all three. A review on 11 August 2026 caught a draft of this rule
# phrased on the allowlist, which names data that does not exist.
RELIC_TYPE_TO_CLASS = {"6": "druid", "7": "paladin", "8": "shaman"}

SPEC_CLASS = {
    "Feral Bear": "druid", "Feral Cat": "druid", "Balance Druid": "druid",
    "Restoration Druid": "druid",
    "Retribution Paladin": "paladin", "Protection Paladin": "paladin",
    "Holy Paladin": "paladin",
    "Elemental Shaman": "shaman", "Enhancement Shaman": "shaman",
    "Restoration Shaman": "shaman",
}

# THE MAP ABOVE STOPS AT THREE CLASSES, because relics belong to Druids,
# Paladins and Shamans and that is all it was written for. A class-locked
# trinket exists for all nine classes, so the general question, which class is
# this spec, is answered here instead. Every spec name but the two Feral ones
# contains its own class.
CLASSES = ("warrior", "paladin", "hunter", "rogue", "priest", "shaman",
           "mage", "warlock", "druid")

UNSPOKEN_CLASS = {"Feral Bear": "druid", "Feral Cat": "druid"}


def spec_class(spec: str) -> str | None:
    if spec in UNSPOKEN_CLASS:
        return UNSPOKEN_CLASS[spec]
    lowered = spec.lower()
    for name in CLASSES:
        if name in lowered:
            return name
    return None


def class_locked_claimants(item_ids: set[str],
                          items: dict[str, dict]) -> dict[str, list[str]]:
    """Every spec of the class an item is locked to.

    A workbook rank cannot supply the claimants for an item no tab ranks, and
    seven of the nine Ashtongue Deathsworn trinkets are ranked by no tab. The
    lock is the claim: an item only a Paladin may equip is contested by the
    three Paladin specs and by nobody else.

    REPUTATION REWARDS ONLY, and the narrowing is deliberate. A tier piece also
    names one class, so an unrestricted rule added every spec of that class to
    all 190 tier pages, silently widening claimants the ladder had already
    decided. The ladder answers for anything it ranks; this answers only where
    it says nothing.
    """
    out: dict[str, list[str]] = {}
    for item_id in item_ids:
        row = items.get(item_id)
        if not row or "reputation" not in row.get("source", ""):
            continue
        names = [n for n in (row.get("class_allowlist") or "").split("|") if n]
        if len(names) != 1:
            continue
        owner = names[0].lower()
        out[item_id] = [spec for spec in SPECS if spec_class(spec) == owner]
    return out


def relic_claimants(item_ids: set[str], items: dict[str, dict]) -> dict[str, list[str]]:
    """Every spec of the class a relic belongs to.

    A relic carries no stat line, so no ladder could rank it on stats even if a
    tab held the section. What decides the claim is the class lock and the
    effect, and the effect is recorded in data/facts/item-effects.csv rather
    than here: this function answers WHO CAN WEAR IT, and the effect answers who
    wants it. Both belong on the page.
    """
    out: dict[str, list[str]] = {}
    for item_id in item_ids:
        row = items.get(item_id)
        if not row or row.get("slot") != "Ranged":
            continue
        # A ranged WEAPON has weapon damage. A relic has none.
        if row.get("weapon_min"):
            continue
        owner = RELIC_TYPE_TO_CLASS.get(row.get("ranged_weapon_type", ""))
        if not owner:
            continue
        out[item_id] = [spec for spec, cls in SPEC_CLASS.items() if cls == owner]
    return out


def claimants(item_ids: set[str],
              speed_of: dict[int, float]) -> dict[str, list[str]]:
    """Which specs rank each item in the top five of its slot.

    Read straight from the workbook tabs rather than from the generated ladder,
    because the generated table holds the shortlist per spec and this needs it
    inverted, per item. The selection rule is the same one `shortlist` applies:
    arena armor out, arena weapons in, every phase kept.
    """
    # THE SAME EXCLUSIONS THE LADDER APPLIES, or this counts a different top
    # five from the one the compendium shows. Until 10 August 2026 this filtered
    # arena armor and nothing else, so a world-boss or level-60 row could hold a
    # top-five place here while the ladder excluded it, and the item ranked
    # sixth lost a claimant it should have had.
    world_boss = world_boss_ids(WORLD_BOSSES)
    level_60 = level_60_locations(LEVEL_60)

    out: dict[str, list[str]] = {item_id: [] for item_id in item_ids}
    for spec, (tab, _) in SPECS.items():
        ladder = read_tab(WORKBOOK / tab)
        for section, rows in ladder.items():
            arena_allowed = section in WEAPON_SECTION_NAMES
            eligible = [
                row for row in rows
                if row["item_id"]
                and row["item_id"] not in world_boss
                and row["location"] not in level_60
                and (arena_allowed or row["route"] != "arena")
            ]
            # THE SAME SPEED RULE THE LADDER APPLIES, before the cut, so the
            # backfilled slow weapons gain their claimant here exactly as they
            # gain their shortlist row there.
            eligible = enhancement_slow_only(spec, section, eligible, speed_of)
            eligible = hunter_no_crafted(spec, section, eligible)
            eligible.sort(key=lambda row: row["epv"], reverse=True)
            # THE SAME SELECTION THE LADDER APPLIES, or this counts a different
            # list from the one the compendium shows.
            limit = (WIDE_SHORTLIST if section in WIDE_SECTIONS
                     else SHORTLIST)
            for row in select(eligible, limit):
                key = str(row["item_id"])
                if key in out and spec not in out[key]:
                    out[key].append(spec)
    return out


def share_within_weapon_sets(contested: dict[str, list[str]],
                             items: dict[str, dict],
                             speed_of: dict[int, float]) -> None:
    """A spec claiming one half of a paired weapon claims the other half.

    THE WORKBOOK PRICES AN OFF-HAND WEAPON AS A MAIN HAND, because most tabs
    carry one weapon ladder and it is the main-hand one. The off-hand Warglaive
    of Azzinoth therefore scores 226.90 against the main-hand glaive's 1102.26
    on the Combat Rogue tab and lands at rank 31 of 60, so the top-five rule
    gave it no claimant at all and its page read as an item nobody wants. That
    is a scoring context, not a fact about the item.

    The item table already answers it. Both halves carry the same `set_name`,
    and the only two weapon sets in the tier are matched pairs: The Twin Blades
    of Azzinoth and The Fists of Fury. The off hand of a pair is wanted by
    whoever wants the main hand and by nobody else, so the claimants are shared
    across the set.

    Limited to WEAPON sets on purpose. A tier set is five pieces in five slots,
    each of which the workbook ranks in its own right, so sharing claimants
    across one would add cards the data does not support.

    THE ENHANCEMENT SPEED RULE HOLDS THROUGH THE SHARE. The Fists of Fury pair
    Claw of Molten Fury at 2.7 with Fist of Molten Fury at 1.5, so a share that
    ignored speed would hand the fast half an Enhancement claimant the ladder
    just removed. A shared claimant lands on a set member only where the member
    passes the same speed rule the shortlist applied, per
    data/judgments/enhancement-weapon-rules.yaml.
    """
    members: dict[str, list[str]] = {}
    for item_id, row in items.items():
        if row["slot"] == "Weapon" and row["set_name"]:
            members.setdefault(row["set_name"], []).append(item_id)
    for set_name, ids in members.items():
        shared: list[str] = []
        for item_id in ids:
            for spec in contested.get(item_id, []):
                if spec not in shared:
                    shared.append(spec)
        for item_id in ids:
            if item_id in contested:
                kept = list(shared)
                speed = speed_of.get(int(item_id))
                if speed is not None and speed <= ENHANCEMENT_SPEED_FLOOR:
                    kept = [spec for spec in kept if spec != ENHANCEMENT_SPEC]
                contested[item_id] = kept


def bis_sets() -> dict[str, set[int]]:
    """Which item ids each spec's best-in-slot simulated set wears.

    Read from the same captures tools/extract_bis_sets.py reads, through that
    tool's own `bis_ids`, so the standing a page states and the one the spec
    pages derive start at the same bytes. A spec with no capture, which is the
    tanks, the healers and the Feral Cat, is simply absent, and every claim it
    holds states Upgrade.
    """
    sets: dict[str, set[int]] = {}
    for path in sorted(CAPTURES.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text())
        key = doc.get("spec") or path.stem.replace("-", "_")
        name = DISPLAY.get(key)
        if name is not None:
            sets[name] = bis_ids(doc)
    return sets


def page(row: dict, specs: list[str], ambiguous: bool,
         bis: dict[str, set[int]]) -> str:
    """One item page. The item is named; nothing else is stated."""
    # The id goes beside the name only where the item table holds another item
    # by that name, which is the rule docs/kb/DEVELOPING.md sets for a human
    # author. A generator has no more licence than an author to add noise.
    ref = f"[{row['name']}]{{.item"
    ref += f" item={row['item_id']}}}" if ambiguous else "}"

    lines = [
        "---",
        f"title: {row['name']}",
        "---",
        "",
        BANNER,
        "",
        ":::: {.subject}",
        "",
        ref,
        "",
        "::: {.commentary}",
        "",
        ref,
        "",
        ":::",
        "",
        "::: {.specs}",
        "",
    ]
    # THE STANDING RIDES ON THE HEADING AS AN ATTRIBUTE, never as a written
    # field: a Standing field in a document fails the build, exactly as a
    # Priority field does, because both are generated vocabulary. BIS where
    # this spec's best-in-slot simulated set wears the item, Upgrade for every
    # other claimant, including every spec with no simulated set.
    for spec in specs:
        standing = "BIS" if int(row["item_id"]) in bis.get(spec, set()) \
            else "Upgrade"
        lines += [f"#### {spec} {{standing={standing}}}", "",
                  "Delta", f":   {ref}", ""]
    lines += [":::", "", "::::", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--items", type=Path, default=ITEMS)
    ap.add_argument("--drops", type=Path, default=DROPS)
    ap.add_argument("--db", type=Path, required=True, help="WoWSims db.json")
    ap.add_argument("--out", type=Path, default=Path("docs/items"))
    args = ap.parse_args()

    if not args.db.exists():
        print(f"error: database not found: {args.db}", file=sys.stderr)
        return 2
    # Speeds come from db.json rather than items.csv for the same reason
    # extract_ladder reads them there: the speed rule decides which ids
    # items.csv holds, so reading speeds back out of items.csv is a cycle.
    speed_of = weapon_speeds(json.loads(args.db.read_text()))

    items = {r["item_id"]: r for r in csv.DictReader(args.items.open())}
    dropped = {
        r["item_id"] for r in csv.DictReader(args.drops.open())
        if r["tier"] in TIERS
    }
    missing = sorted(dropped - set(items))
    if missing:
        print(f"error: {len(missing)} dropped item(s) are not in {args.items}: "
              f"{', '.join(missing)}", file=sys.stderr)
        return 1

    # Two items sharing a name need the id written beside it on both pages.
    by_name: dict[str, int] = {}
    for row in items.values():
        by_name[row["name"].lower()] = by_name.get(row["name"].lower(), 0) + 1

    # TIER PIECES GET A PAGE TOO, and they are not in the drop table because a
    # tier set piece is bought from a vendor with a token rather than dropped.
    # Reported by the guild lead on 10 August 2026 from the built site: clicking
    # a tier item on a spec page left for Wowhead while every non-tier item
    # stayed here. That was not a link bug. shortlist.lua falls back to the
    # Wowhead bubble for anything with no page, which is right behaviour on a
    # wrong input, and 190 of the 697 items the ladder references are tier
    # pieces, so 27 percent of everything clickable behaved differently.
    #
    # TIER 6 ONLY. The 105 earlier-tier pieces keep linking out, because this
    # phase does not route them and a page each is 105 more chances for a figure
    # to go stale, which the header above warns about.
    tier_pieces = {
        item_id for item_id, row in items.items()
        if row.get("source") == "tier_vendor" and row.get("tier") in TIERS
    }
    # A REPUTATION REWARD IS PHASE 3 LOOT AND HAD NO PAGE. Pages are keyed on
    # the drop table, and the nine Ashtongue Deathsworn trinkets are bought at
    # Exalted rather than dropped, so all nine were reachable from nowhere: no
    # card, and no row on any boss page. They are class-locked, so each one has
    # exactly one set of claimants and a page has something to say.
    reputation = {
        item_id for item_id, row in items.items()
        if "reputation" in row.get("source", "") and row.get("tier") in TIERS
    }
    subjects = dropped | tier_pieces | reputation

    contested = claimants(subjects, speed_of)
    # A relic is claimed by its class, not by a workbook rank. Merged after the
    # ladder pass so it can only ADD a claimant, never remove one the workbook
    # supplied.
    for source in (relic_claimants(subjects, items),
                   class_locked_claimants(subjects, items)):
        for item_id, specs in source.items():
            for spec in specs:
                if spec not in contested.setdefault(item_id, []):
                    contested[item_id].append(spec)
    share_within_weapon_sets(contested, items, speed_of)
    bis = bis_sets()

    # The directory is rebuilt rather than added to, so an item removed from the
    # drop table does not leave a page behind describing loot that is not there.
    args.out.mkdir(parents=True, exist_ok=True)
    for stale in args.out.glob("*.md"):
        stale.unlink()

    written, unclaimed = 0, 0
    written_pages: dict[str, str] = {}
    # SORTED BY NAME AND THEN BY ID. `dropped` is a set, so a tie on the name
    # broke in whatever order the set happened to iterate, and the two
    # Warglaives of Azzinoth swapped file names between runs. `just check`
    # caught it, which is what it is for.
    for item_id in sorted(subjects, key=lambda i: (items[i]["name"], int(i))):
        row = items[item_id]
        specs = contested[item_id]
        if not specs:
            unclaimed += 1
        # A shared name puts the id on BOTH file names rather than on the second
        # one to be written. Naming one of a pair for its name and the other for
        # its id would make the plain name mean whichever was processed first,
        # which is neither stable nor readable.
        ambiguous = by_name[row["name"].lower()] > 1
        base = slug(row["name"])
        if ambiguous:
            base = f"{base}-{item_id}"
        (args.out / f"{base}.md").write_text(page(row, specs, ambiguous, bis))
        written_pages[item_id] = base
        written += 1

    # WHERE EACH ITEM'S PAGE IS, for the filters that link to it. The slug rule
    # lives here and nowhere else, so a spec page linking to an item page reads
    # this rather than rebuilding the rule and drifting from it.
    index = Path("theme/filters/pages.generated.lua")
    lines = [
        "-- GENERATED BY tools/generate_item_pages.py. DO NOT EDIT.",
        "--",
        "-- Which page each item was written to, keyed by item id. Read by",
        "-- shortlist.lua so a spec page can link to the item page rather than",
        "-- to Wowhead, and written here because this file owns the slug rule.",
        "return {",
    ]
    for item_id in sorted(written_pages, key=int):
        lines.append(f'  ["{item_id}"] = "{written_pages[item_id]}",')
    lines.append("}")
    index.write_text("\n".join(lines) + "\n")

    cards = sum(len(v) for v in contested.values())
    print(f"{written} item page(s) -> {args.out}")
    print(f"  {cards} claimant card(s), {unclaimed} item(s) no spec ranks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
