#!/usr/bin/env python3
"""Write one page per rostered spec, and the two indexes into the compendium.

NO PAGE CARRIES DATA. A spec page is the spec's name inside a `.shortlist`
block; `theme/filters/shortlist.lua` fills in every row from the generated
ladder and the judgment store. An index is a list of links, and the links are
derived from the same drop table the item pages are.

TWO WAYS IN, because a council asks two different questions. When a drop
lands, the question is who wants it, and the boss index leads to the item page.
When a week is being planned, the question is what a player still needs, and the
spec index leads to the spec page. Both are generated, so an item added to the
drop table cannot be missing from either.

Usage:
    python3 tools/generate_spec_pages.py
"""

from __future__ import annotations

import argparse
import collections
import csv
import re

import yaml
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_ladder import SPECS  # noqa: E402
from generate_item_pages import TIERS, slug  # noqa: E402

ITEMS = Path("data/facts/items.csv")
DROPS = Path("data/facts/drops.csv")
PROGRESSION = Path("data/facts/progression.yaml")


def encounter_order() -> tuple[list[str], dict[tuple[str, str], int]]:
    """The zones in progression order, and each boss's position within one.

    THE INDEX USED TO READ ALPHABETICALLY, which put Gurtogg Bloodboil first in
    Black Temple and Archimonde second in Mount Hyjal. A raid does not meet them
    in that order, and the index exists to be opened before a pull, so the one
    ordering it must not use is the one that ignores the instance.

    THE ORDER IS NOT RESTATED HERE. `data/facts/progression.yaml` already holds
    it as a fact, says in its own words that it is a fact rather than a
    forecast, and is cross-checked against the drop table by `just check`. A
    second copy in this file is the copy that would go stale.
    """
    doc = yaml.safe_load(PROGRESSION.read_text())
    zones, positions = [], {}
    for zone, block in doc["zones"].items():
        zones.append(zone)
        for boss in block["bosses"]:
            positions[(zone, boss["name"])] = boss["position"]
    return zones, positions

BANNER = (
    "<!-- GENERATED BY tools/generate_spec_pages.py. DO NOT EDIT.\n"
    "     Every row is read at build time from data/facts and data/judgments.\n"
    "     To change what it says, change the data. -->"
)


def spec_page(name: str) -> str:
    return "\n".join([
        "---",
        f"title: {name}",
        "---",
        "",
        BANNER,
        "",
        "::: {.shortlist}",
        name,
        ":::",
        "",
    ])


def page_name(row: dict, ambiguous: bool) -> str:
    """The file an item's page was written to. Must match the item generator."""
    base = slug(row["name"])
    return f"{base}-{row['item_id']}" if ambiguous else base


def link_text(row: dict, ambiguous: bool) -> str:
    """The name to show, which the hand qualifies where two items share it.

    The same rule itemdb.display_name applies on a page. Two rows reading
    `Warglaive of Azzinoth` one under the other tell a reader nothing about
    which is which, and the index is where they are seen side by side.
    """
    if ambiguous and row["hand_type"]:
        return f"{row['name']} ({row['hand_type']})"
    return row["name"]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--items", type=Path, default=ITEMS)
    ap.add_argument("--drops", type=Path, default=DROPS)
    ap.add_argument("--specs-out", type=Path, default=Path("docs/specs"))
    ap.add_argument("--index-out", type=Path, default=Path("docs"))
    args = ap.parse_args()

    items = {r["item_id"]: r for r in csv.DictReader(args.items.open())}
    drops = [r for r in csv.DictReader(args.drops.open()) if r["tier"] in TIERS]

    by_name: dict[str, int] = collections.Counter(
        r["name"].lower() for r in items.values())

    # ---------------------------------------------------------- spec pages
    args.specs_out.mkdir(parents=True, exist_ok=True)
    for stale in args.specs_out.glob("*.md"):
        stale.unlink()
    for name in sorted(SPECS):
        (args.specs_out / f"{slug(name)}.md").write_text(spec_page(name))
    print(f"{len(SPECS)} spec page(s) -> {args.specs_out}")

    # ---------------------------------------------------------- boss index
    # Zone, then boss, then item. A boss dropping one item into several zones
    # does not happen, and a shared trash entry is recorded per zone already.
    by_boss: dict[tuple[str, str], set[str]] = collections.defaultdict(set)
    for row in drops:
        by_boss[(row["zone"], row["boss"])].add(row["item_id"])

    # A REPUTATION REWARD HAS A PAGE AND HAD NO WAY IN. This index is built from
    # the drop table, so the nine Ashtongue Deathsworn trinkets appeared under
    # no zone and no boss, and their pages were reachable only from a spec page.
    # The index answers "where does this come from", and a quartermaster is an
    # answer to that question, so it is a group here like a boss is. The zone
    # and the standing come from the item table rather than being written out,
    # so a second faction would need no change.
    for item_id, row in items.items():
        if "reputation" not in row.get("source", "") or row["tier"] not in TIERS:
            continue
        by_boss[("Reputation", row["source_note"])].add(item_id)

    lines = [
        "---",
        "title: Loot By Boss",
        "eyebrow: Mount Hyjal and Black Temple",
        "subtitle: >-",
        "  Every item the two raids drop, under the boss that drops it, and the",
        "  rewards a reputation sells. Open the page for the boss you are about",
        "  to pull.",
        "---",
        "",
        BANNER,
        "",
    ]
    # Zones in progression order, then anything the file does not name, then
    # Reputation, which is not a zone and is not walked through.
    zone_order, positions = encounter_order()
    present = {z for z, _ in by_boss}
    ordered = [z for z in zone_order if z in present]
    ordered += sorted(z for z in present
                      if z not in zone_order and z != "Reputation")
    if "Reputation" in present:
        ordered.append("Reputation")

    for zone in ordered:
        lines += [f"## {zone}", ""]
        # A boss the encounter order names sorts by where it stands in the
        # instance. Trash carries no position and follows the bosses rather
        # than landing in the middle of them on its initial letter.
        def where(boss: str, zone: str = zone) -> tuple[int, str]:
            return (positions.get((zone, boss), 99), boss)

        for boss in sorted((b for z, b in by_boss if z == zone), key=where):
            # Name then id. A tie on the name broke on set iteration order and
            # the two Warglaives swapped places between runs, which `just
            # check` caught the same way it caught it in the page generator.
            ids = sorted(by_boss[(zone, boss)],
                         key=lambda i: (items[i]["name"], int(i)))
            lines += [f"### {boss}", ""]
            for item_id in ids:
                row = items[item_id]
                ambiguous = by_name[row["name"].lower()] > 1
                target = page_name(row, ambiguous)
                lines.append(
                    f"- [{link_text(row, ambiguous)}](items/{target}.md)")
            lines.append("")
    (args.index_out / "bosses.md").write_text("\n".join(lines))
    print(f"{len(by_boss)} boss/zone group(s) -> {args.index_out / 'bosses.md'}")

    # ---------------------------------------------------------- spec index
    lines = [
        "---",
        "title: Loot By Spec",
        "eyebrow: Mount Hyjal and Black Temple",
        "subtitle: >-",
        "  What each spec wants, slot by slot, from the EP Workbook. Five deep,",
        "  every phase, with the priority the council has settled where it has",
        "  settled one.",
        "---",
        "",
        BANNER,
        "",
    ]
    for name in sorted(SPECS):
        lines.append(f"- [{name}](specs/{slug(name)}.md)")
    lines.append("")
    (args.index_out / "specs.md").write_text("\n".join(lines))
    print(f"{len(SPECS)} spec link(s) -> {args.index_out / 'specs.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
