#!/usr/bin/env python3
"""Write the tokens page: who gains what from each token, and in what state.

WHAT THIS ANSWERS. The question asked at the loot table: a token drops, and
the council wants the give-out order that maximizes what each item does. The
zero-state table per token migrated here from the tier page; what this page
adds is the DECISION TREE, the same question asked state by state, because a
token's worth to a spec moves with the tier pieces that spec already holds.
A two-piece threshold makes the second token worth more than the first, so
the zero-state ordering alone can put the wrong claimant first once awards
start landing.

EVERY BRANCH IS A MEASURED SUBSET DIFFERENCE. The tier rounds in
data/facts/tier-sims.yaml price every subset of each spec's token slots on
its entry profile, so the gain of adding one piece GIVEN a held set is the
difference of two recorded rows, never a sum of one-slot readings. The
coherence backtest in data/facts/sim-results.yaml is why that distinction is
enforced: one-slot deltas do not compose across a hit cap, and subset
differences need no composing.

The break-even readings stay on the tier page; this page cross-references
them where a branch breaks an old bonus.

Usage:
    python3 tools/generate_tokens_page.py
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_sim_pages import SPEC_LABEL, figure  # noqa: E402

TIER_SIMS = Path("data/facts/tier-sims.yaml")
TOKENS = Path("data/facts/tokens.yaml")
FIGURES = Path("data/facts/sim-figures.yaml")

BANNER = ("<!-- GENERATED BY tools/generate_tokens_page.py. DO NOT EDIT.\n"
          "     Every figure is read from data/facts/tier-sims.yaml. To\n"
          "     change what it says, rerun the sims. -->")

TOKEN_SLOTS = ["head", "shoulder", "chest", "hands", "legs"]

# Two branches whose gains sit within this many combined standard errors
# are printed as tied rather than ordered.
TIE_SPAN = 2.0


def spec_class(label: str) -> str:
    lowered = label.lower()
    for name in ("warrior", "paladin", "hunter", "rogue", "priest",
                 "shaman", "mage", "warlock", "druid"):
        if name in lowered:
            return name.capitalize()
    return "Druid"


def combined_se(a: dict, b: dict) -> float:
    """One standard error for the difference of two measured rows."""
    return math.sqrt(a["standard_error"] ** 2 + b["standard_error"] ** 2)


def greedy_order(rows: list[dict]) -> list[str]:
    """The best pickup order, read greedily off the subsets."""
    by_set = {frozenset(r["replaced"]): r for r in rows}
    slots = max((r["replaced"] for r in rows), key=len, default=[])
    taken: list[str] = []
    while len(taken) < len(slots):
        candidates = [(by_set[frozenset(taken + [s])]["dps"], s)
                      for s in slots if s not in taken
                      and frozenset(taken + [s]) in by_set]
        if not candidates:
            break
        taken.append(max(candidates)[1])
    return taken


def branch_states(rows: list[dict], slot: str) -> list[dict]:
    """The measured states a token branch conditions on: the prefixes of the
    spec's own greedy pickup order with this slot removed, so a reader walks
    the states a raid actually passes through rather than all sixteen."""
    by_set = {frozenset(r["replaced"]): r for r in rows}
    order = [s for s in greedy_order(rows) if s != slot]
    out = []
    held: list[str] = []
    for step in [None] + order:
        if step is not None:
            held.append(step)
        before = by_set.get(frozenset(held))
        after = by_set.get(frozenset(held + [slot]))
        if before is None or after is None:
            continue
        out.append({
            "held": list(held),
            "gain": after["dps"] - before["dps"],
            "se": combined_se(after, before),
            "pieces_before": before.get("pieces_left") or {},
            "pieces_after": after.get("pieces_left") or {},
        })
    return out


def threshold_note(branch: dict) -> str:
    """Whether this branch turns a Tier 6 bonus on, from the recorded piece
    counts of its two rows."""
    for name, after in (branch["pieces_after"] or {}).items():
        before = (branch["pieces_before"] or {}).get(name, 0)
        for threshold in (2, 4):
            if before < threshold <= after:
                return f" and turns the {threshold}-piece on"
    return ""


def held_words(held: list[str]) -> str:
    if not held:
        return "as the first tier piece"
    if len(held) == 1:
        return "after the " + held[0]
    return "after the " + ", ".join(held[:-1]) + " and " + held[-1]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=Path("docs/tokens.md"))
    args = ap.parse_args()

    if not TIER_SIMS.is_file():
        print(f"error: no figures at {TIER_SIMS}. Produce them with\n"
              "  python3 tools/run_tier_sims.py --iterations 10000",
              file=sys.stderr)
        return 1

    doc = yaml.safe_load(TIER_SIMS.read_text())
    tokens = yaml.safe_load(TOKENS.read_text())
    figures = yaml.safe_load(FIGURES.read_text())
    default_tier = max({r.get("boss_armor", 0) for r in figures["results"]})
    entry_dps = {r["spec"]: r["dps"] for r in figures["results"]
                 if r["anchor"] == "entry"
                 and r.get("boss_armor") == default_tier}
    entry_se = {r["spec"]: r["standard_error"] for r in figures["results"]
                if r["anchor"] == "entry"
                and r.get("boss_armor") == default_tier}

    members = tokens["line_members_by_tier"][6]
    spec_to_set = tokens["spec_to_set"]
    set_pieces = {b["set_name"]: b["pieces"] for b in tokens["sets"]}
    t6_tokens = sorted((x for x in tokens["tokens"] if x.get("tier") == 6),
                       key=lambda x: (TOKEN_SLOTS.index(x["slot"]),
                                      x["name"]))

    from extract_ladder import SPECS as LADDER_SPECS
    by_class: dict[str, list[tuple[str, str]]] = {}
    for label, (_tab, key) in LADDER_SPECS.items():
        by_class.setdefault(spec_class(label), []).append((label, key))

    sections = []
    for token in t6_tokens:
        classes = members[token["line"]]
        slot = token["slot"]

        # ONE ENTRY PER CLAIMANT SPEC: the zero-state gain, its standing,
        # and where the lattice supports it, the state-conditional branches.
        ranked, unmeasured = [], []
        for cls in classes:
            for label, key in sorted(by_class.get(cls, [])):
                block = (doc["specs"] or {}).get(key)
                if block is None:
                    unmeasured.append(label)
                    continue
                t6 = block.get("tier_six") or {}
                pieces = t6.get("pieces") or {}
                rows = t6.get("rows") or []
                singles = block.get("token_singles") or {}
                set6 = (spec_to_set.get(key) or {}).get(6)
                token_piece = ((set_pieces.get(set6) or {}).get(slot) or {})
                token_id = int(token_piece.get("item_id") or -1)
                worn = pieces.get(slot) or {}
                gain, se, note, branches = None, None, "", []
                if int(worn.get("id") or 0) == token_id and rows:
                    by_set = {frozenset(r["replaced"]): r for r in rows}
                    empty = by_set.get(frozenset())
                    first = by_set.get(frozenset([slot]))
                    if empty and first:
                        gain = round(first["dps"] - empty["dps"], 1)
                        se = combined_se(first, empty)
                    note = "BIS"
                    branches = branch_states(rows, slot)
                elif slot in singles:
                    base = entry_dps.get(key)
                    if base is not None:
                        gain = round(singles[slot]["dps"] - base, 1)
                        se = math.sqrt(
                            singles[slot]["standard_error"] ** 2
                            + entry_se.get(key, 0.0) ** 2)
                    note = "Not BIS"
                ranked.append({
                    "gain": gain, "se": se, "label": label,
                    "piece": token_piece.get("name", ""), "note": note,
                    "branches": branches, "key": key,
                })
        ranked.sort(key=lambda r: (r["gain"] is None, -(r["gain"] or 0)))

        parts = [f"## {token['name']}", "",
                 f"Drops from {token['boss']}. Classes: "
                 f"{', '.join(classes)}.", ""]

        if ranked:
            parts += ["| Order | Spec | Gain | Buys | Standing |",
                      "|---|---|---|---|---|"]
            for i, r in enumerate(ranked, 1):
                cell = ("not measured" if r["gain"] is None
                        else f"{r['gain']:+.1f}")
                parts.append(f"| {i} | {r['label']} | {cell} | "
                             f"{r['piece']} | {r['note']} |")
            parts.append("")

        # THE TREE. The give-out order above is the zero state; each branch
        # below re-prices a spec's gain in the states its own pickup order
        # passes through, every figure the difference of two measured
        # subset rows.
        measured = [r for r in ranked if r["gain"] is not None]
        if measured:
            tree = ["The order, state by state:", ""]
            for i, r in enumerate(measured):
                tied = ""
                if i > 0:
                    prev = measured[i - 1]
                    span = TIE_SPAN * math.sqrt(
                        (r["se"] or 0) ** 2 + (prev["se"] or 0) ** 2)
                    if abs((prev["gain"] or 0) - (r["gain"] or 0)) <= span:
                        tied = f", tied with {prev['label']}"
                lead = ("The first of these tokens gains most at" if i == 0
                        else "Next")
                tree.append(f"- {lead} **{r['label']}**, "
                            f"{r['gain']:+.1f} ± {r['se']:.1f}{tied}.")
                for b in r["branches"]:
                    if not b["held"]:
                        continue
                    tree.append(
                        f"    - {held_words(b['held']).capitalize()}, "
                        f"this token pays {b['gain']:+.1f} ± "
                        f"{b['se']:.1f}{threshold_note(b)}.")
                if r["note"] == "Not BIS" and not r["branches"]:
                    tree.append(
                        "    - Measured alone on the entry set only: this "
                        "spec's list does not keep the piece, so the "
                        "deeper states are not in the lattice.")
            parts += tree + [""]
        if unmeasured:
            parts.append(
                "Unmeasured claimants, see [the specs the tier page cannot "
                "measure](tier.md#the-specs-this-page-cannot-measure): "
                + ", ".join(sorted(unmeasured)) + ".")
            parts.append("")
        sections.append("\n".join(parts))

    body = f"""---
title: Tokens
eyebrow: Measurement
subtitle: >-
  A token drops and the council wants the give-out order that maximizes what
  the item does: each token's claimants ranked by measured gain, then the
  same question state by state, because a token's worth moves with the tier
  pieces its taker already holds.
status: draft
updated: 2026-08-22
---

{BANNER}

Each section is one token: the specs that can redeem it, best measured gain
first, then the decision tree. Every ordering here is derived from
measurement, and the award itself is the council's call.

## How to read every figure

**Gain** in a table is the token's own piece measured alone on that spec's
entry set, against its entry figure. A first piece often reads negative
because no set bonus is active yet; the tree below the table is where the
thresholds appear. The standing says whether the token piece is in that
spec's best-in-slot set. The plus or minus is one standard error, not a
confidence interval.

**A tree branch re-prices the same token in a later state**: the gain of
adding the piece after the pieces named, read as the difference of two
measured subset rows from the tier rounds, with the spread combined from
both. Nothing is added across slots, because one-slot readings do not
survive a hit cap, which the coherence backtest measured; a subset
difference needs no adding. The states walked are the spec's own best
pickup order, so a reader follows the road the raid actually takes. Where
breaking an old bonus is the cost that makes a branch read low, the
break-even is on [Tier](tier.md).

**Every piece arrives dressed**: the gems and the enchant the exported
profile wears on it, or the spec's standard gem in each socket for a piece
outside every profile.

{chr(10).join(sections)}"""
    args.out.write_text(body)
    print(f"1 page -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
